sqle/server/auditplan/task.go
=> fix:fix time zone , use utc time

sqle/api/app.go, sqle/api/controller/v1/statistic.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Fix issue1629

sqle/api/app.go, sqle/api/controller/v1/statistic.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix misspell

sqle/api/cloudbeaver_wrapper/app.go, sqle/api/cloudbeaver_wrapper/service/user.go
=> Fix issue1579

sqle/api/controller/v1/statistic.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
#1629 
文档地址：http://10.186.18.11/confluence/pages/viewpage.action?pageId=86835267
修改数据源接口定义
=> fix-issue1629

sqle/api/controller/v2/workflow.go, sqle/model/workflow.go
=> Fix 1640 bug

sqle/api/controller/v1/sql_audit.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> feat:support direct sql analysis api

sqle/api/app.go, sqle/api/controller/v1/rule.go, sqle/api/controller/validator.go, sqle/api/controller/validator_test.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix issue 1653

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix-issue1653

sqle/api/controller/v1/workflow.go
=> refactor:make code more concise

sqle/api/controller/v1/rule.go, sqle/api/controller/v1/rule_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/errors/errors.go, sqle/model/rule.go, sqle/model/utils.go
#1653 
- 查看自定义规则接口
- 删除自定义规则接口
=> Fix issue1653 1

sqle/driver/mysql/audit.go, sqle/driver/mysql/mysql.go, sqle/driver/mysql/session/context.go, sqle/driver/mysql/util/parser_helper.go, sqle/server/audit.go
=> Issue 1630 2

sqle/driver/mysql/mysql.go
=> detail log

sqle/driver/mysql/audit.go, sqle/driver/mysql/mysql.go, sqle/driver/mysql/session/context.go, sqle/driver/mysql/util/parser_helper.go, sqle/server/audit.go
=> Cherry pick issue 1630

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix issue 1653 3

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/rule.go
#1653
移除rule name，添加annotation字段
=> fix issue1653 4

sqle/api/controller/v1/sql_audit.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:get request use query , not body

sqle/model/rule.go, sqle/server/audit.go, sqle/server/custom_rule_audit_ce.go, sqle/server/sqled_test.go
=> fix-issue1653 5

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/rule.go
#1653
界面优化：
区分新老规则类型。规则分类的排序方式：系统默认的分类保持在前，后增加的分类按照增加顺序展示
=> fix issue1653

sqle/api/controller/v1/instance.go, sqle/api/controller/v2/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle/issues/1676
=> chore:url and get log file api define

sqle/api/controller/v1/rule.go, sqle/model/rule.go
=> fix-issue 1653

sqle/api/controller/v1/statistic.go
#858(https://github.com/actiontech/sqle-ee/issues/858)
=> fix-issue 858

sqle/model/audit_plan.go
=> fix issue 1704

sqle/model/audit_plan_report.go, sqle/model/instance.go
=> fix issue 1707

sqle/model/rule.go
#862(https://github.com/actiontech/sqle-ee/issues/862)
=> fix issue 862

sqle/model/user.go, sqle/model/workflow.go
=> Issue 1605 1

sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/model/workflow.go
=> Issue 1605 2

spelling_dict.txt, sqle/api/controller/v1/project_permission.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/model/workflow.go
=> Issue 1605 3

sqle/driver/mysql/mysql.go, sqle/driver/v2/driver_interface.go
=> fix-issue1718

sqle/driver/mysql/mysql.go
=> fix issue 1718

sqle/cmd/scannerd/cmd/sqlfile.go, sqle/cmd/scannerd/scanners/common/file.go, sqle/cmd/scannerd/scanners/common/interface_func.go, sqle/cmd/scannerd/scanners/common/parse.go, sqle/cmd/scannerd/scanners/mybatis/mybatis.go, sqle/cmd/scannerd/scanners/parse/parse.go, sqle/cmd/scannerd/scanners/scanner.go, sqle/cmd/scannerd/scanners/sqlfile/sqlfile.go, sqle/cmd/scannerd/scanners/sqlfile/sqlfile_test.go, sqle/cmd/scannerd/scanners/sqlfile/testdata/test01.sql, sqle/server/auditplan/meta.go
=> fix issue 1690

sqle/model/workflow.go
=> Issue 1725

sqle/model/user.go, sqle/model/workflow.go
=> fix:task summary wait operation person

sqle/pkg/scanner/client.go
=> fix-issue 1690

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
(https://github.com/actiontech/sqle-ee/issues/883)
修改swagger定义
=> fix issue883

sqle/api/controller/validator.go, sqle/api/controller/validator_test.go
=> change limitation of workflow name

sqle/api/controller/validator.go, sqle/api/controller/validator_test.go
=> Issue 1731

sqle/driver/mysql/mysql.go
=> fix issue1737

sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/rule/rule_test.go
=> make rules more readable

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:swagger api def

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> fix issue1743

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/util/visitor.go
=> fix issue1743 2

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/executor/executor.go, sqle/driver/mysql/rule/rule.go
=> fix issue1743 4

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> fix issue 1743-3

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> fix issue 1743 5

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add fuzzy filter

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/workflow_list.go
=> Issue 1768

sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/server/auditplan/meta.go
file path: sqle/server/auditplan/meta.go
modify content:
InstanceType: InstanceTypeMySQL-->InstanceTypeAll,
reason: audit plan "Mybatis 扫描" support all types of datasource, just change this type into type all.
@linxiaotao
=> fix issue1764: modify meta of Metas

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/session/context.go
#1743 
建议连库查询时，确保SQL执行计划中使用的索引区分度大于阈值
=> Fix issue1743 6

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix issue1767

sqle/model/user.go, sqle/model/workflow.go
=> Issue 1775

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/model/audit_plan_report.go
=> Fix issue1767 2

sqle/api/controller/validator.go, sqle/api/controller/validator_test.go, sqle/model/workflow.go
=> Cherry pick2

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:change param validate

sqle/pkg/im/im.go
=> feat:dingtalk support execution

sqle/cmd/scannerd/cmd/slowquery.go, sqle/cmd/scannerd/scanners/slowquery/slowquery_ce.go
https://github.com/actiontech/sqle-ee/issues/931
=> Slowlog filter

spelling_dict.txt
https://github.com/actiontech/sqle-ee/issues/933
=> fix spelling

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/executor/executor.go, sqle/driver/mysql/rule/rule.go
#1743
修复在没有查询条件时，会触发规则"SQL查询条件必须能走索引"的问题
=> fix issue 1743 7

sqle/api/controller/v1/sql_audit_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/918
=> fix parameter of api definitions

sqle/api/controller/v1/sql_audit_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add api for detail info

sqle/api/controller/v1/instance.go, sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:sql manage list api define

sqle/api/controller/v1/sql_audit_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> rename api field

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:sql manage api define update

sqle/api/app.go, sqle/api/controller/v1/sql_audit_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/sql_audit_record.go, sqle/model/sql_audit_record_list.go
=> Issue 1811

spelling_dict.txt, sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix:add @Id

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:optimize api return

sqle/api/controller/v1/sql_audit_record.go
=> tags is required not nil by "dive" validation

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:add schema name field

sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
#1783
使用TEXT 类型的字段建议和原表进行分拆，与原表主键单独组成另外一个表进行存放
=> fix issue 1783 1

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> Fix issue1783 5

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> Fix issue1783 6

sqle/api/controller/v1/rule.go, sqle/api/controller/v1/rule_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/958
=> Issue ee 958

sqle/api/controller/v1/audit_plan.go, sqle/cmd/scannerd/scanners/scanner.go, sqle/model/audit_plan.go, sqle/model/audit_plan_list.go, sqle/model/audit_plan_list_test.go, sqle/server/auditplan/task.go, sqle/utils/util.go, sqle/utils/util_test.go
specific feats:
Added statistics and display of the average and maximum execution time of slow logs
Added recording and display of slow log execution users and schema
tests:
Add unit tests for newly added utils
style:
simplify the header of the slow log statistics table
@linxiaotao
=> feats: new info collection for slow log statistics

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/958
=> change field name

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> Feat index rule

sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> docs: update api documents

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:support link audit plan or ui_audit for front

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:add project name query

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:sql manage batch update api

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:add remark field

sqle/api/controller/v1/sql_audit_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/959
add:
git_http_url string required
git_user_name string not required
git_user_password string not required
=> docs: modify the SQL audit http interface

sqle/api/app.go, sqle/api/controller/v1/sql_audit_record.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v1/sql_manager_ce.go, sqle/api/controller/v1/task.go, sqle/model/sql_manage.go, sqle/model/utils.go, sqle/server/auditplan/manager.go, sqle/server/auditplan/manager_ce.go, sqle/server/auditplan/mananger_comm.go, sqle/server/auditplan/task.go
=> Sql manage 3

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/958
=> correct api definition

sqle/model/rule.go
https://github.com/actiontech/sqle-ee/issues/958
=> content field may store long string

sqle/api/app.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v1/sql_manager_ce.go, sqle/model/sql_manage.go
=> chore:ce sql manage

sqle/model/sql_manage.go, sqle/utils/util.go
=> fix:add check

sqle/model/sql_manage.go
https://github.com/actiontech/sqle-ee/pull/992
=> fix:not show all assignees

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:add person audited status

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:add update status

sqle/model/sql_manage.go, sqle/server/auditplan/manager.go, sqle/server/auditplan/mananger_comm.go
=> fix:count error and use default status

sqle/model/sql_manage.go
=> chore:support batch insert

sqle/api/controller/v1/audit_plan.go
#1767 
在报告统计信息和SQL及审核结果信息之间新增一行分隔符
=> fix issue 1767 3

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:swagger sql manage

sqle/api/app.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v1/sql_manager_ce.go, sqle/model/sql_manage.go
=> feat:sql manage export

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/session/mock_context.go
=> fix issue1783

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> exclude unnecessary case

sqle/driver/mysql/executor/executor.go
#974(https://github.com/actiontech/sqle-ee/issues/974)
query_rewrite为重写器查询重写插件生成的系统库(https://dev.mysql.com/doc/refman/8.0/en/rewriter-query-rewrite-plugin.html)
=> filter query_rewrite schema

sqle/model/sql_manage.go
=> chore:add remark field length

sqle/driver/mysql/mysql.go, sqle/driver/mysql/optimizer/index/ast.go, sqle/driver/mysql/optimizer/index/ast_test.go, sqle/driver/mysql/optimizer/index/optimizer.go, sqle/driver/mysql/optimizer/index/optimizer_test.go, sqle/pkg/optimizer/index/ast.go, sqle/pkg/optimizer/index/optimizer.go
=> optimize index suggestion

sqle/model/sql_manage.go
=> fix:error delete syntax in mysql5.7

sqle/driver/mysql/rule/rule.go
=> fix rule description

sqle/api/controller/v1/sql_audit_record.go, sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> feat:support redirect to sql_audit list

sqle/api/cloudbeaver_wrapper/controller/audit.go, sqle/api/cloudbeaver_wrapper/graph/model/models_gen.go, sqle/api/cloudbeaver_wrapper/graph/resolver/executor_gen.go, sqle/api/cloudbeaver_wrapper/graph/resolver/service.sql_gen.go, sqle/api/cloudbeaver_wrapper/graph/schema/service.auth.graphqls, sqle/api/cloudbeaver_wrapper/graph/schema/service.sql.graphqls, sqle/api/cloudbeaver_wrapper/service/gql.go, sqle/api/cloudbeaver_wrapper/service/user.go
=> Support 1884

sqle/api/controller/v1/sql_audit_record.go, sqle/model/sql_audit_record_list.go, sqle/model/sql_manage.go, sqle/model/utils.go
=> Change to list impl

sqle/api/controller/v1/sql_audit_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:change input param compatible front

spelling_dict.txt
=> fix:spell error

sqle/api/controller/v1/rule.go, sqle/model/rule.go, sqle/model/rule_list.go
=> fix filter for getting rules

sqle/api/controller/v2/audit_plan.go, sqle/api/controller/v2/sql_audit.go, sqle/api/controller/v2/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> db_type is needed when get rules by audit result

sqle/api/app.go
https://github.com/actiontech/sqle-ee/issues/1080
=> everyone can read rule knowledge

sqle/driver/common/grpc.go
=> set the limitation as a max number to avoid receive limitation

sqle/api/cloudbeaver_wrapper/service/instance.go, sqle/driver/v2/util.go
=> support tdsql

sqle/model/sql_manage.go
=> chore:compatible tdsql

sqle/model/rule.go
https://github.com/actiontech/sqle-ee/issues/1059
=> fix:error sql

go.mod, go.sum, vendor/github.com/pingcap/parser/charset/charset.go, vendor/github.com/pingcap/parser/charset/charset_extra.go, vendor/github.com/pingcap/parser/perfect_parser.go, vendor/modules.txt
=> update parser lib, for #1923 and #1924

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/utils/util.go
https://github.com/actiontech/sqle/issues/1936
=> fix:Rule error reporting

sqle/api/controller/v1/sql_audit_record.go, sqle/api/controller/v1/sql_audit_record_ce.go, sqle/api/controller/v1/task.go, sqle/model/sql_audit_record.go
https://github.com/actiontech/sqle-ee/issues/1131
=> refactor:Remove fingerprint map

sqle/driver/plugin_manager.go
=> increase timeout duration

sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/optimizer/index/optimizer.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/util/visitor.go, sqle/driver/mysql/util/visitor_test.go
#1921 
Support for explicitly declaring connection conditions using the using statement Support for declaring connection conditions using the WHERE statement
@winfredLIN
=> feat: rule dml_check_join_has_on increase coverage

sqle/api/controller/v1/audit_plan.go, sqle/model/audit_plan.go, sqle/model/utils.go
#1119(https://github.com/actiontech/sqle-ee/issues/1119)
=> add audit plan upload sql blanklist function

sqle/api/controller/v1/audit_plan.go, sqle/model/audit_plan.go, sqle/model/utils.go
=> change error name

sqle/api/controller/v1/audit_plan.go
https://github.com/actiontech/sqle-ee/issues/1119
=> fix issue 1119

sqle/api/controller/v1/sql_audit_record.go
[actiontech/sqle-ee#1065](https://github.com/actiontech/sqle/pull/1960)
=> correct response struct

sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/rule/rule_ce.go, sqle/model/rule.go
https://github.com/actiontech/sqle-ee/issues/1059
=> load default rules knowledge

sqle/model/sql_audit_record.go
https://github.com/actiontech/sqle-ee/issues/1131
=> fix:add foreign instance

sqle/server/audit.go
=> fix issue 1965

go.mod, go.sum, vendor/github.com/actiontech/java-sql-extractor/parser/util.go, vendor/github.com/actiontech/java-sql-extractor/parser/visitor.go, vendor/modules.txt
https://github.com/actiontech/sqle-ee/issues/1048
=> fix panic && null

sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/rule/rule.go
#1983 
1. filter out SQL use distinct in count
2. add unit test cases for filtering out SQL use distinct in count
=> modify: filter out SQL use distinct in count

sqle/api/app.go, sqle/api/controller/v1/company_notice.go, sqle/api/controller/v1/company_notice_ce.go, sqle/model/company_notice.go, sqle/model/utils.go
https://github.com/actiontech/sqle-ee/issues/1122
=> Issue 1122

sqle/api/app.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v1/sql_manager_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/sql_manage.go
https://github.com/actiontech/sqle-ee/issues/1149
=> feat:support get sql manage tips

sqle/api/controller/v1/project_permission.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/dms/instance.go, sqle/model/configuration.go, sqle/model/project_permission.go, sqle/model/workflow.go, sqle/notification/notification.go, sqle/pkg/im/dingding/dingding.go, sqle/pkg/im/im.go, sqle/pkg/im/im_ce.go, sqle/server/clean.go, sqle/server/ding_talk.go, sqle/server/workflow_schedule.go
#1945 
skip not set rule template instance
remove the GetWorkflowDetailById method
replace s.GetWorkflowDetailByWorkflowID with dms.GetWorkflowDetailByWorkflowID
replace workflow.id with workflow.workflow_id
=> fix: instances

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1166
=> chore:change enum file name

sqle/cmd/scannerd/cmd/common.go, sqle/cmd/scannerd/cmd/root.go, sqle/cmd/scannerd/scannerd.go
https://github.com/actiontech/sqle-ee/issues/1151
=> scannerd add version

spelling_dict.txt
=> add sprintln to spelling_dict.txt

sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
#1969 
/v1/projects/${project_name}/tasks/audits[post]
工单支持上传zip文件，接口定义
=> support audit sqls from zip file

sqle/model/audit_plan.go
https://github.com/actiontech/sqle-ee/issues/1179
=> change Fingerprint type

sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/util/parser_helper.go, sqle/driver/mysql/util/visitor.go
=> add where exists condition

sqle/driver/mysql/session/context.go, sqle/model/audit_plan.go, sqle/server/auditplan/task.go
https://github.com/actiontech/sqle-ee/issues/1182
=> Mysql慢日志智能扫描任务SQL的审核结果和SQL审核结果不一致

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1191
=> api define

sqle/api/controller/v1/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
actiontech/sqle-ee/issues/1191
=> change api define

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1191
=> chore:change name

sqle/cmd/scannerd/scanners/scanner.go
actiontech/sqle-ee/issues/1191
=> get endpoint for scanner task

sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/util/parser_helper.go
=> Fix issue1994

.github/workflows/check-pr-files.yml, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/rule/rule_ce.go, sqle/driver/v2/util.go
actiontech/sqle-ee/issues/1059
=> Issue ee 1059

sqle/api/controller/v1/audit_plan.go, sqle/model/audit_plan.go, sqle/model/audit_plan_test.go, sqle/model/sql_manage.go, sqle/server/auditplan/task.go
https://github.com/actiontech/sqle-ee/issues/1191
=> feat:sql manage add new field endpoint

sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> return sqle source of SQLs

sqle/api/controller/v1/task.go, sqle/api/controller/v2/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue 2054

sqle/api/controller/v2/workflow.go, sqle/model/workflow.go
=> fix: the workflow_record_history associated table uses workflow.id for the foreign key.

sqle/api/controller/base.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/dashboard.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/project_permission.go, sqle/api/controller/v1/sql_audit_record.go, sqle/api/controller/v1/task.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go
https://github.com/actiontech/sqle-ee/pull/1218
=> fix: get current user info is missing

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/rule.go, sqle/model/rule_list.go
https://github.com/actiontech/sqle/issues/2030
=> Fuzzy rules

sqle/api/controller/v1/project_permission.go, sqle/api/controller/v2/workflow.go
=> remove duplicate exec/audit user

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> add check explain type rule

build/sqled_with_dms.spec
[https://github.com/actiontech/dms/issues/93](关联issue)
=> the dms service specifies the running user #94

sqle/driver/mysql/rule/rule.go
=> modify message

sqle/api/controller/v2/instance.go, sqle/dms/instance.go, sqle/model/rule.go
=> fix: global template is displayed incorrectly

build/sqled_with_dms.spec
[issues](https://github.com/actiontech/dms/issues/97)
=> the rpm upgrade installation retains the original configuration file

sqle/api/app.go, sqle/api/controller/v2/sql_manage.go, sqle/api/controller/v2/sql_manager_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1229
=> Issue ee 1229 api

sqle/model/sql_manage.go
https://github.com/actiontech/sqle-ee/issues/1229
移除端点信息原有实现
=> chore:move unused field

sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/rule/rule.go
#2049 
WHERE子句禁止出现NULL值计算COLUMN_A=NULL可以写成COLUMN_A IS NULL
=> avoid column=null in where

go.mod, go.sum, sqle/api/controller/v1/dms_handle.go, sqle/api/controller/v1/dms_handle_ce.go, sqle/api/controller/v1/task.go, sqle/common/instance.go, sqle/errors/errors.go, sqle/model/workflow.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/db_service.go, vendor/github.com/actiontech/dms/pkg/dms-common/dmsobject/plugin.go, vendor/modules.txt
[关联issues](https://github.com/actiontech/dms/issues/99)
=> validate db_service data before deletion

sqle/api/controller/v1/project_permission.go
#2005 
temporary solution, project_id == "" to skip permission verification
=> fix: check permission

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> use GetSelectivityOfColumns

sqle/model/sql_manage.go
https://github.com/actiontech/sqle-ee/issues/1229
=> Revert "chore:move unused field"

spelling_dict.txt, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> Fix issue2049 1

sqle/api/controller/v1/task.go, sqle/dms/instance.go
=> fix: remove detects if instance exists

sqle/api/controller/v1/sql_audit_record.go
=> issues-2122: missing instance for task associated model

spelling_dict.txt, sqle/server/auditplan/huawei_task.go
https://github.com/actiontech/sqle-ee/issues/1254
Imitate the way Huawei Cloud processes regions and check if regions exist before creating clients
=> fix: huawei SDK panic when input a region which is not exist in regions of huawei cloud rds

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/util/visitor.go
=> check xml sql

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v2/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/audit_plan.go, sqle/model/audit_plan_test.go, sqle/model/sql_manage.go, sqle/pkg/scanner/client.go, sqle/server/auditplan/task.go
This reverts commit 15ad15aea94339567462aa02390f82639e4323d0.
https://github.com/actiontech/sqle-ee/issues/1229
=> Revert "Revert "chore:move unused field""

docker-images/sqle/start.sh
合并配置：https://github.com/actiontech/dms/issues/74
新增log配置：https://github.com/actiontech/dms/issues/95
=> update config in docker build

sqle/server/auditplan/huawei_task.go, sqle/server/auditplan/meta.go
=> modify: meta of huawei cloud auditplan

sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v2/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1271
=> Add fuzzy search by schema name feature

sqle/model/workflow.go
https://github.com/actiontech/sqle/issues/2157
=> fix: missing workflow_id when query  expired/scheduled workflows

spelling_dict.txt, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/audit_plan_test.go, sqle/api/controller/v2/audit_plan.go, sqle/model/audit_plan.go, sqle/model/utils.go, sqle/utils/util.go, sqle/utils/util_test.go
actiontech/sqle-ee/issues/1272
=> Issue ee 1272 cherry pick

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/audit_plan_test.go, sqle/api/controller/v2/audit_plan.go
#2159 
https://github.com/actiontech/sqle-ee/issues/1272
1. 修改了错误的拼写
2. 修复了单测测试内容的错误
=> ci: modify bad words

sqle/api/app.go, sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1266
=> sql analysis api define

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> check subquery

scripts/init_start.sh
=> issues-2164: SQLE3启动脚本：实际启动失败，但输出启动成功

sqle/model/utils.go
https://github.com/actiontech/sqle-ee/issues/1267
=> Add a composite index to improve the SELECT query speed

sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v1/sql_manager_ce.go, sqle/model/sql_manage.go
https://github.com/actiontech/sqle-ee/pull/1226
=> chore:community edition sql analysis

go.mod, go.sum, sqle/api/controller/v1/sql_audit.go, sqle/api/controller/v1/sql_audit_record.go, sqle/api/controller/v1/task.go, sqle/api/controller/v2/sql_audit.go, sqle/api/controller/v2/task.go, sqle/model/task.go, sqle/server/sqled_test.go, vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/mapper.go, vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/mappers.go, vendor/github.com/actiontech/mybatis-mapper-2-sql/parser.go, vendor/modules.txt
cherry pick https://github.com/actiontech/sqle/pull/2075
=> Cherry pick v3

scripts/init_start.sh
=> issues-2164: increase wait time for startup to 20 seconds

sqle/model/utils.go
=> fix compatibility issues

go.mod, go.sum, vendor/github.com/actiontech/dms/pkg/dms-common/dmsobject/db_service.go, vendor/modules.txt
https://github.com/actiontech/sqle-ee/issues/1297
更新dms依赖，以解决插件寻找dms依赖找不到的问题
=> chore: update dms dependence

sqle/model/sql_manage.go
https://github.com/actiontech/sqle-ee/issues/1266
=> remove instance

docker-images/sqle/start.sh
https://github.com/actiontech/dms/issues/127
=> enable auto_migrate by default

sqle/driver/mysql/rule/rule_list_trial.go
https://github.com/actiontech/sqle-ee/issues/1297
=> fix: enterprise trial edition compilation failed

sqle/driver/mysql/advisor.go
#2117 
修改建议描述
SQL使用了前缀模式匹配 --->  SQL使用了前模糊匹配
=> modify: description of create index suggestions

sqle/driver/mysql/advisor.go
=> cherry pick: modify: description of create index suggestions

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/util/util.go
=> use 1 instead select fields

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> check single index

go.mod, go.sum, vendor/github.com/pingcap/parser/lexer.go, vendor/github.com/pingcap/parser/perfect_parser.go, vendor/github.com/pingcap/parser/yy_parser.go, vendor/modules.txt
=> update MySQL parser

Makefile
https://github.com/actiontech/sqle-ee/issues/1339
=> feat:trial version makefile

sqle/model/sql_whitelist.go, sqle/server/audit.go, sqle/server/sqled_test.go
actiontech/sqle/issues/2105
#2105  #2023-1-29 #wanghc #修复【扫描任务没有触发白名单】
=> #2105 fix bug

docker-images/sqle/start.sh
https://github.com/actiontech/sqle/issues/2242
=> use default config.yaml for docker image

go.mod, go.sum, sqle/dms/common.go, sqle/model/user.go, sqle/model/workflow.go, sqle/notification/notification.go, sqle/notification/webhook.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/proxy.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/router.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/user.go, vendor/github.com/actiontech/dms/pkg/dms-common/conf/options.go, vendor/github.com/actiontech/dms/pkg/dms-common/register/register.go, vendor/modules.txt
#2238 
the information added are as below:
1. third-party user information.
2. current stage id.
3. data source information.
4. workflow audit task id.
5. workflow description.
6. types of SQL included.
=> feat:  webhook of workflow supports transmitting more workflow related information

build/sqled_with_dms.spec, docker-images/sqle/start.sh
https://github.com/actiontech/sqle/issues/2242
=> use std_dms.log to receive dms standard output

sqle/model/task.go
=> start line should not be null

sqle/driver/mysql/executor/executor.go
actiontech/sqle/issues/2008
actiontech/sqle-ee/issues/1212
#wanghc #修复审核系统视图bug，无法获取到视图类建表语句(mysql8问题)
=> 审核包含系统视图的DQL语句报错修复

sqle/notification/webhook.go
=> fix CurrentStep is nil issue

sqle/driver/mysql/executor/executor.go
https://github.com/actiontech/sqle-ee/issues/1351
=> database key to lower

sqle/api/controller/v1/workflow.go, sqle/api/controller/v1/workflow_ce.go
=> remove workflow template

sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v2/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1362
=> chore:swagger

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1362
=> Issue 1362 api 1

sqle/api/controller/v1/workflow.go, sqle/api/controller/v1/workflow_ce.go
=> getWorkflowTemplate interface return default template

sqle/api/controller/v1/sql_audit.go, sqle/api/controller/v2/sql_audit.go, sqle/server/audit.go
[关联issues](https://github.com/actiontech/dms/issues/164)
=> issues-164: cloudbeaver audit using associated data source rule template

sqle/dms/common.go, sqle/notification/webhook.go
=> add project name of workflow to the request of webhook

sqle/pkg/scanner/client.go
=> scanner send to dms

go.mod, go.sum, vendor/github.com/actiontech/mybatis-mapper-2-sql/parser.go, vendor/modules.txt
=> chore:add new label procedure

go.mod, go.sum, vendor/modules.txt
=> fix:remove replace label

sqle/api/controller/v2/audit_plan.go, sqle/cmd/scannerd/scanners/scanner.go, sqle/model/audit_plan.go, sqle/server/auditplan/task.go
https://github.com/actiontech/sqle-ee/issues/1381
=> Issue 1381

sqle/api/controller/v2/audit_plan.go, sqle/cmd/scannerd/scanners/scanner.go, sqle/model/audit_plan.go, sqle/server/auditplan/task.go
https://github.com/actiontech/sqle-ee/issues/1381
=> chore:use sql get slow log

sqle/notification/webhook.go
=> fix nil point

sqle/api/controller/v1/dashboard.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix: get incorrect dashboard statistics data

sqle/model/rule.go, sqle/model/utils.go, sqle/sqled.go
#1849   #2192
actiontech/sqle/issues/1849
actiontech/sqle/issues/2192
描述：
1、插件已删除的规则同步删除sqle中的公共模板中规则、项目模板中规则、知识库。
2、当插件规则参数中Key与模板参数中Key相等时，若描述或类型有变化则更新更新描述和类型
3、根据模板参数和插件参数的Key进行双向匹配，判断新增或删除规则模板中参数
=> #1849 #2192 #wanghc #插件规则变更同步至sqle规则模板中

sqle/api/controller/v1/audit_plan.go, sqle/notification/notification.go
=> Send webhook async

sqle/model/workflow_list.go
https://github.com/actiontech/sqle-ee/issues/1399
=> fix:Inconsistent parameters

sqle/api/controller/v1/sql_audit.go, sqle/api/controller/v1/sql_audit_record.go
https://github.com/actiontech/sqle/issues/2301
=> chore:skip zip file and git repository

sqle/driver/mysql/advisor.go, sqle/driver/mysql/advisor_test.go
https://github.com/actiontech/sqle/issues/2231
=> fix: panic when audit SQL which driving table in subquery

sqle/model/audit_plan.go
https://github.com/actiontech/sqle-ee/issues/1405
=> chore:maximize decimal value

sqle/api/controller/v1/sql_audit_record.go, sqle/utils/util.go
https://github.com/actiontech/sqle/issues/2310
=> chore:Skip invalid UTF-8 character set in SQL

sqle/api/controller/v1/task.go
issue：https://github.com/actiontech/sqle-ee/issues/1404
添加工单导出注释
=> #1404 #wanghc #添加工单导出注释

sqle/api/controller/v1/sql_audit_record.go, sqle/utils/util.go
=> fix:transform unknown encoding to utf8

sqle/server/auditplan/huawei_task.go
=> fix: HTML characters not escaped

sqle/model/sql_whitelist.go
issue：actiontech/sqle-ee/issues/1392
描述：白名单查询，where条件中过滤掉被删除的数据，防止cout计数数据不准确
=> 修改获取白名单行数查询过滤条件

sqle/api/app.go, sqle/api/controller/v1/sql_dev_record.go, sqle/api/controller/v1/sql_dev_record_ce.go, sqle/api/controller/v2/sql_audit.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/sql_dev_record.go, sqle/model/utils.go
https://github.com/actiontech/sqle-ee/issues/1406
=> Sql dev record

sqle/api/controller/v1/task.go
issue：actiontech/sqle-ee/issues/1404
描述：乱码问题已由前端修复，删除工单导出重复指定csv编码
=> 删除工单导出重复指定csv编码

sqle/api/app.go, sqle/api/controller/v1/sql_audit_record.go, sqle/api/controller/v1/task.go, sqle/cmd/sqled/sqled.go, sqle/config/config.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/task.go, sqle/model/task_files.go, sqle/model/utils.go, sqle/server/clean.go, sqle/server/manager.go, sqle/sqled.go, sqle/utils/file.go, sqle/utils/file_test.go, sqle/utils/util.go, sqle/utils/util_test.go
=> Support save origin file

sqle/api/controller/v1/sql_dev_record_ce.go, sqle/api/controller/v2/sql_audit.go
https://github.com/actiontech/sqle-ee/issues/1426
=> fix: offline audit cause panic

sqle/driver/plugin_manager.go
https://github.com/actiontech/sqle-ee/issues/1355
社区版代码提交在了企业版，社区版重新进行提交
=> change jar plugin start method

sqle/driver/mysql/mysql.go, sqle/log/logger.go
https://github.com/actiontech/sqle/issues/2326
增加审核规则耗时日志,帮助排查审核规则执行慢的问题
> [!TIP]
=> chore:rule execution time

sqle/model/task_files.go
#2337
1. 修改SQL语句中表名`files`->`audit_files`
2. 增加了注释
3. 修改了变量名`files`->`auditFiles`
> [!TIP]
=> fix: SQL statement error prevents obtaining expired file records

sqle/api/app.go, sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1441
添加企业微信接口定义
> [!TIP]
=> add wechat audit api interface

go.mod, go.sum, sqle/api/controller/v1/audit_plan.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/db_service.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/project.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/user.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/jwt/jwt.go, vendor/modules.txt
#2340 
打开智能扫描任务编辑页面的操作只能由【admin/项目管理员/任务创建人】执行，只有查看权限的成员不能操作
> [!TIP]
=> 智能扫描任务打开编辑页面权限调整

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v2/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/audit_plan_list.go, sqle/model/audit_plan_list_test.go, sqle/pkg/params/params.go, sqle/server/auditplan/meta.go
#2342 #2340 
- 数据库中的敏感信息加密保存
- 编辑页面用密文展示敏感信息
- 扫描列表返回字段增加创建者id
> [!TIP]
=> 智能扫描任务敏感数据，访问权限更新

sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1441
定时上线api修改接口定义
> [!TIP]
=> UpdateWorkflowScheduleV2 api add IsNotify && NotifyType

sqle/api/controller/v2/workflow.go, sqle/api/controller/v2/workflow_ce.go, sqle/model/configuration.go, sqle/model/utils.go, sqle/model/workflow.go, sqle/pkg/im/im.go, sqle/pkg/im/im_ce.go, sqle/server/manager.go, sqle/server/wechat_ce.go, sqle/server/workflow_schedule.go
https://github.com/actiontech/sqle-ee/issues/1441
新增wechatRecord表
定时上线功能新增判断是否需要发送企微通知逻辑
> [!TIP]
=> Fix issue1441 4

sqle/api/app.go, sqle/api/controller/v1/optimization.go, sqle/api/controller/v1/optimization_ce.go, sqle/api/controller/v1/sql_dev_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/errors/errors.go, sqle/model/sql_optimization.go, sqle/model/utils.go
https://github.com/actiontech/sqle-ee/issues/1439
SQL优化功能接口，model定义
> [!TIP]
=> sql optimization

sqle/driver/mysql/rollback.go, sqle/driver/mysql/rollback_test.go, sqle/driver/mysql/util/visitor.go
https://github.com/actiontech/sqle/issues/2351
> [!TIP]
=> fix:sql rollback panic

sqle/api/app.go, sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1480
更新url路径
更新swagger
> [!TIP]
=> update url && swagger

sqle/api/controller/v1/optimization.go, sqle/config/config.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue 1459

Makefile, build/sqled_with_dms.spec
actiontech/sqle-ee/issues/1482
调整打包命令，支持通过指定版本号打专业版的rpm包
> [!TIP]
=> support pack trial package

sqle/api/controller/v1/sql_audit_record.go
https://github.com/actiontech/sqle-ee/issues/1422
支持合并文件中的SQL
> [!TIP]
=> feat: support merge upload file sqls

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1480
更新swagger
> [!TIP]
=> swagger use enum && update response struct

sqle/api/app.go, sqle/api/controller/v1/optimization.go, sqle/api/controller/v1/optimization_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1422
SQL优化概览
> [!TIP]
=> Optimization overview

sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1480
枚举类型使用小写
> [!TIP]
=> Use lowercase

sqle/driver/mysql/advisor.go
=> fix:as name null pointer error

sqle/api/controller/v1/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1461
接口`/v1/projects/{project_name}/instance_tips`
入参`functional_module`新增枚举值`create_optimization`
> [!TIP]
=> 接口instance_tips文档更新

sqle/api/controller/v1/system_module.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1461
接口`/v1/system/module_status`，入参`module_name`新增枚举值：`sql_optimization`，供前端查询sql优化是否开启
> [!TIP]
=> issue-1461

sqle/server/optimization/rule/rule.go, sqle/server/optimization/rule/rule_ce.go
https://github.com/actiontech/sqle-ee/issues/1460
赋值重写规则知识库
> [!TIP]
=> #1460 #wanghc #重写知识库

sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
SQL审核以文件聚合的展示页面，增加分页参数
> [!TIP]
=> 接口复审：SQL审核以文件聚合的展示页面，增加分页

go.mod, go.sum, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/optimization.go, sqle/api/controller/v1/project_permission.go, sqle/dms/permission.go, sqle/server/optimization/rule/rule.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/user.go, vendor/modules.txt
https://github.com/actiontech/sqle-ee/issues/1461
- 数据源接口适配创建优化
- 为sql优化相关接口添加权限校验
- optimizationRecord添加字段InstanceId
> [!TIP]
=> feat:sql_optimization

sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
增加显示文件中出现error/warning/normal/notice的sql的数量统计
> [!TIP]
=> 接口复审：SQL审核以文件聚合的展示页面，增加审核结果各等级sql数量的统计

sqle/driver/mysql/rollback.go, sqle/model/utils.go
#2401
#2125 
delete update生成的回滚语句新增二进制数据处理
> [!TIP]
=> Fix issue2401

sqle/driver/mysql/rollback.go
#2401
delete update生成的回滚语句新增二进制数据处理
> [!TIP]
=> Cherry pick v2 2.2311

sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle/pull/2410
补充swagger文档
> [!TIP]
=> docs: update swagger add filter_file_id

sqle/api/app.go
无
删除没用的静态页面注册代码，对功能没有影响
> [!TIP]
=> remove useless code

sqle/driver/plugin_manager.go, sqle/model/utils.go, sqle/server/optimization/rule/rule.go, sqle/server/optimization/rule/rule_list.go
https://github.com/actiontech/sqle-ee/issues/1521
定义Oracle重写规则，并加入插件重写规则的map中
> [!TIP]
=> feat: support Oracle optimization

sqle/api/app.go, sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1532
新增获取文件上线排序方式的接口定义
/v1/task_groups/audit接口新增排序方式参数
> [!TIP]
=> Fix issue1532

sqle/model/task_files.go, sqle/server/sqled.go
1. 调整批量执行SQL的策略：一旦出现执行失败的SQL，不再执行剩余未执行的SQL。
2. 调整总结SQL文件执行状态的策略：一旦出现执行失败的SQL，文件执行状态显示为失败。
> [!TIP]
=> 调整批量执行SQL的策略

sqle/driver/plugin_manager.go
https://github.com/actiontech/sqle/issues/2253
=> 解决sqle日志膨胀问题

sqle/server/optimization/rule/rule.go, sqle/server/optimization/rule/rule_list.go
https://github.com/actiontech/sqle-ee/issues/1522
- 重新定义 DDLCheckDatabaseCollation 现复用的重写规则名称，避免复用
> [!TIP]
=> fix: split DDLCheckDatabaseCollation

sqle/api/controller/v1/task.go, sqle/api/controller/v1/task_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/errors/errors.go, sqle/model/task.go
https://github.com/actiontech/sqle-ee/issues/1532
1. 实现获取文件排序方式的接口
2. /v1/task_groups/audit接口中增加文件排序功能
> [!TIP]
=> Fix issue1532 1

sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1532
/v1/projects/{project_name}/tasks/audits 接口新增file_order_method参数
> [!TIP]
=> tasks/audits api add file_order_method param

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v1/workflow_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/task_files.go
https://github.com/actiontech/sqle-ee/issues/1539
1. 新增修改文件上线顺序的接口
2. 获取审核任务文件概览列表对`execOrder`字段进行排序
> [!TIP]
=> Fix issue1532 2

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1539
swagger中添加参数定义
> [!TIP]
=> add params in swagger

sqle/model/task_files.go
https://github.com/actiontech/sqle-ee/issues/1542
新增通过id获取auditfile函数
> [!TIP]
=> add get audit file by id func

sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1532
参数没有定义在form中
> [!TIP]
=> add params to form

sqle/driver/mysql/rollback.go
=> do not use single quotes to wrap pk data

sqle/api/controller/v1/configuration.go, sqle/model/configuration.go
https://github.com/actiontech/dms-ee/issues/256
- 系统变量相关接口 /v1/configurations/system_variables 支持控制台操作日志过期时间
> [!TIP]
=> 系统变量相关接口支持控制台操作日志过期时间

sqle/server/sqled.go
https://github.com/actiontech/sqle-ee/issues/1562
检查最后一个sql所处的batch，若执行失败，则不再执行剩下的sql文件
> [!TIP]
=> fix: check the last batch

sqle/driver/mysql/rollback.go
=> Fix issue2433 cherrypick v2

sqle/driver/mysql/rollback.go
=> Fix issue2433 cherrypick

sqle/driver/mysql/mysql.go
https://github.com/actiontech/sqle/issues/2442
文件上线支持mysql，实现ExecBatch方法
> [!TIP]
=> feat: file online support mysql

sqle/driver/mysql/executor/executor.go
#2405
mysql new connection使用utf8mb4字符集
> [!TIP]
=> mysql connection use utf8mb4

sqle/driver/plugin_adapter_v2.go, sqle/driver/plugin_manager.go
https://github.com/actiontech/sqle/issues/2348
sqle启动插件逻辑，新增记录插件pid文件，kill残留插件进程逻辑
> [!TIP]
=> feat: plugins process pid file and kill plugins process residual

sqle/driver/plugin_manager.go
https://github.com/actiontech/sqle/issues/2348
修复plugin pidfile不存在导致panic问题
> [!TIP]
=> fix: plugin pid file walk nil pointer

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/workflow_list.go
#2451
1. 获取工单接口和导出工单接口统一使用instance id
2. 工单查询语句使用instance id作为查询条件
> [!TIP]
=> Fix issue2451

go.mod, go.sum, sqle/utils/version.go, sqle/utils/version_test.go, vendor/github.com/hashicorp/go-version/CHANGELOG.md, vendor/github.com/hashicorp/go-version/LICENSE, vendor/github.com/hashicorp/go-version/README.md, vendor/github.com/hashicorp/go-version/constraint.go, vendor/github.com/hashicorp/go-version/version.go, vendor/github.com/hashicorp/go-version/version_collection.go, vendor/modules.txt
https://github.com/actiontech/sqle-ee/issues/1567
1. 引入版本解析包 
https://pkg.go.dev/github.com/hashicorp/go-version#section-readme
https://github.com/hashicorp/go-version
STAR 1.6k
被引用数量：Imported by 4,943
2. 新增工具函数，比较版本号
3. 为该函数新增单元测试
> [!TIP]
=> Issue1567：新增版本比较工具函数

sqle/api/controller/v1/sql_audit_record.go, sqle/api/controller/v1/task.go
=> convert gbk encoding

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
https://github.com/actiontech/sqle/issues/2457
=> MYSQL规则 避免对条件字段使用函数操作 和 不建议在WHERE条件中使用与过滤字段不一致的数据类型 审核sql panic报错

sqle/server/auditplan/task.go
https://github.com/actiontech/sqle-ee/issues/1592
复用代码，减少重复
> [!TIP]
=> Reduce code duplication

sqle/api/controller/v1/audit_plan_test.go, sqle/utils/util.go, sqle/utils/util_test.go
ISSUE: https://github.com/actiontech/sqle/issues/2448
PR : https://github.com/actiontech/sqle/pull/2449
1. 修改正则表达式，让正则表达式能够匹配多行
> [!TIP]
=> Cherry-Pick From 2.9999.x: Fix the issue of SQL blacklist invalidation in multiple rows of SQL

Makefile
This reverts commit 263eb773
#2468 
回退变更，因为影响到了GOCD打包，暂时做回退处理
> [!TIP]
=> Revert "make it possible to specify GOARCH when compile"

sqle/notification/notification.go, sqle/pkg/im/im.go
https://github.com/actiontech/sqle-ee/issues/1605
将通知内容中工单链接中的order更新为exec-workflow
> [!TIP]
=> fix workflow url in notification

sqle/api/controller/v1/workflow.go, sqle/model/task.go
=> updates func need use map[string]interface{}

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/user.go, sqle/model/workflow.go
https://github.com/actiontech/dms-ee/issues/312
添加接口：通过实例ID获取实例上未完成的工单数量
> [!TIP]
=> Feat overview of global db services

Makefile
https://github.com/actiontech/sqle-ee/issues/1621#issuecomment-2244283232
> [!TIP]
=> modify makefile to build arm scanner

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
#2486
新增获取工单附件接口,为了支持工单克隆功能
> [!TIP]
=> 新增获取工单附件接口

sqle/cmd/scannerd/cmd/mybatis.go, sqle/cmd/scannerd/cmd/root.go, sqle/cmd/scannerd/cmd/sqlfile.go, sqle/cmd/scannerd/scanners/common/interface_func.go, sqle/cmd/scannerd/scanners/mybatis/mybatis.go, sqle/cmd/scannerd/scanners/sql_file/sqlfile.go, sqle/pkg/scanner/client.go
=> temp:scanner refactor

sqle/api/controller/v1/instance_audit_plan.go, sqle/server/auditplan/task_type_mysql_schema_meta.go
1. 增加数据源只能绑定单个扫描任务的校验
2. 修复schema建表展示问题
> [!TIP]
=> Fix audit plan ce

sqle/model/instance_audit_plan.go, sqle/server/auditplan/meta.go, sqle/server/auditplan/task_type_mysql_schema_meta.go
扫描任务库表元数据中文名称修改
同步扫描任务时出现panic bug修复
调整mysql库表元数据获取sqls的审核结果列的表头顺序
> [!TIP]
=> Instance audit plan modify

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance_audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1660
智能扫描自定义排序的接口定义
> [!TIP]
=> Audit plan filter

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance_audit_plan.go, sqle/api/controller/v2/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/instance_audit_plan.go, sqle/server/auditplan/manager.go, sqle/server/auditplan/meta.go, sqle/server/auditplan/sql_info.go, sqle/server/auditplan/task.go, sqle/server/auditplan/task_type_default.go, sqle/server/auditplan/task_type_mysql_audit_log_ali.go, sqle/server/auditplan/task_type_mysql_processlist.go, sqle/server/auditplan/task_type_mysql_schema_meta.go, sqle/server/auditplan/task_type_mysql_slowlog_ali.go, sqle/server/auditplan/task_type_mysql_slowlog_baidu.go, sqle/server/auditplan/task_type_mysql_slowlog_huawei.go, sqle/server/auditplan/task_type_oracle_topsql.go, sqle/server/auditplan/task_type_tidb_audit_log.go, sqle/server/auditplan/task_v2.go
https://github.com/actiontech/sqle-ee/issues/1576#issuecomment-2257474194
1. 扫描任务移除固定字段schema
2. 自定义字段schema获取后作为枚举值返回
3. Meta的自定义参数字段Params调整为func类型，支持动态获取
> [!TIP]
=> Metas param enums

sqle/api/controller/v1/instance_audit_plan.go, sqle/server/auditplan/task_type_mysql_schema_meta.go
1. 返回instance id，metas筛选需要
2. 修复非MySQL的库表任务
> [!TIP]
=> Fix schema task

sqle/model/instance_audit_plan.go, sqle/model/instance_audit_plan_list.go, sqle/server/auditplan/manager.go
=> fix: get audit plan sqls  incorrect id

sqle/cmd/scannerd/cmd/mybatis.go, sqle/cmd/scannerd/cmd/root.go, sqle/cmd/scannerd/cmd/sqlfile.go, sqle/cmd/scannerd/scanners/common/interface_func.go, sqle/cmd/scannerd/scanners/mybatis/mybatis.go, sqle/cmd/scannerd/scanners/mybatis/mybatis_test.go, sqle/cmd/scannerd/scanners/sql_file/sqlfile.go, sqle/cmd/scannerd/scanners/sql_file/sqlfile_test.go, sqle/pkg/scanner/client.go
=> Scanner direct audit

sqle/api/app.go, sqle/api/controller/v1/dms_handle.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/instance_audit_plan.go, sqle/api/controller/v1/project_permission.go, sqle/dms/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/audit_plan.go, sqle/model/instance_audit_plan.go, sqle/model/instance_audit_plan_list.go, sqle/server/auditplan/manager.go, sqle/server/auditplan/task_v2.go
智能扫描任务接口重定义
删除创建时business入参
删除静态审核接口定义的参数
instance_tips添加business入参
> [!TIP]
=> Modify audit plan api define

sqle/api/app.go, sqle/api/controller/v1/instance_audit_plan.go, sqle/api/controller/v2/audit_plan.go, sqle/api/middleware/jwt.go, sqle/cmd/scannerd/cmd/root.go, sqle/cmd/scannerd/cmd/slowquery.go, sqle/cmd/scannerd/scanners/common/interface_func.go, sqle/cmd/scannerd/scanners/slowquery/slowquery_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/instance_audit_plan.go, sqle/pkg/scanner/client.go
=> Slowlog url modify

sqle/server/optimization/rule/rule_list.go, sqle/server/optimization/rule/rule_list_trial.go
https://github.com/actiontech/sqle-ee/issues/1681
使用条件编译，使专业版不显示SQL优化规则
> [!TIP]
=> Professional version should not show SQL optimization rules

sqle/api/app.go, sqle/api/controller/v1/instance_audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1660
- 接口路由 audit_plan_type 改成 audit_plan_id
- 更新接口文档
> [!TIP]
=> Update audit plan sql api

sqle/api/controller/v2/audit_plan.go, sqle/api/middleware/jwt.go, sqle/model/audit_plan.go, sqle/model/instance_audit_plan.go, sqle/model/instance_audit_plan_list.go, sqle/model/utils.go, sqle/server/auditplan/job_task_handler.go, sqle/server/auditplan/manager.go, sqle/server/auditplan/sql_info.go, sqle/server/auditplan/task.go, sqle/server/auditplan/task_type_default.go, sqle/server/auditplan/task_type_mysql_audit_log_ali.go, sqle/server/auditplan/task_type_mysql_processlist.go, sqle/server/auditplan/task_type_mysql_schema_meta.go, sqle/server/auditplan/task_type_mysql_slowlog_ali.go, sqle/server/auditplan/task_type_mysql_slowlog_baidu.go, sqle/server/auditplan/task_type_mysql_slowlog_huawei.go, sqle/server/auditplan/task_type_oracle_topsql.go, sqle/server/auditplan/task_type_tidb_audit_log.go, sqle/server/auditplan/task_v2.go, sqle/server/auditplan/task_wrap.go
https://github.com/actiontech/sqle-ee/issues/1576#issuecomment-2262433545
1. sql管控三张表重命名
2. instance name改成instance id
3. 扫描过程遇到审核报错，只打印错误日志，避免影响其他任务写入SQL
4. 扫描任务关闭后，获取task panic问题修复
> [!TIP]
=> table rename

sqle/api/controller/v1/instance_audit_plan.go, sqle/api/controller/v2/audit_plan.go, sqle/model/instance_audit_plan.go, sqle/model/instance_audit_plan_list.go, sqle/server/auditplan/task_wrap.go
补充上次采集时间更新逻辑
获取扫描任务id不正确修复
删除扫描任务报错sql修复
> [!TIP]
=> Audti plan fix and add last collection time

sqle/server/auditplan/job_task_handler.go, sqle/server/auditplan/meta.go, sqle/server/auditplan/task.go, sqle/server/auditplan/task_type_mysql_audit_log_ali.go, sqle/server/auditplan/task_type_mysql_processlist.go, sqle/server/auditplan/task_type_mysql_slowlog_ali.go, sqle/server/auditplan/task_type_mysql_slowlog_baidu.go, sqle/server/auditplan/task_type_tidb_audit_log.go, sqle/server/auditplan/task_v2.go
删除mybatis和sqlfile审核任务meta
删除慢日志审核过去时间段内抓取的SQL（分钟）参数
> [!TIP]
=> Remove unused audit plan

sqle/api/controller/v1/instance_audit_plan.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v2/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1576#issuecomment-2262433545
- 补充sql管控的业务筛选条件
> [!TIP]
=> Filter business

sqle/model/instance_audit_plan_list.go
=> fix: instance audit plan query fix

sqle/model/instance_audit_plan.go
https://github.com/actiontech/sqle/issues/2523
获取同步任务sql修改
获取info中的start time命名修改
> [!TIP]
=> fix: start time namemodify and get sync audit plan sql fix

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/rule/rule_list.go, sqle/driver/mysql/session/mock_context.go
#2473 
添加了一条MySQL审核规则，并编写了测试用例，同时添加了一个没有主键、只有自增字段的mock表
> [!TIP]
=> feat: 添加MySQL规则 "MySQL 自增字段禁止手动插值"

sqle/server/auditplan/meta.go
#2523
TBase慢日志支持展示连接信息
> [!TIP]
=> feat:support TBase slow log connect info

sqle/api/app.go, sqle/api/controller/v1/task.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/task_files.go
https://github.com/actiontech/sqle/issues/2486
工单克隆后端接口支持：
- 新增获取工单附件接口
- 补充task返回值参数（exec_mode，sql_source）
- 修复审核时save task bug
> [!TIP]
=> Workflow clone api impl

sqle/api/controller/v1/sql_audit_record.go, sqle/api/controller/v1/task.go
#2356 
1. getSQLFromFile函数不再传递"dbType"参数
2. xml解析器不再formatsql，仅返回原始sql
> [!TIP]
=> xml解析不再进行format格式化；返回原始sql字符串

sqle/api/controller/v2/sql_manage.go, sqle/model/instance_audit_plan.go, sqle/model/instance_audit_plan_list.go, sqle/model/instance_audit_plan_list_test.go
https://github.com/actiontech/sqle/issues/2527#issuecomment-2283038616
1. 新增优先级字段/接口返回
> [!TIP]
=> add columns priority

sqle/server/auditplan/task_type_oracle_topsql.go
https://github.com/actiontech/sqle/issues/2523#issuecomment-2283502903
修复oracle扫描任务获取的instance type错误
> [!TIP]
=> fix: audit plan get oracle instance type fix

sqle/api/app.go, sqle/api/controller/v1/report_push_config.go, sqle/model/base.go, sqle/model/report_push_config.go, sqle/model/utils.go, sqle/sqled.go
https://github.com/actiontech/sqle/issues/2527
1. 默认项目新增推送报告配置
2. 推送报告配置展示
3. 推送报告配置更新
> [!TIP]
=> Report push impl

sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v2/sql_manage.go
https://github.com/actiontech/sqle/issues/2527
1. sql管控新增高优先级条件筛选
> [!TIP]
=> Priority filter

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance_audit_plan.go, sqle/api/controller/v1/report_push_config.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v2/sql_manage.go, sqle/dms/common.go, sqle/model/instance_audit_plan.go, sqle/model/report_push_config.go, sqle/model/sql_manage.go, sqle/model/utils.go, sqle/pkg/params/params.go, sqle/server/auditplan/job_task_handler.go, sqle/server/auditplan/meta.go, sqle/server/auditplan/task_type_default.go, sqle/server/auditplan/task_type_mysql_audit_log_ali.go, sqle/server/auditplan/task_type_mysql_processlist.go, sqle/server/auditplan/task_type_mysql_schema_meta.go, sqle/server/auditplan/task_type_mysql_slowlog_ali.go, sqle/server/auditplan/task_type_mysql_slowlog_baidu.go, sqle/server/auditplan/task_type_mysql_slowlog_huawei.go, sqle/server/auditplan/task_type_oracle_topsql.go, sqle/server/auditplan/task_type_tidb_audit_log.go, sqle/server/auditplan/task_v2.go, sqle/server/manager.go, sqle/server/report_push.go, sqle/server/report_push_ce.go
https://github.com/actiontech/sqle/issues/2527
- 推送配置定时更新推送任务
> [!TIP]
=> Report push job

sqle/server/auditplan/task_type_default.go
https://github.com/actiontech/sqle/issues/2539
1. 修复默认参数类型错误问题
> [!TIP]
=> fix: use default audit level value

sqle/cmd/scannerd/scanners/common/file.go, sqle/cmd/scannerd/scanners/common/interface_func.go
https://github.com/actiontech/sqle-ee/issues/1747
> [!TIP]
=> Fix issue1747

sqle/api/controller/v1/instance_audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle/issues/2523#issuecomment-2295848522
实例扫描任务接口返回instance id，支持前端获取权限
> [!TIP]
=> Inst audit plan add res param

sqle/api/controller/v1/instance_audit_plan.go, sqle/api/controller/v1/sql_manage.go, sqle/model/instance_audit_plan.go, sqle/model/instance_audit_plan_list.go, sqle/model/instance_audit_plan_list_test.go, sqle/server/auditplan/job_task_handler.go, sqle/server/auditplan/task_type_default.go, sqle/server/auditplan/task_type_mysql_schema_meta.go, sqle/server/auditplan/task_type_oracle_topsql.go, sqle/server/auditplan/task_wrap.go
https://github.com/actiontech/sqle/issues/2544
扫描任务新增sql分析和手动审核功能
> [!TIP]
=> Audit plan audit analysis api impl

sqle/api/app.go, sqle/api/controller/v1/blacklist.go, sqle/api/controller/v1/sql_whitelist.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1754
1. 增加黑名单机制,匹配黑名单的SQL不会出现在SQL管控中
2. 优化白名单机制,新增匹配次数等字段
> [!TIP]
=> White black list api define

sqle/server/auditplan/task_filter_tips.go, sqle/server/auditplan/task_type_default.go, sqle/server/auditplan/task_type_mysql_audit_log_ali.go, sqle/server/auditplan/task_type_mysql_processlist.go, sqle/server/auditplan/task_type_mysql_schema_meta.go, sqle/server/auditplan/task_type_mysql_slowlog_ali.go, sqle/server/auditplan/task_type_mysql_slowlog_baidu.go, sqle/server/auditplan/task_type_mysql_slowlog_huawei.go, sqle/server/auditplan/task_type_oracle_topsql.go, sqle/server/auditplan/task_type_tidb_audit_log.go
https://github.com/actiontech/sqle/issues/2550
1. 智能扫描SQL详情增加高优先级参数的筛选和展示
2. 所有任务SQL详情增加通用参数（sql/rule）筛选
3. 所有任务增加通用的高优先级配置（审核级别）
> [!TIP]
=> Audit plan sql priority

sqle/server/auditplan/task_type_default.go, sqle/server/auditplan/task_type_mysql_schema_meta.go, sqle/server/auditplan/task_type_oracle_topsql.go
https://github.com/actiontech/sqle/issues/2550
1. 智能扫描SQL详情增加高优先级参数的筛选和展示
2. 所有任务SQL详情增加通用参数（sql/rule）筛选
3. 所有任务增加通用的高优先级配置（审核级别）
> [!TIP]
=> Audit plan sql priority dev1

sqle/server/auditplan/task_type_mysql_audit_log_ali.go, sqle/server/auditplan/task_type_mysql_slowlog_ali.go, sqle/server/auditplan/task_type_mysql_slowlog_baidu.go, sqle/server/auditplan/task_type_mysql_slowlog_huawei.go
https://github.com/actiontech/sqle/issues/2523#issuecomment-2295788919
智能扫描rds慢日志参数补充默认值
> [!TIP]
=> add: audit plan rds slowlog add param deafult value

sqle/api/controller/v1/report_push_config.go, sqle/api/controller/v1/sql_manage.go, sqle/model/report_push_config.go, sqle/model/utils.go, sqle/notification/notification.go, sqle/sqled.go
https://github.com/actiontech/sqle-ee/issues/1768
1. 修改更新推送报告逻辑（移除仅启停操作时不允许其他参数变更）
3. 工单发出推送消息后更新推送配置最新推送时间
4.  新增删除推送报告配置方法
> [!TIP]
=> Update last push time

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/blacklist.go, sqle/api/controller/v1/sql_whitelist.go, sqle/api/controller/v2/audit_plan.go, sqle/model/audit_plan.go, sqle/model/instance_audit_plan.go, sqle/model/sql_whitelist.go, sqle/server/audit.go, sqle/server/auditplan/task_wrap.go, sqle/server/auditplan/task_wrap_test.go, sqle/server/sqled_test.go
https://github.com/actiontech/sqle-ee/issues/1754
> [!TIP]
=> 新增黑名单,优化白名单

sqle/api/controller/v1/instance_audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle/issues/2523#issuecomment-2306472898
修改实例扫描任务列表instance_id返回值类型：uint64 -> string
> [!TIP]
=> Fix audit plan list instance  id loss of precision

sqle/model/audit_plan.go, sqle/model/task.go, sqle/server/auditplan/task_wrap.go
https://github.com/actiontech/sqle-ee/issues/1773
get host from task struct
> [!TIP]
=> chore:get host from task struct

sqle/api/controller/v1/pipeline.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
1. 定义了流水线相关页面需要的HTTP API接口
2. 生成接口文档
> [!TIP]
=> api definition: HTTP API interfaces required for pipeline related pages

sqle/api/controller/v1/pipeline.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
1. 将id类型调整为uint
2. 获取单个流水线详情的响应体，增加了Data层级
3. 创建流水线增加了InstanceType，用于自动匹配审核模板
4. 增加对接说明字段
=> api definition: adjust api definition

sqle/api/controller/v1/pipeline.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> api definition: create pipeline returns pipeline id

sqle/api/controller/v1/blacklist.go, sqle/api/controller/v1/sql_whitelist.go
https://github.com/actiontech/sqle-ee/issues/1785
当用户编辑黑/白名单的匹配类型或匹配内容,该条记录的匹配次数和匹配时间将会被重置
> [!TIP]
=> 当用户编辑黑/白名单的匹配类型或匹配内容,该条记录的匹配次数和匹配时间将会被重置

sqle/model/instance_audit_plan.go
https://github.com/actiontech/sqle/issues/2561
修复删除扫描任务报错
> [!TIP]
=> fix: fix delete audit plan

sqle/common/instance.go, sqle/model/pipline.go, sqle/server/pipeline/pipeline.go
1. 当删除数据源时，会检查流水线节点是否有关联该数据源，若关联则无法删除
2. 优化了流水线节点的表，用instance id 替代instance name
3. 在删除流水线的时候，使用project id进行筛选
> [!TIP]
=> optimize pipeline related bussiness logic

Makefile
添加makfile命令
作用：将c文件同步到vendor文件夹中
> [!TIP]
=> add modvendor command

sqle/api/controller/v1/instance_audit_plan.go, sqle/api/controller/v1/sql_manager_ce.go
https://github.com/actiontech/sqle/issues/2572#issue-2496307785
修改扫描任务获取审核有问题的sql数的方法名
> [!TIP]
=> rename UnsolvedSQLCount function name

scripts/functions.sh, scripts/init_config.sh, scripts/init_start.sh, scripts/stop_sqle.sh
暂无
1. 增加了init_config.sh用于引导用户交互式配置插件基础配置
> [!TIP]
=> launch sqle: scripts for automatically configure plugin environment

sqle/api/controller/v2/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/instance_audit_plan.go, sqle/model/instance_audit_plan_list.go, sqle/model/instance_audit_plan_list_test.go, sqle/server/auditplan/job_task_handler.go
https://github.com/actiontech/sqle/issues/2572#issuecomment-2330712191
1、优化扫描任务sql审核的逻辑
2、sql管控新增返回接口字段，标记审核中的sql
> [!TIP]
=> Audit plan sql audit optimize

sqle/api/controller/v1/instance_audit_plan.go, sqle/driver/v2/driver_grpc_server.go, sqle/model/base.go, sqle/model/instance_audit_plan_list.go, sqle/model/rule.go, sqle/model/task.go, sqle/pkg/i18nPkg/i18nStr.go, sqle/server/auditplan/manager.go, sqle/server/auditplan/task_type_default.go, sqle/server/auditplan/task_type_mysql_schema_meta.go, sqle/server/auditplan/task_type_oracle_topsql.go, sqle/server/auditplan/task_v2.go
https://github.com/actiontech/sqle/issues/2594
https://github.com/actiontech/sqle/issues/2596 
https://github.com/actiontech/sqle/issues/2595
修复国际化引入的问题
> [!TIP]
=> Fix i18n problems ce

sqle/api/controller/v1/pipeline.go, sqle/server/pipeline/pipeline.go
1. 在生成pipeline node的命令的时候 增加参数项目名称
2. 优化了离线模式下，生成的命令，离线模式下不再增加数据源名称
> [!TIP]
=> pipelione: add project name as a part of command

sqle/cmd/scannerd/command/base.go
https://github.com/actiontech/sqle/issues/2595
将scannerd命令中对必要参数和非必要参数提示的内容改为英文
> [!TIP]
=> i18n: change the prompt for the scanner command to English

sqle/server/audit.go
https://github.com/actiontech/sqle-ee/issues/1638
1. 当白名单过滤后，没有需要审核的sql时，跳过审核阶段
> [!TIP]
=> modify: when there is no sql, skip audit.

sqle/api/controller/v2/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
#2616 
修改错误的endpoints数据类型定义,由字符串修改为数组
> [!TIP]
=> chore:support endpoints field

sqle/api/controller/v1/sql_version_ce.go
=> fix: add ce file add !enterprise tag

sqle/api/controller/v1/sql_version.go, sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/sql_version.go
1. 接口参数类型变更：sql_version_id from string to *uint
2. 数据库名称变更：sql_versions.desc to sql_versions.description (due to desc is one of the reserved word of mysql)
3. 接口参数新增：WorkflowDetailWithInstance.workflow_sequence 
=> api and model definition 

sqle/api/app.go, sqle/api/controller/v1/sql_version.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/sql_version.go
批量关联工单到版本 接口定义调整
版本详情接口新增工单发布时间，工单发布状态返回字段
sql版本model新增字段，新增工单发布时间，工单发布状态字段
> [!TIP]
=> Sql version manage api 

sqle/model/pipline.go, sqle/server/pipeline/pipeline.go
1. 将pipeline service层的db操作移动到model层
> [!TIP]
=> refactor: move database operations to the model layer

sqle/api/controller/v2/workflow.go, sqle/model/workflow.go, sqle/server/sqlversion/sql_version_ce.go
创建工单接口，增加创建时，将工单和SQL版本进行关联
> [!TIP]
=> feat: create and associate workflow to the first stage of the SQL version.

sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
1. 更新swagger文档，增加query参数filter_sql_version_id 
> [!TIP]
=> api definition: update swagger add filter_sql_version_id as query param

sqle/api/controller/v2/workflow.go, sqle/model/workflow.go
1. 修改创建工单函数，增加stage id作为入参，当指定了stage id，工单会绑定到指定的sql 版本的阶段，若不指定，则默认绑定到sql 版本的第一阶段
2. 该方法的修改用于后续批量发布功能
> [!TIP]
=> modify: create workflow support specify the bound stage

sqle/model/workflow_list.go
=> fix: do not display the same version repeatedly

sqle/model/sql_version.go, sqle/model/workflow.go
1. 初始化绑定到SQL版本阶段的工单状态
> [!TIP]
assign in @iwanghc
=> modify: init stage of workflow in sql version stage

sqle/api/controller/v2/workflow.go, sqle/model/sql_version.go, sqle/model/sql_version_ce.go, sqle/model/workflow.go, sqle/server/workflow_schedule.go
版本工单批量上线ce代码修改
修改上线执行代码，允许传入chan以获取上线结果
上线时更新版本管理中workflow的上线时间
迁移版本关联model方法到ee
> [!TIP]
=> Sql version manage

go.mod, go.sum, sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/instance_audit_plan.go, sqle/api/controller/v1/project_permission.go, sqle/api/controller/v1/sql_audit.go, sqle/api/controller/v1/sql_audit_record.go, sqle/api/controller/v1/task.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/audit_plan.go, sqle/api/controller/v2/sql_audit.go, sqle/api/controller/v2/workflow.go, sqle/api/middleware/permission.go, sqle/dms/permission.go, sqle/server/workflow_schedule.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/user.go, vendor/modules.txt
https://github.com/actiontech/sqle/issues/2619
assign in @winfredLIN
link https://github.com/actiontech/dms/pull/305
新增全局管理,全局浏览权限
> [!TIP]
=> Sqle ce 2619

sqle/api/app.go, sqle/api/controller/v1/sql_version.go, sqle/api/controller/v1/sql_version_ce.go, sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1807#issuecomment-2381112995
1. 取消使用retry接口，复用更新工单接口重试工单
2. 原因：重试工单调用流程和驳回后更新工单一致
3. 在更新工单接口，增加放行工单状态为执行失败的工单
> [!TIP]
=> feat: support retry workflow after executing failed

sqle/api/controller/v1/workflow.go, sqle/model/workflow_list.go
工单列表的版本信息，已删除的版本过滤掉
没有版本不返回值该字段
> [!TIP]
=> add: workflow list query sql add deleted at param

sqle/api/controller/v2/workflow.go, sqle/model/sql_version_ce.go
https://github.com/actiontech/sqle-ee/issues/1807#issuecomment-2401771413
link：https://github.com/actiontech/sqle-ee/pull/1877/files
1. 增加查询工单对应的sqlversion，
2. 如果没有就不返回工单的sql版本，前端也不显示
3. 如果有，前端就会显示该版本名称
> [!TIP]
=> fix: the SQL version is not displayed in the workflow detail

sqle/api/controller/v1/sql_version.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
link https://github.com/actiontech/sqle-ee/pull/1881
https://github.com/actiontech/sqle-ee/issues/1807#issuecomment-2404067275
1. sql版本列表增加可删除和可锁定字段
2. 当sql版本没有绑定任何工单时，可删除，若绑定任意工单则不可删除
3. 当sql版本的所有工单处于执行成功或关闭状态时，可锁定。若存在任意工单不处于上述两种状态，则不可锁定。
> [!TIP]
=> api definition: add deletable and lockable to mark if sql version can be delete and lock

sqle/api/controller/v2/workflow.go, sqle/model/sql_version_ce.go, sqle/model/workflow.go, sqle/server/workflow_schedule.go
工单关闭时，版本中的工单状态更新为不需要发布状态
model更新方法修改，适配状态修改
> [!TIP]
=> chore：cancel workflow modify sql version not released

sqle/api/controller/v1/rule.go
https://github.com/actiontech/sqle/issues/2659
修复导出规则模板时规则信息错误
> [!TIP]
assign in @taolx0
=> Fix export rule template

sqle/server/workflow_schedule.go
修复批量发布时异常中断：
工单结束的状态的channel，排除等待执行这个中间状态
> [!TIP]
=> fix: workflow over status  chan exclude wait for execution status

sqle/model/audit_plan.go
https://github.com/actiontech/sqle-ee/issues/1867
修复数据库大小写敏感的排序规则导致sqle启动失败
> [!TIP]
=> 修复数据库大小写敏感的排序规则导致sqle启动失败

sqle/notification/notification.go
https://github.com/actiontech/sqle/issues/2663
修复config值为nil时的panic报错
> [!TIP]
=> fix:config panic error

sqle/api/controller/v1/rule.go
https://github.com/actiontech/sqle/issues/2580#issuecomment-2406997208
兼容wps软件对csv文件格式的转换
> [!TIP]
=> fix:compatible wps software

sqle/driver/mysql/rule/ai/rule_00134.go, sqle/driver/mysql/rule/ai/rule_00140.go, sqle/driver/mysql/rule/ai/util/util.go, sqle/driver/mysql/rule_00134_test.go, sqle/driver/mysql/rule_00140_test.go
AI生成MySQL规则SQLE00134、SQLE00140
=> SQLE00134&SQLE00140

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/configuration.go, sqle/server/clean.go
https://github.com/actiontech/sqle/issues/2667#issuecomment-2413166180
1. 删除过期工单自动清理的定时任务
2. 调整全局配置的接口定义，删除已完成的工单自动过期时间参数
3. CB工作台操作过期时间默认值放大2160h（3个月）
> [!TIP]
=> Remove clean workflow job

sqle/api/app.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v1/sql_manager_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
link https://github.com/actiontech/sqle-ee/pull/1904
1. 接口定义：全局SQL管控列表，用于实现tab页：待处理SQL
> [!TIP]
=> api definition: global sql manage list

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
1. 获取全局工单的接口定义，支持通过优先级、数据源和项目过滤
> [!TIP]
=> api definition: get workflow globally, add filter and response

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
1. 接口定义：获取全局工单接口，增加通过多个工单状态进行筛选
2. 由于全局工单只显示，没有成功上线的工单，因此需要筛选多个工单状态。
=> api definition: add status list to filter workflow

docker-images/sqle/docker-compose.yaml
https://github.com/actiontech/sqle/issues/2686
更新docker-compose使用的cb镜像
> [!TIP]
=> use actiontech cloudbeaver image

sqle/api/controller/v1/sql_audit.go, sqle/api/controller/v1/sql_audit_record.go, sqle/api/controller/v1/task.go, sqle/api/controller/v2/sql_audit.go, sqle/model/sql_audit_record.go, sqle/server/audit.go, sqle/server/sqled.go, sqle/server/workflow_schedule.go
https://github.com/actiontech/sqle-ee/issues/1775
> [!TIP]
=> fix: 修复白名单对快捷审核下离线审核不起作用

sqle/driver/mysql/executor/executor.go, sqle/driver/mysql/rule/ai/experience.md, sqle/driver/mysql/rule/ai/rule_00039.go, sqle/driver/mysql/rule/ai/rule_00091.go, sqle/driver/mysql/rule/ai/rule_00096.go, sqle/driver/mysql/rule/ai/rule_00112.go, sqle/driver/mysql/rule/ai/rule_00122.go, sqle/driver/mysql/rule/ai/rule_00176.go, sqle/driver/mysql/rule/ai/rule_00180.go, sqle/driver/mysql/rule/ai/rule_00218.go, sqle/driver/mysql/rule/ai/util/extractor.go, sqle/driver/mysql/rule/ai/util/util.go, sqle/driver/mysql/rule_00112_test.go, sqle/driver/mysql/rule_00122_test.go, sqle/driver/mysql/rule_00180_test.go
=> Sqle00180&00122

sqle/api/controller/v1/workflow.go, sqle/utils/util.go
1. 将oadProjectsByWorkflows函数拆分，复用其中loadProjectsByProjectIds的逻辑
2. 提供将string slice做交集的方法
> [!TIP]
=> modify: split functions and provide tools and methods

sqle/model/workflow_list.go
1. 修复因为修改变量名，但SQL中没有修改完全，导致SQL执行失败的问题
> [!TIP]
- [ x ] 我已完成自测
- [ x ] 我已在关联的issue里补充了实现方案
- [ x ] 我已在关联的issue里补充了测试影响面
- [ x ] 我已确认了变更的兼容性，如果不兼容则在issue里标记 `not_compatible`
- [ x ] 我已确认了是否要更新文档，如果要更新则在issue里标记 `need_update_doc`
=> fix: wrong sql missing “s”

sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v1/sql_manager_ce.go, sqle/api/controller/v1/system_module.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle/issues/2701
1. 增加全局待关注清单，工单统计数量接口（ce
工单统计数量接口，对应前端两个tab页面，前端分别根据不同页面的筛选项查询，社区版，统计数据根据前端筛选变化。
3. 增加全局待关注清单，SQL管控统计数量接口
SQL管控统计数量接口，企业版，统计数据根据前端筛选变化。
4. 增加系统模块红点接口，、
红点接口，标记某个模块是否需要展示红点
> [!TIP]
=> api definition: three api for global todo list

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/workflow_list.go
https://github.com/actiontech/sqle/issues/2701
test1 测试变更接口
https://github.com/actiontech/sqle/issues/2701#issuecomment-2428462170
test2 测试新增接口
https://github.com/actiontech/sqle/issues/2701#issuecomment-2428472932
1. 新增统计全局待处理清单页面的统计数字接口的实现
2. 统一管理全局待处理清单的权限处理
3. 统一管理了全局待处理清单中，工单和SQL管控过滤逻辑
4. 根据之前的修改建议，进行了一些其他优化
> [!TIP]
=> implement of two statistic http api，and optimize related api

sqle/server/auditplan/job_task_handler.go
test: https://github.com/actiontech/sqle/issues/2701#issuecomment-2434590491
https://github.com/actiontech/sqle/issues/2701
1. 提取可复用函数，根据SQL和对应的智能扫描任务，判断SQL是否是高优先级，及其原因
> [!TIP]
=> modify: extract GetSingleSQLPriorityWithReasons for reusing

sqle/api/controller/v2/workflow.go
https://github.com/actiontech/sqle/issues/2704
取消创建工单时，审核结果规则等级高于审批流程中预设的等级会创建失败的限制（需求需要允许创建这样的工单）。
> [!TIP]
=> del CheckWorkflowCanCommit when create workflow

sqle/api/app.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle/issues/2701
1. 将全局工单、全局SQL管控以及对应的统计数量接口移动到dashboard路由组下
> [!TIP]
=> api definition: move 4 api to dashboard router group

sqle/api/controller/v1/statistic.go
https://github.com/actiontech/sqle/issues/2658
当某个用户被删除后，概览页面的工单中的用户会显示`username[x]`
> [!TIP]
=> fix: 删除用户后,项目概览页面报错

sqle/server/auditplan/task_type_mysql_processlist.go, sqle/server/auditplan/task_type_mysql_schema_meta.go, sqle/server/auditplan/task_type_oracle_topsql.go, sqle/server/pipeline/pipeline.go
https://github.com/actiontech/sqle/issues/2479
对于`dms.GetInstancesById`的返回值需要对exist进行校验后，再调用instance. 保证不出现panic。
> [!TIP]
=> fix: panic when instance is deleted

sqle/driver/v2/proto/driver_v2.proto
https://github.com/actiontech/sqle/issues/2595
插件接口proto文件国际化字段加注释
> [!TIP]
=> comments for i18n fields

sqle/cmd/scannerd/command/base.go, sqle/cmd/scannerd/command/command.go
https://github.com/actiontech/sqle/issues/2718
TDSQL支持连接信息
> [!TIP]
=> feat:TDSQL support link cmd

sqle/model/configuration.go
https://github.com/actiontech/sqle-ee/issues/1828
- 存在`BeforeSave` hook的时候，在Updates前需要把数据查询出来并且实例化。
> [!TIP]
=> fix: 修复对接飞书审批失败

sqle/api/controller/v1/instance_audit_plan.go, sqle/server/auditplan/meta.go
https://github.com/actiontech/sqle/issues/2646
扫描任务详情页，自定义扫描任务返回连接信息。
> [!TIP]
assign in @taolx0
=> fix: 自定义扫描任务TOKEN没有展示到页面

sqle/server/auditplan/task_type_default.go
https://github.com/actiontech/sqle-ee/issues/1951#issuecomment-2453987046
1. 智能扫描sql时间类型字段增加标识
> [!TIP]
assign in @winfredLIN 
link https://github.com/actiontech/sqle-ee/pull/1955
=> feat: type tag provides time format time

sqle/api/controller/v1/database_compare.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/1949#issuecomment-2456707237
数据库结构对比，获取变更sql与对比ddl语句接口定义修改：新增记录审核报错的字段，记录错误信息，不阻塞sql语句的正常返回。
> [!TIP]
=> Database comparison api

sqle/api/controller/v1/backup.go, sqle/api/controller/v2/task.go, sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
1. 接口调整：创建回滚工单使用独立接口
2. 接口调整：查看SQL列表，如果SQL有对应回滚工单，会返回对应的回滚工单id，以实现快捷跳转
> [!TIP]
=> 1956 issue

sqle/api/controller/v1/sql_audit_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle/issues/2742
1. 创建快捷审核支持指定规则模版名
> [!TIP]
=> 创建快捷审核支持指定规则模版名

sqle/api/controller/v1/task.go, sqle/model/task.go, sqle/server/backup_ce.go
测试：https://github.com/actiontech/sqle-ee/issues/1956#issuecomment-2473043720
1. 审核时可以设置开启备份
2. 仅支持MySQL，不支持其他数据源
3. 仅支持SQL模式，不支持文件模式
> [!TIP]
=> feat: enable backup when audit

sqle/api/controller/v1/backup.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
1. 新增字段origin task id，用于前端筛选数据源
> [!TIP]
=> api definition: add origin task id to filter instance

sqle/api/controller/v1/rule.go, sqle/api/controller/v1/sql_audit_record.go, sqle/model/task.go, sqle/server/sqled.go
https://github.com/actiontech/sqle/issues/2742
快捷审核支持切换审核规则模版
> [!TIP]
assign in @iwanghc
=> support quick audit based on rule template name

sqle/api/controller/v2/task.go, sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
1. rollback sql to rollback sqls
2. associated workflow add name in it
3. add associated workflow in returns of workflow resp
> [!TIP]
=> api definition: modify audit task resp and workflow resp

sqle/api/controller/v1/backup.go, sqle/api/controller/v2/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
1. 在关联的回滚工单中增加工单的状态
2. origin 改为 original
> [!TIP]
=> api definition: add status to associated rollback workflow

sqle/api/controller/v1/backup.go, sqle/api/controller/v1/task.go, sqle/api/controller/v2/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/driver/mysql/mysql.go, sqle/model/backup_task.go, sqle/model/backup_task_ce.go, sqle/model/task.go, sqle/server/audit.go, sqle/server/backup.go, sqle/server/backup_ce.go, sqle/server/sqled.go
切换为开发分支
link https://github.com/actiontech/sqle-ee/pull/1999
测试 https://github.com/actiontech/sqle-ee/issues/1956#issuecomment-2477842021
按序提交，需要在以下PR合并后，再复审。有一部分commit在下面的PR中。
https://github.com/actiontech/sqle/pull/2756
https://github.com/actiontech/sqle-ee/pull/1978
1. 支持工单在开启备份后，在SQL执行之前备份
> [!TIP]
=> feat: backup for sqls

sqle/server/auditplan/metrics.go, sqle/server/auditplan/task_type_oracle_topsql.go
https://github.com/actiontech/sqle/issues/2774
oracle top sql扫描任务采集sql以及合并sql时，使用定义Metric类型来获取与存储指标信息。
> [!TIP]
=> fix：oracle top sql audit plan metric

sqle/api/app.go, sqle/api/controller/v1/backup.go, sqle/api/controller/v1/backup_ce.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/model/task.go, sqle/model/workflow.go
assigin in @ColdWaterLW 
1. 实现获取回滚SQL列表，以创建回滚工单
2. 实现创建回滚工单
3. 修改重试工单，允许更多状态进行回滚
> [!TIP]
=> feat: support create rollback workflow

sqle/api/controller/v1/instance_audit_plan.go, sqle/model/utils.go
https://github.com/actiontech/sqle-ee/issues/1824
支持批量save切片
> [!TIP]
=> feat:support batch save array or slice

sqle/driver/mysql/rule/rule_list.go, sqle/model/utils.go
https://github.com/actiontech/sqle-ee/issues/2012
- rollback: https://github.com/actiontech/sqle/pull/2782
- 调低影响数据源性能的规则，让他不初始化在默认模版中
> [!TIP]
=> fix: rollback forbiddenRules and change rule level

sqle/api/app.go, sqle/api/controller/v1/backup.go, sqle/api/controller/v1/backup_ce.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/task.go, sqle/dms/instance.go, sqle/model/instance.go, sqle/model/task.go, sqle/server/backup_ce.go
1. 支持更新备份策略
2. 支持提示数据源开启备份但工单未开启
> [!TIP]
=> feat: support modify backup strategy

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
https://github.com/actiontech/sqle/issues/2784
1. 修复规则：列建议添加注释，未触发的问题
> [!TIP]
=> fix: rule check column without comment not triggered

sqle/api/controller/v1/backup.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/system_module.go, sqle/api/controller/v1/task.go, sqle/api/controller/v2/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/server/support_checker.go
https://github.com/actiontech/sqle-ee/issues/2028
1. 新增三个接口定义
2. 系统模块增加备份，用于检查是否数据源可以开启备份
3. 增加工单级别修改备份最高行数
4. 增加tips，提示用户数据源支持哪些备份方式
> [!TIP]
=> api definition: tips, backup max rows, etc.

sqle/api/controller/v2/task.go, sqle/server/backup.go
link https://github.com/actiontech/sqle-ee/pull/2041
test https://github.com/actiontech/sqle-ee/issues/2028#issuecomment-2519451494
1. sql列表以及回滚sql列表增加sql备份的状态和结果信息
> [!TIP]
=> feat: get backup status and result

sqle/api/controller/v1/instance.go, sqle/server/backup_ce.go
test https://github.com/actiontech/sqle-ee/issues/2028#issuecomment-2519466290
https://github.com/actiontech/sqle-ee/issues/2028
1. tips接口增加提示数据源支持的备份类型
> [!TIP]
=> feat: support show supported backup strategy tip for db service

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rollback.go, sqle/server/backup.go, sqle/server/backup_ce.go, sqle/server/sqled.go
https://github.com/actiontech/sqle-ee/issues/2028
1. 兼容支持生成回滚语句的插件进行备份
> [!TIP]
=> modify: backup compatible with other plugins

sqle/api/app.go, sqle/api/controller/v1/configuration.go, sqle/api/controller/v1/configuration_ce.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v1/sql_manager_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/2035
对接coding平台接口定义
> [!TIP]
=> feat: 对接coding平台接口定义

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/configuration.go, sqle/server/clean.go
https://github.com/actiontech/sqle/issues/2667#issuecomment-2522645442
cherry pick
移除自动销毁工单（目前没有使用场景）
> [!TIP]
=> Remove clean workflow job 04

sqle/api/controller/v1/configuration.go, sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/configuration.go
https://github.com/actiontech/sqle-ee/issues/2035
- 修改测试coding的url, priority枚举
> [!TIP]
=> fix: update test coding url coding priority

sqle/driver/mysql/util/util.go, sqle/driver/mysql/util/util_test.go, sqle/pkg/driver/impl.go, sqle/server/auditplan/huawei_task.go, sqle/server/auditplan/task.go, sqle/server/auditplan/task_test.go
#2603
新增一个函数处理panic情况。所有计算fingerprint的地方都使用这个函数
> [!TIP]
skip review
=> Fix issue 2603

sqle/api/app.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v1/sql_manager_ce.go, sqle/api/controller/v2/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> feat: coding opt

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/instance_audit_plan.go
https://github.com/actiontech/sqle-ee/pull/2062
- rename is_coding_notification_enabled to is_coding_enabled
> [!TIP]
skip review
=> fix: rename and add status const for sqlmanagerecordprocess

sqle/utils/util.go, sqle/utils/util_test.go
https://github.com/actiontech/sqle-ee/issues/1987
1. 修复当两个入参切片都是长度0的时候panic的问题
2. 增加单元测试
> [!TIP]
=> fix: panic when input slice are all zero length

sqle/api/controller/v1/sql_rewriting.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/2037
设计原型发生变更，本次跟进调整：
1. 添加重写后的业务含义
> [!TIP]
=> sql rewriting: add RewrittenSQLBusinessDesc

sqle/api/controller/v1/sql_whitelist.go
https://github.com/actiontech/sqle-ee/issues/2084
审核SQL例外关键字检索失效修复
> [!TIP]
=> fix: fix audit whitelist fail

sqle/model/instance_audit_plan_list.go, sqle/model/instance_audit_plan_list_test.go, sqle/server/auditplan/task_type_default.go, sqle/server/auditplan/task_type_mysql_schema_meta.go, sqle/server/auditplan/task_type_oracle_topsql.go
https://github.com/actiontech/sqle/issues/2814
新增审核中状态标识扫描任务采集待审核的sql
> [!TIP]
=> fix: add audit status for sqls, fix unmarshal error

sqle/api/controller/v1/sql_rewriting.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/2037
设计原型发生变更，本次跟进调整：
1. 添加sql的执行逻辑描述
> [!TIP]
=> sql rewriting: add sql logic desc in response

sqle/api/app.go
https://github.com/actiontech/sqle-ee/issues/1938
获取黑名单接口权限修改为项目内成员可查看
> [!TIP]
=> 获取黑名单接口权限修改为项目内成员可查看

Makefile
actiontech/sqle-ee/issues/2106
去掉git_version变量前面的空格，因为空格导致前端展示有误
> [!TIP]
=> remove leading space from line

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance_audit_plan.go
https://github.com/actiontech/sqle-ee/issues/2099
不传递得自定义参数值将不会做更新操作（解决自定义参数中密码类型被置空的问题）
> [!TIP]
=> partially audit plan params

build/sqled.spec, build/sqled_with_dms.spec, scripts/functions.sh, sqle/driver/plugin_manager.go
https://github.com/actiontech/sqle-ee/issues/2116
- rpm安装包中集成java
> [!TIP]
=> SQLE安装包中集成Java

build/sqled.spec
https://github.com/actiontech/sqle-ee/issues/2116
- 创建空的jdk目录用于和gocd 社区版打包的解耦合
> [!TIP]
=> fix: create jdk dir and update sqled.spec

sqle/api/app.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v1/sql_manager_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/2134
- 执行计划图表接口定义
> [!TIP]
=> feat: sql analysis chart api definition

sqle/log/logger.go, sqle/sqled.go
- https://github.com/actiontech/sqle/issues/2797
- 修复无法开启debug日志问题
> [!TIP]
=> fix: 无法开启DEBUG日志

sqle/api/controller/v1/project_permission.go, sqle/api/controller/v1/task.go, sqle/log/logger.go, sqle/model/project_permission.go, sqle/model/workflow.go, sqle/server/workflow_schedule.go
https://github.com/actiontech/sqle-ee/issues/2154
1. 修复允许审批工单用户查看工单任务失败
2. 修复gorm日志无法开启问题
> [!TIP]
=> Fix workflow permission

sqle/api/controller/v1/database_compare.go, sqle/api/controller/v2/sql_audit.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle/issues/2884
新增规则执行报错信息：
1. 数据库结构对比
2. 直接审核接口（cb sql审核使用）
> [!TIP]
=> Fix missing return rule error

sqle/cmd/scannerd/scanners/supervisor/supervisor.go
https://github.com/actiontech/sqle/issues/2868
单测报错修复
补充error 为 nil判断
> [!TIP]
link https://github.com/actiontech/sqle/pull/2885
=> fix: scannerd go test, add error nil judgment

sqle/api/controller/v2/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/2164
- 增加v2 cost字段
> [!TIP]
=> fix: add v2 cost

sqle/api/controller/v2/audit_plan.go, sqle/model/instance_audit_plan.go, sqle/server/auditplan/task_wrap.go
https://github.com/actiontech/sqle/issues/2895
1. 执行异常扫描任务实例查询去重，并过滤已停止的任务
2. 错误日志优化
> [!TIP]
=> fix: sql manage duplicate warning error of instance audit plan

sqle/api/controller/v1/analysis.go, sqle/server/auditplan/task_wrap.go
https://github.com/actiontech/sqle-ee/pull/2180#discussion_r1926403987
- 提取GetQueryCost方法
> [!TIP]
=> fix: extract GetQueryCost

sqle/model/task_files.go
https://github.com/actiontech/sqle/issues/2884
文件模式上线审核，触发规则结果统计修改
1、触发的error、normal、notice不统计执行报错的规则
2、 执行报错的规则数量计入warn中
> [!TIP]
=> modify: execution failed rule statistics

sqle/api/app.go, sqle/api/controller/v1/knowledge_base.go, sqle/api/controller/v1/knowledge_base_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
1. 定义知识库列表接口，用于搜索和展示知识库列表
2. 定义知识库标签列表接口，用于根据标签搜索知识库列表
> [!TIP]
=> api definition: get knowledge base and tags of knowledge base #2192

sqle/api/controller/v1/knowledge_base.go, sqle/model/knowledge_base.go, sqle/model/tags.go, sqle/model/utils.go, sqle/server/knowledge_base/knowledge_base_ce.go, sqle/sqled.go
1. 表结构定义：知识表，标签表
2. 更新API定义
3. 在SQLE启动时迁移旧的知识库（ce空实现）
> [!TIP]
=> Model and HTTP API definition

sqle/api/controller/v1/knowledge_base.go, sqle/api/controller/v1/knowledge_base_ce.go, sqle/api/controller/v1/system_module.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
1. 增加接口定义：用于检查知识库模块是否可用
2. 增加接口定义：用于查看知识图谱
> [!TIP]
=> api definition for check module knowledge base

sqle/api/controller/v1/knowledge_base.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
link https://github.com/actiontech/sqle-ee/pull/2213
1. 修改知识图谱的接口的标签
> [!TIP]
=> update swagger modify tag of api

sqle/api/controller/v1/instance.go
issue：https://github.com/actiontech/dms/issues/349
调整获取数据库插件logo接口，数据库类型入参改为数组
> [!TIP]
link https://github.com/actiontech/dms/pull/369
=> issue_dms_349

sqle/server/fillsql/fill_sql.go
#2915
修复频繁执行sql分析后导致的连接泄漏
> [!TIP]
=> #2915: fix connection leak

sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/rule/rule_ce.go, sqle/model/knowledge_base.go, sqle/model/rule.go, sqle/model/utils.go, sqle/server/knowledge_base/knowledge_base_ce.go, sqle/sqled.go
https://github.com/actiontech/sqle-ee/issues/2222
link https://github.com/actiontech/sqle-ee/pull/2228
1. 变更表结构，将规则和自定义规则中的知识库id去除，将知识库的规则名称去除
2. 增加关联关系表 
3. 初始化知识库
> [!TIP]
=> optimize the structure of knowledge related tables

build/sqled.spec, build/sqled_with_dms.spec, scripts/sqled.systemd
- https://github.com/actiontech/sqle-ee/issues/2254
-在sqled.systemd文件中配置java环境变量
> [!TIP]
=> fix: failed to start oracle plugin

sqle/api/controller/v1/knowledge_base.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
link https://github.com/actiontech/sqle-ee/pull/2255
https://github.com/actiontech/sqle-ee/issues/2247
1. 定义根据规则名称获取知识图谱子图谱的接口
> [!TIP]
=> api definition: add filter on get graph API

sqle/driver/mysql/rule/ai/rule_list.go, sqle/driver/mysql/rule/ai/rule_list_trial.go
cherry pick
https://github.com/actiontech/sqle/pull/2947
skip review
=> fix AI rules in trial

sqle/api/app.go, sqle/api/controller/v1/configuration.go, sqle/api/controller/v1/configuration_ce.go, sqle/api/controller/v1/sql_audit_record.go, sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/utils/util.go
https://github.com/actiontech/sqle/issues/2942
- 快捷审核GIT审核支持分支选择
> [!TIP]
=> feat: 快捷审核git仓库审核，支持指定仓库分支

sqle/api/controller/v1/task.go, sqle/dms/common.go
link https://github.com/actiontech/dms/pull/382
https://github.com/actiontech/dms/issues/340?open_in_browser=true
- Add TODO comment in task.go for considering HTTPS in sqled
- Add TODO comment in dms/common.go for considering HTTPS in sqled
> [!TIP]
=> refactor: add TODO comments for HTTPS consideration

sqle/cmd/scannerd/scanners/common/common_test.go, sqle/cmd/scannerd/scanners/common/parse.go
https://github.com/actiontech/sqle-ee/issues/2229
- 使用regex去匹配替换行内注释
> [!TIP]
=> fix: scanner扫描带注释的xml文件报错

sqle/api/controller/v1/configuration.go, sqle/api/controller/v1/configuration_ce.go
https://github.com/actiontech/sqle/issues/2942
- 将方法:testGitConnectionV1移动到公共代码，防止EE编译报错
> [!TIP]
=> fix: move testGitConnectionV1 to configuration.go

sqle/api/controller/v1/sql_manage.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/2267
link: https://github.com/actiontech/sqle-ee/pull/2271
> [!TIP]
=> fix: move SqlAnalysisChart message

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/splitter/splitter.go, sqle/driver/mysql/splitter/splitter_test.go, sqle/driver/mysql/splitter/splitter_test_3.sql
https://github.com/actiontech/sqle/issues/2956
- 修复识别BEGIN语句块错误
> [!TIP]
=> fix: 审核带有Begin的语句会出现语法分析报错

sqle/driver/v2/util.go
https://github.com/actiontech/sqle-ee/issues/2243
修复数据库结构对比获取变更sql时数组下标越界
> [!TIP]
link http://10.186.18.21/sqle/sqle-oracle-plugin-j/-/merge_requests/268
=> fix: fix index out of range

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/task.go, sqle/utils/csv_builder.go, sqle/utils/util.go
https://github.com/actiontech/sqle-ee/issues/2250
link https://github.com/actiontech/sqle-ee/pull/2291
1. cherry-pick 变更到3.2404.x
> [!TIP]
=> feat(utils): add CSVBuilder for CSV file generation with Excel compatibility

.github/workflows/pr-agent.yml, .pr_agent.toml
#2977 
添加AI复审的actions和prompt
> [!TIP]
=> add configuration for pr-agent

sqle/driver/plugin_manager.go
https://github.com/actiontech/sqle-ee/issues/2307
> [!TIP]
=> cherry-pick: 使用绝对路径解决 Java 插件执行问题

sqle/api/controller/v2/instance_audit_plan.go, sqle/dms/instance.go, sqle/model/instance.go, sqle/model/instance_audit_plan_list.go
assigin in @iwanghc 
https://github.com/actiontech/sqle/issues/3008
1. 修复SQL管控列表根据环境标签筛选未生效的问题
2. 调整SQL管控详情，返回环境UID
> [!TIP]
=> fix two probelm in SQL Manage

.github/workflows/pr-agent.yml, .pr_agent.toml
组织内部流程调整，无需建issue
可用的大模型名称变了，调整pr-agent使用的模型名称
> [!TIP]
=> update ai model configuration

sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
skip review
issue：
https://github.com/actiontech/dms-ee/issues/622
创建审核任务接口支持指定审核规则模板，用于数据导出使用专属审核规则模板
代码已在已复审在main，cherry-pick到05
___
- 增加 rule_template_name 字段
- 添加规则模板逻辑验证
- 同步更新接口文档与 Swagger 配置
___
```mermaid
flowchart LR
A["sqle/api/controller/v1/task.go"] -- "新增字段及逻辑" --> B["审核任务处理更新"]
A -- "变更数据模型" --> C["接口参数更新"]
C -- "同步更新文档" --> D["sqle/docs/docs.go"]
C -- "同步更新 Swagger" --> E["sqle/docs/swagger.json & swagger.yaml"]
```
<tr>
<td>
<details>
<summary><strong>task.go</strong><dd><code>添加审核任务规则模板支持</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Db conf audit template

Makefile
https://github.com/actiontech/sqle-ee/issues/2354#issuecomment-3142674867
避免makefile中使用新版本git特性，兼容gocd流水线中老版本git
> [!TIP]
___
- 改进标签获取与排序逻辑
- 使用 sort -rV 优化标签排序
- 修正稳定版与预发布标签的选择
___
```mermaid
flowchart LR
A["获取 HEAD_HASH"] --> B["使用 git tag --points-at"]
B --> C["通过 sort -rV 排序"]
C --> D["过滤稳定版标签"]
C --> E["处理预发布标签"]
```
<tr>
<td>
<details>
<summary><strong>Makefile</strong><dd><code>更新标签获取与排序命令</code>&nbsp; &nbsp; &nbsp; &nbsp; …
=> build: improve tag retrieval and sorting in Makefile

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
https://github.com/actiontech/sqle-ee/issues/2488#issuecomment-3157217434
- 修复规则: 对字段创建约束前，建议先创建索引
- 规则针对约束是指非空约束（Not Null），检查约束（Check），默认约束（Default），外键约束(FOREIGIN KEY)进行触发
> [!TIP]
___
- 修改测试用例中SQL语句
- 扩展检查逻辑支持外键和CHECK约束
- 补充DEFAULT和非空约束的处理
___
```mermaid
flowchart LR
A["\"测试用例更新\""] --> B["\"规则处理逻辑更新\""]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>audit_test.go</strong><dd><code>更新测试逻辑以验证检查索引规则</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: rule checkIndexesExistBeforeCreatConstraints

sqle/driver/mysql/rule/rule.go, sqle/utils/util.go
https://github.com/actiontech/sqle/issues/2049
- Enhance the checkEventScheduler rule to also detect Event SQL statements
- Implement a new IsEventSQL utility function for identifying Event-related SQL
> [!TIP]
=> feat(rule): add detection for Event SQL in rule checks

sqle/api/controller/v2/instance_audit_plan.go, sqle/server/optimization/sql_flash/sql_flash_types.go, sqle/server/support_checker.go
https://github.com/actiontech/sqle-ee/issues/2498
- 定义SQLFlash接口对应的数据结构
- 调整module_status接口中调优功能是否支持的判断逻辑
- 删除instance_tips接口中对调优功能的数据源类型过滤
> [!TIP]
___
- 新增 SQL Flash 优化数据结构定义
- 更新优化检测逻辑使用配置参数判断
- 移除实例提示中过滤数据库类型的检查
- 改进整体 SQL 优化支持逻辑
___
```mermaid
flowchart LR
A["实例提示API更新"] -- "移除DB类型过滤" --> B["instance_audit_plan.go"]
C["新增SQL Flash功能"] -- "定义新数据结构" --> D["sql_flash_types.go"]
E["优化支持检测变更"] -- "使用配置判断" --> F["support_checker.go"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><t …
=> Sql flash ce

go.mod, go.sum, sqle/api/app.go, sqle/api/controller/v1/configuration.go, sqle/dms/system_variable.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/configuration.go, sqle/model/utils.go, sqle/model/workflow.go, sqle/notification/notification.go, sqle/pkg/im/im.go, sqle/server/clean.go, vendor/github.com/actiontech/dms/internal/dms/pkg/constant/const.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/db_service.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/member.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/plugin.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/router.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v1/user.go, vendor/github.com/actiontech/dms/pkg/dms-common/api/dms/v2/router.go, vendor/github.com/actiontech/dms/pkg/dms-common/dmsobject/user.go, vendor/github.com/actiontech/dms/pkg/dms-common/i18nPkg/bundle.go, vendor/modules.txt
skip review
https://github.com/actiontech/dms-ee/issues/597
> [!TIP]
=> Cherry pick notif

sqle/api/controller/v1/analysis.go, sqle/api/controller/v1/instance_audit_plan.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v2/audit_plan.go, sqle/api/controller/v2/sql_anaysis_task.go, sqle/api/controller/v2/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/2519
- 增加是否下发影响行数的参数
> [!TIP]
___
- 添加 `affectRowsEnabled` 参数控制是否计算影响行数
- 更新各 API 接口逻辑以支持新参数传递
- 调整 swagger 文档及相关 JSON/YAML 文件，补充参数说明
- 优化错误处理逻辑，仅在启用参数时返回影响行数数据
___
```mermaid
flowchart LR
A["修改 GetSQLAnalysisResult 接口"] --> B["传递 affectRowsEnabled 参数"]
B --> C["调整各 API 接口逻辑"]
C --> D["更新 Swagger 文档"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>6 files</summary><table>
<tr> …
=> feat: add affect rows param

sqle/api/controller/v1/analysis.go, sqle/api/controller/v1/instance_audit_plan.go, sqle/api/controller/v1/sql_manage.go, sqle/api/controller/v2/audit_plan.go, sqle/api/controller/v2/sql_anaysis_task.go, sqle/api/controller/v2/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
skip review
https://github.com/actiontech/sqle-ee/issues/2519
> [!TIP]
___
- 更新函数签名，添加 affectRowsEnabled 参数
- 新增查询参数解析逻辑控制影响行数计算
- 修复 SQL 分析接口计算逻辑异常问题
- 完善 Swagger 文档，补充 affectRowsEnabled 参数说明
___
```mermaid
flowchart LR
A["API入口"]
B["解析 Query 参数 affectRowsEnabled"]
C["调用 GetSQLAnalysisResult"]
D["条件判断执行影响行数计算"]
A -- "获取 affectRowsEnabled" --> B
B -- "传递参数" --> C
C -- "判断后计算" --> D
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>5 files</summary><table>
<tr> …
=> Cherry pick main

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/session/context.go
https://github.com/actiontech/sqle/issues/3130
新增MySQL规则：DDL执行前，判断是否有事务未提交
> [!TIP]
=> New rule 2.2306.x

sqle/driver/plugin_adapter_v2.go, sqle/driver/plugin_manager.go
link https://github.com/actiontech/sqle-ee/pull/2542
https://github.com/actiontech/sqle-ee/issues/2541
方案和测试：https://github.com/actiontech/sqle-ee/issues/2541#issuecomment-3301777660
1. 增加插件主动关闭的日志，方便后续排查
> [!TIP]
___
- 在插件适配器中增加插件停止前后日志记录
- 在插件管理器中添加停止时日志输出
___
```mermaid
flowchart LR
A["PluginProcessorV2 Stop 方法"] -- "添加开始与结束日志" --> B["记录插件停止状态"]
C["pluginManager Stop 方法"] -- "添加停止日志" --> B
```
<tr>
<td>
<details> …
=> feat: 增加插件停止时的日志记录功能

sqle/driver/mysql/analysis.go
fix: https://github.com/actiontech/sqle/issues/3138
修复MySQL分析SQL时，从SQL中提取相关表的实现
> [!TIP]
___
- 重构SQL解析逻辑，简化表名提取
- 使用 utilV2.GetTableNames 统一处理节点
- 消除冗余的多分支逻辑判断
___
```mermaid
flowchart LR
A["原有多分支逻辑"] -- "被替换" --> B["调用 utilV2.GetTableNames"]
B -- "返回表名列表" --> C["执行 addTable 添加表"]
```
<tr>
<td>
<details>
<summary><strong>analysis.go</strong><dd><code>重构SQL表提取逻辑</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Fix mysql analysis

sqle/api/controller/v2/workflow.go
https://github.com/actiontech/sqle/issues/3143
删除更新工单时关于审批流程模板的校验（前端会有二次确认的交互）
> [!TIP]
___
- 删除工单更新多余校验逻辑
- 移除审批流程模板检查
- 简化后端工单更新流程
___
```mermaid
flowchart LR
A["删除获取模板逻辑"]
B["移除模板存在性验证"]
C["删除提交前校验操作"]
A --> B
B --> C
```
<tr>
<td>
<details>
<summary><strong>workflow.go`</strong><dd><code>移除模板校验相关冗余代码</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix(workflow): remove unnecessary workflow template check
