sqle/driver/mysql/mysql.go

The fields of inst are need for pt-osc command line.
#130

fix: panic when enable pt-osc

---

sqle/driver/mysql/executor/executor.go

fix sql syntax error, using backticks to warp schema name

---

sqle/driver/mysql/audit.go
sqle/driver/mysql/mysql.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/session/context.go
sqle/driver/mysql/session/mock_context.go

Add explain check 

---

sqle/api/app.go
sqle/api/controller/v1/audit_plan.go
sqle/api/controller/v1/auth.go
sqle/api/middleware/jwt_test.go
sqle/utils/aes.go
sqle/utils/jwt.go

fix pr #392, the original jwt key is "secret" who has been changed when we set it is same as aes secret key, so the audit token cannot be used after upgrading SQLE from 1.2202.0 to 1.2203.0

fix pr #392

---

sqle/driver/mysql/executor/executor.go

#499
创建审核任务时，如果表名中存在以关键字（比如group）明明的表，审核任务可以正常创建，页面可以正常打开，但是SQL语句池是空的，查看日志时发现是SQL执行异常
time="2022-05-05T10:24:52+08:00" level=error msg="query sql failed; host: 10.0.11
.123, port: 3306, user: root, query: show create table group, error: Error 1064::
You have an error in your SQL syntax; check the manual that corresponds to yourr
MySQL server version for the right syntax to use near 'group' at line 1\n" namee
=meta_iastdb thread_id=J90 type=audit_plan

修复表名为关键字时审核任务无法正常展示的问题

---

sqle/model/sql_query.go

issue509 fix model

---

sqle/api/controller/v1/sql_query.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

correct api response

---

sqle/api/cloudbeaver_wrapper/app.go
sqle/api/cloudbeaver_wrapper/service/base.go
sqle/api/cloudbeaver_wrapper/service/user.go

#891 修复用户登录成功后续操作失败会报错, 修复SQLE拿到的CB是否登录有误
1. 如果用户登录成功了, 后续TriggerLogin()中间件无论出什么错都应该把登录接口的响应抛回前侧
2. 只有从SQLE处登录, SQLE的cookie转换中间件才会生效, cookie得转换后才能拿到正确的用户状态(当前是否登录)

issue_891 fix bug

---

sqle/api/controller/v1/rule.go
sqle/model/rule.go
sqle/model/utils.go

#960
* sql工作台的审核 
* * 规则模板应该从项目和全局里找sqle/api/cloudbeaver_wrapper/service/audit.go:47
* 扫描任务
* * 添加扫描任务，实例的规则模板应该从项目和全局里找 sqle/api/controller/v1/audit_plan.go:357
* 删除全局和项目规则模板
* * 获取模板数据时应该只从一个指定的项目里拿 
* * * sqle/api/controller/v1/rule.go:916
* * * sqle/api/controller/v1/rule.go:268
* 更新全局和项目规则模板
* * 获取模板数据时应该只从一个指定的项目里拿 
* * * sqle/api/controller/v1/rule.go:750
* * * sqle/api/controller/v1/rule.go:155
* 创建默认模板
* * 获取模板数据时应该只从一个指定的项目里拿
* * * sqle/model/utils.go:245
* 克隆项目模板
* * 使用和克隆全局模板一样的函数判断模板是否存在 sqle/api/controller/v1/rule.go:1053
* 删除全局规则模板
* * 应该检查模板是否在任意项目中被使用 sqle/api/controller/v1/rule.go:275

issue_960 debug fix bug

---

sqle/api/app.go
sqle/api/controller/v2/audit_plan.go
sqle/api/controller/v2/sql_audit.go
sqle/api/controller/v2/task.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

feat:
- 新增 API 定义 GET: /v2/tasks/audits/{task_id}/sqls
- 新增 API 定义 POST: /v2/sql_audit
- 新增 API 定义 GET: /v2/projects/{project_name}/audit_plans/{audit_plan_name}/reports/{audit_plan_report_id}/sqls
related: #1411

feat: 新增 API 定义，升级了 audit_result 审核结果结构定义

---

sqle/api/controller/v1/rule.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

fix:
- 新增 api query 参数 filter_rule_names
- 修复 #1416 中引入的 swagger doc 文档错误

fix(rule): api 新增query参数支持通过 rule_name 列表获取 rule 

---

sqle/api/cloudbeaver_wrapper/service/audit.go
sqle/api/controller/v1/audit_plan.go
sqle/api/controller/v1/sql_audit.go
sqle/api/controller/v1/task.go
sqle/api/controller/v2/audit_plan.go
sqle/api/controller/v2/sql_audit.go
sqle/api/controller/v2/task.go
sqle/driver/v2/driver_interface.go
sqle/errors/errors.go
sqle/model/audit_plan.go
sqle/model/audit_plan_list_test.go
sqle/model/audit_plan_report.go
sqle/model/audit_plan_report_list.go
sqle/model/task.go
sqle/server/audit.go
sqle/server/auditplan/task.go
sqle/server/sqled_test.go

feat:
- 新增接口实现。与旧接口相比，接口功能没有太大变化。仅字段 audit_result 格式有所变化。
- /v2/projects/{project_name}/audit_plans/{audit_plan_name}/reports/{audit_plan_report_id}/sqls。
- /v2/sql_audit。
- /v2/tasks/audits/{task_id}/sqls
fix:
- model 模型字段格式调整，需要升级工具支持
- AuditPlanReportSQLV2，表名 "audit_plan_report_sqls_v2"
- ExecuteSQL，表名 execute_sql_detail
- 由于模型字段格式调整，同时调整了单元测试用例代码
related: #1411

feat: 新增 AuditResults 若干接口实现

---

sqle/api/controller/v1/audit_plan.go
sqle/api/controller/v1/task.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

feat:
- GET:/v1/tasks/audits/{task_id}/sqls/{number}/analysis 新增「性能统计」字段，返回「影响行数」等信息
- GET:/v1/projects/{project_name}/audit_plans/{audit_plan_name}/reports/{audit_plan_report_id}/sqls/{number}/analysis 新增「性能统计」字段，返回「影响行数」等信息
related: #1413

feat(api): API 新增「性能统计」字段，返回「影响行数」等信息

---

sqle/driver/mysql/audit_test.go
sqle/server/audit.go
sqle/server/auditplan/task.go

fix：
- (auditplan) processlist 审核任务采集的 SQL，可能执行在不同的 schema 上。因此在审核语句列表中插入了 `USE ${schema_name}` 切换语句。同时审核任务对象 task 会在审核完成后重新生成分数
test:
- 根据 lint 工具优化了一处测试代码

fix: processlist 审核任务 sql，新增 schema 切换动作

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go

针对规则"dml_not_recommend_func_in_where"新增了检查步骤。如果在 where 字句中出现了位运算符和算术运算符，则认定为触发了该规则。具体为：
位运算：`<<`,`>>`,`&`,`|`,`~`,`^`
算术运算：`+`,`-`,`*`,`\`,`%`
#1463

fix(rule): 新增对where子句中算术和位运算符的检查

---

sqle/driver/mysql/audit.go
sqle/utils/util.go
sqle/utils/util_test.go

参考：https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
索引不应区分大小写
related: #1399

fix: 修复审核alter语句中索引大小写问题

---

sqle/api/controller/v2/task.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

Add new filters to the API to allow filtering by the new task sql execution status and audit status values. The new values are:
- terminating
- terminate_succ
- terminate_fail
This change was made to allow better filtering of task sqls in the API.
related: #1519

feat(task): add new task sql execution status 

---

sqle/driver/mysql/mysql.go
sqle/driver/plugin_adapter_v1.go
sqle/driver/plugin_adapter_v2.go
sqle/driver/plugin_interface.go
sqle/server/sqled.go
sqle/server/sqled_test.go
sqle/server/workflow_schedule.go

- refactor(action): 重构了 action.execute() 代码，使之支持异步terminate。
- feat：
- (action): 新增了 action.terminateExecution()，使得可以阻塞等待中止操作。
- (plugin): 新增审核插件 KillProcess() 接口定义。
related: #1519

feat: sqle action 新增 terminate 信号监听

---

sqle/server/sqled.go
sqle/server/workflow_schedule.go
sqle/utils/func_test.go

fix:
- 修复在上线完成后，action.task.status 字段没有及时更新的问题。
#1519 
- 在通知之前更新工单状态，以确保通知内容为最新内容
#450 
test:
- 调整测试用例的时间，以确保 cancel 发生的时间的准确性。

fix: 修复action.task 对象中状态没有更新的问题

---

sqle/api/controller/v1/configuration.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml
sqle/model/configuration.go
sqle/notification/email.go

#1365 
feat:
1. 为表global_configuration_smtp增加字段is_skip_verify
2. 修改/v1/configurations/smtp [get] 和 /v1/configurations/smtp [patch] 接口
3. 发送邮件Notify函数支持跳过认证

Fix issue1365

---

sqle/driver/mysql/rule/rule.go

参考文档：
- https://github.com/pingcap/tidb/blob/master/types/parser_driver/value_expr.go#L247
- https://docs.pingcap.com/zh/tidb/dev/expression-syntax#%E8%A1%A8%E8%BE%BE%E5%BC%8F%E8%AF%AD%E6%B3%95-expression-syntax
related: #1432 #1447

fix(mysql_rule): 调整检查selec where子句中绑定变量的方式

---

sqle/model/workflow_list.go

chore:fix issue 1605

---

sqle/driver/mysql/rule/rule.go

fix rule name

---

go.mod
go.sum
sqle/api/app.go
sqle/api/controller/v1/sql_audit.go
sqle/api/controller/v2/sql_audit.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml
vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/context.go
vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/mapper.go
vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/mappers.go
vendor/github.com/actiontech/mybatis-mapper-2-sql/go.mod
vendor/github.com/actiontech/mybatis-mapper-2-sql/parser.go
vendor/modules.txt

support directly audit several files

---

sqle/driver/mysql/rule/rule.go

Issue 1741

---

sqle/api/controller/v1/configuration.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

chore:add request body

---

sqle/driver/mysql/audit.go
sqle/driver/mysql/mysql.go
sqle/driver/mysql/session/context.go
sqle/driver/mysql/util/parser_helper.go
sqle/server/audit.go

Cherry pick

---

sqle/api/controller/v2/workflow.go
sqle/model/configuration.go
sqle/pkg/im/im.go

#1756 
direct cause: a panic occurred when accessing a nil pointer while retrieving the workflow.assignee in the dingTalkRotation function.
root cause: the status of the dingtalk instance was not updated when the workflow was canceled. as a result, the dingTalkRotation function, which handled the canceled workflow, filtered by the dingtalk instance whose status was not updated correctly.
solution: update the status of the dingtalk instance to “canceled” in the logic for closing the workflow. this will prevent similar issues from occurring in the future.

fix-issue1756: panic in dingTalkRotation function

---

sqle/api/controller/v1/audit_plan.go
sqle/api/middleware/jwt.go
sqle/api/middleware/jwt_test.go

#1758 
Details: Create audit plan failed due to the audit plan name being too long. 
Direct reason: The length of the jwt token exceeds the upper limit of varchar(255) defined in the data table, resulting in insert failure. 
Deep reason: The length of apn(audit plan name) is too long, resulting in the generated jwt token being too long. 
Solution: Use MD5 to hash the name and apn that may be too long to make the name and apn for generating each token become fixed-length, thereby controlling the length of the token.
@linxiaotao

fix-issue1758: create audit plan failed

---

sqle/api/controller/v1/workflow.go

fix:git commit error

---

sqle/api/controller/v1/audit_plan.go

#1758 
username in jwt token will be check when http request go throuth middleware and use username to check if user exist, if using md5 algorithm to resize username, the middleware cannot find user by token.
@linxiaotao

hot-fix: cannot using hash algo in generate token

---

sqle/api/controller/v2/workflow.go
sqle/server/ding_talk.go

#1756 
when canceling the workflow, before the goroutine to cancel dingtalk_instance has been executed, the background scheduled task will obtain and access the closed workflow, causing panic. Solution: Verify its status after obtaining the workflow by the background scheduled task. If it is canceled, the next logic will not be executed
@linxiaotao

fix: small probability of causing panic

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/session/context.go

fix issue 1783 2

---

sqle/api/controller/v1/sql_audit.go

修复日志打印的问题，”direct audit files failed“ 不应该作为标签，这会让所有后续日志都打印该信息。
```bash
time="2023-09-14T14:16:27+08:00" level=info msg="starting call plugin interface [Audit]" /v2/audit_files="direct audit files failed" plugin=Oracle plugin_version=2 session_id=be1e689c04a2436ab2ecd37cacd2afd2 thread_id=S73
```

fix log, field don't add message

---

sqle/api/controller/v1/sql_audit_record.go

https://github.com/actiontech/sqle-ee/issues/1027
replace the logic of only pushing the first item of the parsed SQL list into the buffer with traversing each SQL and pushing it into the buffer
@winfredLIN

fix: extract sqls from xml file only save one

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/util/visitor.go
sqle/driver/mysql/util/visitor_test.go

#1888 
fix func: getTableNameCreateTableStmtMap
problem: this function cannot get all of tables from a joinStmt
fix func: getOnConditionLeftAndRightType
problem: this function cannot get all of colume name from BinaryOperationExpr
temporary solution: supports mapping from table alias to table, but the table can only consist of one table
@winfredLIN

fix: DMLCheckJoinFieldType rule not triggered

---

sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/util/visitor.go
sqle/driver/mysql/util/visitor_test.go

modified: correct spelling of word column

---

sqle/api/controller/v1/audit_plan.go

#1897 
problem:
the old version scanner will not filter out empty sql, and will uploaded empty sql, causing empty node after parse error.
solution:
in sqle server, we filter out SQL files uploaded by scanner with empty SQL content and do not save them to the database.
@winfredLIN

fix: empty node after parse cause by empty sql

---

sqle/driver/mysql/util/util.go

https://github.com/actiontech/sqle/issues/1903

Fix count affect row

---

sqle/api/app.go

https://github.com/actiontech/sqle-ee/issues/1071
@WinfredLIN

feat: support adding enterprise customized api

---

spelling_dict.txt
sqle/cmd/scannerd/scanners/common/common_test.go
sqle/cmd/scannerd/scanners/common/parse.go

Problem solved:
1. Upload pure annotations as SQL
2. For unresolved statements, aggregation is not possible
Solution:
1. Modify the condition judgment for the parsing result, and do not upload for cases where the parsing result is not empty but successfully parsed
2. For unresolved statements, process their strings and remove comments,
@winfredLIN

fix: incorrect fingerprint algorithm parsing result

---

sqle/driver/mysql/util/parser_helper.go

#1917 
add handling in cases where the like pattern type is FuncCallExprd, match function concat, and prefix match its first variable
@WinfredLIN

fix: dml_check_fuzzy_search rule cannot handle concat function

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/util/visitor.go

fix issue 1913

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/session/context.go

#1918 
optimize the performance of calculate index selectivity in the case of large tables
modify test case of  rules about index selectivity

perf: the performance of calculating index selectivity

---

sqle/driver/mysql/audit_offline_test.go
sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/util/function_result_generator.go
sqle/driver/mysql/util/function_result_generator_test.go
sqle/driver/mysql/util/parser_helper.go
sqle/driver/mysql/util/visitor.go
sqle/driver/mysql/util/visitor_test.go

#1974 
1. the rule DMLCheckFuzzySearch unsupport upper function
2. when there is no where in the outer layer of the SQL statement, the where statement of the subquery will not be checked
1. DMLCheckWhereIsInvalid
2. DMLCheckWhereExistNot
3. DMLCheckWhereExistScalarSubquery
4. DMLCheckFuzzySearch
1. Rule DMLCheckFuzzySearch supports the upper function
2. When there is no WHERE in the outer layer of the SQL statement but there is a WHERE statement in its subquery, the WHERE statement in the subquery will also be checked

fix: two questions, involving four rules

---

sqle/api/controller/v1/sql_manage.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

https://github.com/actiontech/sqle-ee/issues/1166

Issue sort

---

sqle/driver/mysql/optimizer/index/optimizer.go

#1955 
Type assertion was made on the node of the join, but it was not determined whether the assertion was successful. Therefore, accessing the nil variable resulted in panic.
When making type assertions on nodes in a join, determine whether the assertion is successful.

fix: panic when process join node with using in optimizer

---

sqle/api/controller/v1/task.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

Fix issue1969

---

sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/session/context.go

#2015 
Resolve this issue by checking the existence of the corresponding table before obtaining selectivity.

fix: get index selectivity error, when table not exist

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go

#2027 
在检查函数的时候，检查函数中是否涉及表中的列，若不涉及，则不触发该规则。
不触发该规则的函数有两种：
1. 如now()这种不包含任何参数的函数
2. 如DATE('2023-01-01')这样不包含列但包含参数的函数用法

修复：应避免在 WHERE 条件中使用函数或其他运算符，使用不作用在列上的函数，会触发该规则

---

sqle/driver/mysql/audit_executed_sql_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/rule/rule_test.go

Fix issue2022

---

sqle/driver/mysql/audit_executed_sql_test.go
sqle/driver/mysql/audit_offline_test.go
sqle/driver/mysql/audit_test.go
sqle/driver/mysql/context_test.go
sqle/driver/mysql/rule/rule.go

修复：建议主键命名为"PK_表名“，当未为主键命名的时候，规则不触发

---

spelling_dict.txt
sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/session/context.go

#2043 
when the table creation statement declares the column character set and table character set (both are the same), trigger the rule
Support checking column character sets in table creation statements
Add support for the following scenarios
1. If both columns and tables declare a character set. The character set of the column is different from the character set of the table, triggering the rule.
2. If the column declares a character set, the table does not declare a character set and only declares sorting rules. The sorting rule corresponds to a character set that is different from the column character set, triggering the rule.
3. If the column declares a character set, the table does not declare a character set and sorting rule. The column character set and the database default …

fix: rule DDLRecommendTableColumnCharsetSame mistriggered 

---

sqle/driver/mysql/executor/executor.go
sqle/driver/mysql/mysql.go
sqle/driver/mysql/session/context.go
sqle/driver/mysql/util/util.go

#2065 
对函数做了兼容性的修改：
```bash golang
func (c *Executor) ShowDatabases(ignoreSysDatabase bool) ([]string, error)
func (c *Executor) ShowSchemaTables(schema string) ([]string, error)
func (c *Executor) ShowSchemaViews(schema string) ([]string, error)
func (c *Context) getSelectivityByIndex(indexes []index) (map[string] /*index name*/ float64, error)
func (c *Context) getSelectivityByColumn(columns []column) (map[string] /*index name*/ float64, error)
```
对结构体MysqlDriverImpl，增加了修改executor的方法
```bash golang
func (i *MysqlDriverImpl) SetExecutor(dbConn *executor.Executor)
```

Compatible with TDSQL database responses with info column 

---

sqle/driver/mysql/audit.go
sqle/driver/mysql/audit_offline_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/util/util.go

Fix issue2049 6

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/context_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/session/context_test.go

#2089 
1. fix: rule not triggered by the SQL below, in this SQL, table2.column_1 do not have index.
``` sql
select * from table_1 left join table_2 on table_1.column_1 = table_2.column_1 and table_1.column_2 = 'some_value';
select * from table_1 cross join table_2 where table_1.column_1 = table_2.column_1 and table_1.column_2 = 'some_value';
```
3. support check multi-column index
4. support check USING and WHERE clause
5. support check multi-join SQL

fix: rule DMLCheckJoinFieldUseIndex not triggered

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/executor/executor.go
sqle/driver/mysql/session/context.go

#2104 
in MySQL, it is not recommended to include - in database and column names, but it is possible to include.
To use it, it is necessary to add a \` ` to the database and column names, otherwise MySQL will return an error
Additionally, strings are distinguished by '' or ''
In the SQL of requests made to MySQL in SQLE, it is necessary to ensure that both database and table names use\` `, and strings use "" or ''

fix: audit SQL error, when database name with line-through '-'

---

sqle/driver/mysql/advisor.go
sqle/driver/mysql/advisor_test.go
sqle/driver/mysql/mysql.go
sqle/driver/mysql/util/parser_helper.go

#2145 
fix panic when accept a nil where statement.
#2146 
modify description of index optimize advice content.
fix mix judging full fuzziness as left fuzziness

fix: panic when accept a nil where stmt

---

sqle/driver/mysql/audit_offline_test.go
sqle/driver/mysql/rule/rule.go

#2062 
Scan SQL to get all select statement, then scan every select fields of every select statement, if find a field using `COUNT` but not using `DISTINCT`, rule triggere.

fix: increase rule coverage and cover subqueries 

---

sqle/server/auditplan/task.go

https://github.com/actiontech/sqle-ee/issues/1230
The convertRawSQLToModelSQLs function was updated to include a 'schema' parameter for handling SQL schema identification. This change improves the system's search capability, allowing users to perform more flexible and precise schema searches. The calling function and related documentation have been updated accordingly.

Add schema parameter to convertRawSQLToModelSQLs function

---

spelling_dict.txt
sqle/api/controller/v1/audit_plan.go
sqle/api/controller/v1/audit_plan_test.go
sqle/api/controller/v2/audit_plan.go
sqle/model/audit_plan.go
sqle/model/utils.go
sqle/utils/util.go
sqle/utils/util_test.go

This update requires modifications to the existing temporary table `black_list_audit_plan_sqls`
Before starting SQLE, do the following on the database
```
ALTER TABLE `black_list_audit_plan_sqls`
DROP INDEX `filter_sql`;
ALTER TABLE `black_list_audit_plan_sqls` 
CHANGE `filter_sql` `filter_content` VARCHAR(512) NOT NULL;
```
Supports three types of slow log filtering: IP, HOST, and CIDR

feat: add three types of slow log blacklist: IP, HOST, and CIDR

---

sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/session/context.go

https://github.com/actiontech/sqle-ee/issues/1256

set getTableNameCreateTableStmtMap to sessionContext func

---

sqle/driver/mysql/advisor.go
sqle/driver/mysql/advisor_test.go
sqle/driver/mysql/mysql.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/session/mock_context.go
sqle/driver/mysql/util/util.go
sqle/pkg/params/params.go

#2154 
1. Treating the column of the in statement as a non equivalent column
2. Fill in selectivity when extracting columns from SQL statements
3. Added exclude fields of type JSON as part of the index
4. Fixed the issue of inaccurate coverage index judgment
5. Added display of single column index when Samsung Index suggests providing single column index

modify: enhance three star advisor and fix a problem 

---

sqle/driver/mysql/advisor.go
sqle/driver/mysql/advisor_test.go
sqle/driver/mysql/mysql.go
sqle/driver/mysql/rule/rule_list.go
sqle/driver/mysql/session/mock_context.go
sqle/driver/mysql/util/util.go
sqle/pkg/params/params.go

https://github.com/actiontech/sqle/issues/2154

Issue2154 cherry pick to sqle v3

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/session/mock_context.go

fix type check bug

---

sqle/driver/mysql/advisor.go
sqle/driver/mysql/advisor_test.go

https://github.com/actiontech/sqle/issues/2190
add the judgment of column types when adding non equivalent columns

fix: non equivalent conditions do not exclude columns with inappropriate types

---

sqle/api/controller/v1/task.go

issue：github.com/actiontech/sqle-ee/issues/1404
描述：导出工单时在cvs文件头写入UTF-8 BOM，防止Microsoft Office excel打开时出现中文乱码

导出工单时在cvs文件头写入UTF-8 BOM，防止中文乱码

---

.github/workflows/check-pr-files.yml

和功能无关，不建issue
修复github actions中“prevent-file-change”失效的问题
“prevent-file-change”是为了防止把应该提交到ce仓库的公共代码提交到ee仓库的一个job，但是最近发现它失效了，当有错误提交的时候也不会报错
通过回退actions版本可以解决问题，原因可能是中间某次更新导致了主逻辑发生变化。变更繁多，没有具体去定位，因为回退版本就可以达到目的
不再使用标签指定指定版本，改用最初使用的commit号，这样就不会有更新了
只是github actions的变更，不会影响任何产品功能
> [!TIP]

the latest v1 can not prevent files which matches the rule pattern

---

build/sqled_with_dms.spec

actiontech/sqle-ee/issues/1482
rpm打包时默认会压缩jar包，导致安装后java插件无法运行。增加一个配置取消压缩来解决这个问题
> [!TIP]

fix bug: plugin which code by java can not run

---

sqle/api/app.go
sqle/api/controller/v2/task.go
sqle/api/controller/v2/workflow.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml
sqle/model/task.go

**调用逻辑中，与原有的调用流程相比，原来的流程是1->3，新增流程2，当工单上线模式是文件模式时，流程变为1->2->3，并且3根据文件id进行筛选。其他无变化。**
1. 用户点击SQL工单列表的某一个工单时，前端调用接口：`/projects/:project_name/workflows/:workflow_id/`接口获取工单的信息：
2. 根据exec_mode判断工单的执行模式，若执行模式是文件模式，则根据工单所有的审核任务id调用新增的接口`GET /tasks/audits/{task_id}/files`，获取当前SQL审核任务的所有文件信息及其SQL的概览列表：
3. 用户点击单个文件，调用`/tasks/audits/:task_id/sqls`，进入文件的详情页面，页面根据文件，呈现文件中的sql及其审核结果、执行状态的列表
`GET /tasks/audits/{task_id}/files`
用途：获取当前项目、当前SQL工单下的文件及其SQL概览信息列表。
**详情信息包括：**
1. 文件执行顺序
4. 文件名称
5. SQL审核的结果标志（各等级规则是否存在触发）
6. 上线情况
7. 文件ID（用于调用获取审核任务sql列表的接口，根据文件id筛选sql）
**各等级规则包括：**
- normal 
- notice
- warnning
- error
**上线情况包括：**
- 上线成功
- 上线失败
- 等待上线
- 上线中
`GET /tasks/audits/:task_id/sqls`
新增Query Parameter：`filter_audit_file_id`，用于根据文件id筛选，审核任务的sql列表，用于呈现单个文 …

接口复审：SQL审核以文件聚合的展示页面

---

sqle/api/controller/v1/sql_audit_record.go
sqle/api/controller/v1/task.go
sqle/api/controller/v2/workflow.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml
sqle/driver/mysql/mysql.go
sqle/driver/plugin_adapter_v1.go
sqle/driver/plugin_adapter_v2.go
sqle/driver/plugin_interface.go
sqle/driver/v2/driver_interface.go
sqle/model/task.go
sqle/model/task_files.go
sqle/model/workflow.go
sqle/server/sqled.go
sqle/server/sqled_test.go

**新增功能：**
1. 支持使用SQL文件执行SQL，模拟数据库客户端执行SQL文件的行为
2. 前提条件：选择数据源时，数据源对应的插件支持执行SQL文件
**修改表结构：**
1. tasks表增加字段exec_mode，用于存储执行sql的模式，在执行SQL时用于判断执行模式
2. workflows表增加字段exec_mode，用于存储工单中文件执行的模式，前端表现层获取
3. audit_files表增加字段exec_order，用于记录文件执行的顺序
4. audit_files表增加字段parent_id，用于记录文件之间的层级关系
**修改http接口：**
1. 创建审核任务接口，增加字段exec_mode，用于记录sql执行的方式
2. 获取审核任务接口，字段sql_source增加枚举值zip_file,git_repository，用于区分工单是否上传的zip文件，若是，在驳回的时候，需要重新上传zip文件。
3. 获取工单信息接口，增加返回字段exec_mode，因为文件执行的细粒度/层级，在SQL工单上，一个SQL工单的上线方式只有一种（sql或sql文件）。
**更新了swagger文档**
> [!TIP]

feat：support using SQL files to execute SQL

---

sqle/server/sqled.go

https://github.com/actiontech/sqle-ee/issues/1562
1. 修改了执行多个SQL文件当文件执行失败的处理逻辑，修改为当SQL文件执行失败，不再执行剩余SQL文件
> [!TIP]

fix: when SQL file execution fails, no more SQL files will be executed

---

sqle/api/controller/v1/audit_plan_test.go
sqle/utils/util.go
sqle/utils/util_test.go

https://github.com/actiontech/sqle/issues/2448
1. 修改正则表达式，让正则表达式能够匹配多行
> [!TIP]

Fix the issue of SQL blacklist invalidation in multiple rows of SQL

---

sqle/driver/plugin_manager.go

https://github.com/actiontech/sqle/issues/2465
提升插件pid文件夹的权限，修复创建pid文件时权限不足问题
问题原因：
插件pid文件夹为0644，没有执行权限，导致无法open该文件夹创建pid文件
解决：提升pid文件夹权限至0755
> [!TIP]

fix: up pidfile dir permission

---

Makefile

make it possible to specify GOARCH when compile

---

sqle/api/app.go
sqle/api/controller/v1/instance_audit_plan.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

Issue#2497

---

sqle/api/controller/v1/instance_audit_plan.go
sqle/dms/instance.go
sqle/driver/mysql/executor/executor.go
sqle/driver/mysql/session/context.go
sqle/model/instance_audit_plan.go

创建实例扫描任务返回data字段的大小写命名修改
修复更新dms数据源业务时同步至实例扫描任务失败问题
修复采集sql时选择的数据库名存在特殊字符报错问题（如“-”）
删除实例扫描任务或扫描任务时同步删除队列中数据
> [!TIP]

Origin manage sql queues

---

sqle/api/app.go
sqle/api/controller/v1/instance_audit_plan.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

https://github.com/actiontech/sqle-ee/issues/1660
- 更新 audit plan sql meta 接口返回结构
- 更新swag文档
> [!TIP]

Update audit plan sql meta api

---

Makefile

https://github.com/actiontech/sqle-ee/issues/1687
修改Makefile，新增标志变量IS_PRODUCTION_RELEASE，用于指定当前打包是否是发版
> [!TIP]

Only use the version number to name the rpm package when publishing.

---

sqle/model/instance_audit_plan.go
sqle/server/auditplan/manager.go
sqle/server/auditplan/metrics.go

https://github.com/actiontech/sqle/issues/2523
扫描任务跑增量同步时，获取到不需要同步的任务问题修复
新增start_time Metric
> [!TIP]

Issue 2523 ce

---

sqle/api/controller/v1/instance_audit_plan.go
sqle/utils/util.go

close https://github.com/actiontech/sqle/issues/2530
智能扫描任务sql导出时，对超长的列进行截取，避免超出Excel类工具单元格字符数上限
> [!TIP]

truncate audit plan sql when exporting for Excel view

---

sqle/api/controller/v1/pipeline.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

1. 增加流水线节点id在更新的时候便于判断节点是没有修改、更新参数、删除还是新建节点
2. 当节点更新参数（除了名称），相当于一个新的节点，命令变化，用户需要重新复制命令
3. 若没有修改或者只修改名称，命令不会变化，则不需要重新复制命令
> [!TIP]

api definition: add pipeline node id for updating node

---

sqle/api/controller/v1/instance.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

https://github.com/actiontech/dms/pull/298
> [!TIP]

api definition: add oppermission for creating pipeline

---

sqle/api/controller/v1/instance_audit_plan.go
sqle/api/controller/v1/pipeline.go
sqle/cmd/scannerd/cmd/mybatis.go
sqle/cmd/scannerd/cmd/root.go
sqle/cmd/scannerd/cmd/slowquery.go
sqle/cmd/scannerd/cmd/sqlfile.go
sqle/cmd/scannerd/command/base.go
sqle/cmd/scannerd/command/command.go
sqle/server/auditplan/meta.go
sqle/server/pipeline/pipeline.go

方案page_id：169738586
1. 定义scannerd/command，将scannerd的命令集中在此处定义
> 在package cmd中，引用scannerd/command，对cmd进行初始化，对变量和标志名称关联
> 若在cmd中初始化时调用了一个未在scannerd/command定义的标志，能够在初始化阶段引发panic，能够在dev阶段发现问题
> 定义了生成command的方法，会检查：必须的flag是否存在，值是否为空。传入的标志位是否存在，类型是否正确。
2. 解除 scannerd/cmd 到 auditplan/meta 的直接依赖，为二者添加依赖scannerd/command。避免了循环依赖和传递循环依赖
3. auditplan和pipeline生成command方法都使用了scannerd/command中的command生成方法，能够在scannerd的定义发生变化时，保持一致性。
> [!TIP]

optimize: unified management of scanner commands

---

sqle/cmd/scannerd/command/base.go

1. 对生成scanner命令的函数做了详尽的注释
2. 优化了生成scanner命令的用户使用体验，对于必要参数，会使用引导词引导用户填写
> [!TIP]

scannerd: generate command, add prompt words instead of returning errors

---

sqle/api/controller/v1/rule.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

https://github.com/actiontech/sqle/issues/2580
审核规则模版支持csv格式导出
> [!TIP]

chore:rule template api define

---

sqle/api/app.go
sqle/api/middleware/jwt.go
sqle/api/middleware/jwt_test.go
sqle/utils/jwt.go

https://github.com/actiontech/sqle/issues/2602
1. 对于慢日志扫描，将慢日志扫描的接口组移动到v1路由组外，该接口的权限校验全由ScannerVerifier来鉴权
2. 在ScannerVerifier中，针对token过期的错误，放行包含该错误的token
> [!TIP]

fix: expired token causes scannerd to be unable to access SQLite normally

---

.github/workflows/check-pr-files.yml

https://github.com/actiontech/sqle-ee/issues/1838
触发pr时增加commit检查，如果包含actions-user提交的commit，就不允许合并
ce代码不会有这个问题，所以只要ee代码检查就可以
> [!TIP]

Prohibit commits from actions-user.

---

sqle/api/controller/v1/workflow.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml
sqle/model/workflow_list.go

工单列表，返回工单绑定的版本，支持通过版本筛选
> [!TIP]

feat: get workflows with sql version and can filter by version

---

sqle/api/controller/v2/workflow.go
sqle/api/controller/v3/workflow.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml
sqle/model/workflow.go
sqle/server/sqlversion/sql_version_ce.go

https://github.com/actiontech/sqle-ee/issues/1807#issuecomment-2401551908
link: https://github.com/actiontech/sqle-ee/pull/1875
1. 修改工单详情接口，增加2个字段，标记工单能否执行，前端根据能否执行置灰或者正常显示按钮
2. 在执行工单的相应接口，增加对工单是否能执行的前置条件校验
功能特性：页面上将用户不能执行的工单的执行按钮颜色变成灰色的特性
限制条件：当工单状态为等待执行时，且工单绑定了SQL版本的某个阶段，且该工单在该阶段中，位于工单前面的工单存在状态不是已关闭或者成功执行的两种状态之一，则不允许执行该工单的sql
> [!TIP]

feat: it is not allowed to execute workflow that have pre-workflow was not executed correctly

---

sqle/api/controller/v1/sql_version_ce.go
sqle/api/controller/v2/workflow.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

修复社区版不支持版本管理的提示内容
工单详情接口新增返回值，返回工单所关联版本的id
> [!TIP]

Sql version manage

---

sqle/api/controller/v1/workflow.go

link https://github.com/actiontech/sqle/pull/2693
1. 实现了全局dashboard工单列表根据用户角色显示
2. 集中管理了全局dashboard权限和可见性的判断
> [!TIP]

modify: global workflow display based on roles

---

sqle/driver/mysql/util/parser_helper_test.go
sqle/pkg/driver/impl.go

https://github.com/actiontech/sqle/issues/2603
github.com/percona/go-mysql/query中生成指纹的函数Fingerprint特殊情况会panic，使用github.com/actiontech/sqle/sqle/driver/mysql/util中的指纹函数替换
> [!TIP]
assign in @winfredLIN

use util.Fingerprint to fix panic ce

---

sqle/model/instance_audit_plan.go
sqle/model/sql_manage.go
sqle/model/workflow.go

https://github.com/actiontech/sqle/issues/2601
背景:工单提交，若需审批成员过多时会报错数据超长
修复:修改审批成员的数据类型长度为2000
> [!TIP]

工单提交，若需审批成员过多时会报错数据超长

---

scripts/functions.sh
scripts/init_config.sh

https://github.com/actiontech/sqle/issues/2682
- 在functions.sh中增加restart_sqle方法
- restart_sqle方法的具体实现是先执行stop_sqle.sh, 后执行init_start.sh
> [!TIP]
assign in @winfredLIN

fix: 使用脚本执行插件配置，脚本在最后应该restart服务

---

sqle/api/controller/v1/backup.go
sqle/api/controller/v1/task.go
sqle/api/controller/v2/task.go
sqle/api/controller/v2/workflow.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

link https://github.com/actiontech/dms/pull/322
issue: https://github.com/actiontech/sqle-ee/issues/1956
新增接口定义：
1. 创建工单，审核接口中增加保存备份策略
2. 查看工单详情，增加工单中的数据源是否开启备份
3. 查看工单SQL，增加备份策略以及备份策略提示信息
4. 创建回滚工单，复用创建工单接口，增加关联工单字段，关联原有工单
5. 创建重试工单，复用更新工单接口，扩大允许更新的工单的范围
6. 变更策略，新增接口支持变更单个SQL的备份策略
7. 变更策略，新增接口支持批量变更所有工单中的某个数据源的SQL的备份策略
8. 下载回滚SQL，新增接口，支持下载原始SQL和备份SQL的excel文件
9. 获取回滚SQL列表，新增接口，用于用户创建回滚工单前，选择回滚的SQL
> [!TIP]

api definition: for backup and recovery

---

sqle/api/controller/v1/backup.go
sqle/api/controller/v2/task.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

1. 接口调整：修改枚举
2. 接口调整：删除多余的空格
> [!TIP]

api definition: modify according to front end feedbacks 

---

sqle/api/controller/v1/rule.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

https://github.com/actiontech/sqle/issues/2742
全局规则模版新增IsDefaultRuleTemplate字段,用来确认规则模版是否是默认规则模版
> [!TIP]
link https://github.com/actiontech/sqle/pull/2744

chore:global default rule template add IsDefaultRuleTemplate field

---

sqle/api/controller/v1/rule.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

https://github.com/actiontech/sqle/issues/2742
IsDefaultRuleTemplate 字段迁移至规则模版tips接口
> [!TIP]
link https://github.com/actiontech/sqle/pull/2744

chore:change IsDefaultRuleTemplate to tips api

---

sqle/api/controller/v1/instance.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

1. 在数据源tips列表增加标志数据源开启备份的返回值
> [!TIP]

api definition: instance tip add enable backup param as response

---

sqle/api/controller/v1/backup.go
sqle/api/controller/v1/task.go
sqle/api/controller/v2/task.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

1. 更新了更新备份策略的接口的路径，该接口仅用于更新备份策略的按钮，区别于更新sql备注。因为更新备份策略的单独的业务逻辑和原有更新备注的不同。将两个字段更新放在同一个接口中，可能会让接口变得更复杂。
3. 在根据task执行状态筛选中，增加了新的task状态
> [!TIP]

api definition: modify path for updating backup strategy, add filter type for execute status of task 

---

sqle/model/instance_audit_plan.go
sqle/server/auditplan/job_task_handler.go

https://github.com/actiontech/sqle/issues/2761
1. 修复获取扫描任务时无法正确判断扫描任务是否存在。
2. 删除扫描任务时，将管控及相关数据软删除改为硬删除。表数据。
3. 队列sql出栈执行审核时，若扫描任务被删除，则同步删除已保存的管控sql。
> [!TIP]

fix: fix the audit plan being deleted, causing sql audit panic

---

sqle/server/auditplan/sql_info.go
sqle/server/auditplan/task_type_mysql_audit_log_ali.go
sqle/server/auditplan/task_type_mysql_processlist.go
sqle/server/auditplan/task_type_mysql_schema_meta.go
sqle/server/auditplan/task_type_mysql_slowlog_ali.go
sqle/server/auditplan/task_type_mysql_slowlog_baidu.go
sqle/server/auditplan/task_type_mysql_slowlog_huawei.go
sqle/server/auditplan/task_type_oracle_topsql.go

https://github.com/actiontech/sqle/issues/2764
修改生成sql id逻辑，新增扫描任务id（audit plan id）作为参数，并去掉实例任务id（source id ）参数
> [!TIP]

optimize: audit plan gen sql id

---

sqle/driver/mysql/audit_offline_test.go
sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go
sqle/utils/util.go

https://github.com/actiontech/sqle/issues/2732
- 新增四条mysql规则
> [!TIP]

feat: 新增MySQL规则

---

build/sqled.spec
build/sqled_with_dms.spec
sqle/api/app.go
sqle/api/controller/v1/sql_rewriting.go
sqle/api/controller/v1/sql_rewriting_ce.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

https://github.com/actiontech/sqle-ee/issues/2037
设计原型发生变更，本次跟进调整：
1. 添加默认的重写配置，方便用户识别配置
2. API入参增加“是否开启数据库结构类型重写”的开关，默认为false
3. API返回增加“sql业务含义”
4. 接口从GET变为POST，考虑原因：api中涉及了模型调用，可能产生费用，且生成不幂等，换为POST接口
> [!TIP]

Sql rewriting fix

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/session/mock_context.go

https://github.com/actiontech/sqle/issues/2794
1.  当数据表定义中存在多个联合索引时，若查询条件能够匹配任意一个联合索引的最左前缀，则视为通过规则审核。
2.  若查询条件中的字段能够命中数据表上任一联合索引的最左前缀，则满足规则要求。
3.  若查询条件中涉及的字段未包含在任何联合索引中，则不触发该规则。
> [!TIP]

feat:rule supports matching multiple combined indexes

---

sqle/model/utils.go

https://github.com/actiontech/sqle/issues/2759
- 根据和产品讨论的规则分类，进行重新细化分类映射
> [!TIP]

fix: 细化新的规则分类映射

---

sqle/api/app.go
sqle/api/controller/v1/instance.go
sqle/dms/common.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

https://github.com/actiontech/dms/issues/346
新增获取插件logo的接口
> [!TIP]
link https://github.com/actiontech/dms/pull/348

Optimize plugin configuration ce

---

sqle/server/auditplan/task_type_mysql_processlist.go

https://github.com/actiontech/sqle/issues/2841
调整MySQL的ProcessList任务获取SQL的方式：通过 "SHOW FULL PROCESSLIST" 获取SQL，避免获取的SQL不完整
> [!TIP]

Fix my sql process list truncated sql

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/rule/rule_list.go
sqle/driver/mysql/rule/rule_list_trial.go

https://github.com/actiontech/sqle/issues/2857
将DMLCheckScanRows的规则变更应用到3.2408.x
目的是为了给zjrc的tdsql插件增加一个基于3.2408.x-ee的分支

cherry-pick rule fix to release 3.2408.x

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/rule/rule.go

https://github.com/actiontech/sqle/issues/2855
test 
1. 修复当ALTER语句中修改列解析后列的字符集类型对象为nil时panic的问题
> [!TIP]

fix: panic when use nil tp of sql in rule DDLRecommendTableColumnCharsetSame

---

sqle/api/app.go
sqle/api/controller/v1/instance_audit_plan.go
sqle/api/controller/v1/sql_manage.go
sqle/api/controller/v1/sql_manager_ce.go
sqle/api/controller/v2/audit_plan.go
sqle/cmd/scannerd/scanners/common/interface_func.go
sqle/cmd/scannerd/scanners/mybatis/mybatis.go
sqle/cmd/scannerd/scanners/scanner.go
sqle/cmd/scannerd/scanners/slowquery/slowquery_ce.go
sqle/cmd/scannerd/scanners/sql_file/sqlfile.go
sqle/cmd/scannerd/scanners/supervisor/supervisor.go
sqle/cmd/scannerd/scanners/supervisor/supervisor_test.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml
sqle/errors/errors.go
sqle/model/instance_audit_plan.go
sqle/pkg/scanner/client.go
sqle/server/auditplan/task_wrap.go

https://github.com/actiontech/sqle/issues/2868
sqle采集或者scannerd慢日志文件采集出现问题时，记录最后一次采集状态和打印错误日志
> [!TIP]

Audit plan err prompt ce

---

sqle/api/controller/v1/sql_manage.go
sqle/api/controller/v2/task.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml
sqle/driver/mysql/mysql.go
sqle/driver/v2/driver_interface.go
sqle/model/task.go

https://github.com/actiontech/sqle/issues/2860
新增audit_execution_error类型表示审核规则执行报错
审核规则执行报错将错误信息记录到audit result中，防止报错的审核规则被跳过无感知
> [!TIP]

Add audit result error result ce

---

sqle/api/controller/v1/analysis.go
sqle/api/controller/v1/sql_manage.go
sqle/api/controller/v1/task.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml

- https://github.com/actiontech/sqle-ee/issues/2164
- sql_analysis接口增加cost字段
- 当前端选中24小时tab需要将当前执行计划展示到趋势图
> [!TIP]

fix: api: sql_analysis add cost property

---

sqle/model/instance_audit_plan.go
sqle/model/instance_audit_plan_list.go
sqle/model/instance_audit_plan_list_test.go
sqle/model/utils.go

https://github.com/actiontech/sqle-ee/issues/2145#issuecomment-2606576888
1. Model增加deleted_at的索引，保证在使用deleted_at作为筛选字段的时候能够有效利用索引 https://github.com/actiontech/sqle-ee/issues/2145#issuecomment-2603993413
2. sql_manage_records表中增加复合索引idx_source_id_source。因为有很多的SQL根据这两个字段筛选记录。增加该索引后，有很多SQL都能使用上该索引。
3. 优化GetManagerSQLListByAuditPlanId函数：影响扫描任务触发sql审核功能 https://github.com/actiontech/sqle-ee/issues/2145#issuecomment-2603808056
4. 优化GetManagerSqlSchemaNameByAuditPlan函数：影响部分可以通过schema筛选记录的智能扫描，如mysql slow log(目前仅有它 https://github.com/actiontech/sqle-ee/issues/2145#issuecomment-2604181713
5. 优化GetManagerSqlMetricTipsByAuditPlan函数：影响部分可以通过指定Metric如dbuser筛选记录的智能扫描，如mysql slow log(目前仅有它 https://github.com/actiontech/sqle-ee/issues/2145#issuecomment-2604325480
6. 优化GetAuditPlanTotalSQL …

optimize SQLs in SQLE and add TODO 

---

sqle/driver/mysql/audit_test.go
sqle/driver/mysql/mysql.go
sqle/driver/mysql/rule/rule.go
sqle/driver/mysql/util/util.go

https://github.com/actiontech/sqle/issues/2888
对于性能消耗高的SQL，使用explain结果代替直接下发select count(*)
> [!TIP]
--------------- -------------------------------------------------------

Imporve get sql affect row num

---

.github/workflows/check-pr-files.yml
sqle/api/app.go
sqle/api/controller/v1/knowledge_base.go
sqle/config/config.go
sqle/docs/docs.go
sqle/docs/swagger.json
sqle/docs/swagger.yaml
sqle/license/temp_knowledge_license_ce.go
sqle/model/knowledge_base.go
sqle/server/support_checker.go

link https://github.com/actiontech/sqle-ee/pull/2213
1. 使用config文件传递知识库的license（临时）
2. 更新swagger文档
3. model增加rule name字段
4. 增加knowledge 的图谱路由
> [!TIP]

knowledge base support konwledge graph

---

sqle/api/middleware/permission.go

https://github.com/actiontech/sqle/issues/2933
- 项目相关权限检查使用了正确的 project_uid，移除了硬编码的空间ID "700300"
- 修改了全局权限检查的逻辑，使用空字符串
- 移除了未使用的 AdminUserAllowed 中间件
> [!TIP]

fix: remove hardcoded project id in permission middleware

---

sqle/driver/mysql/analysis.go
sqle/driver/mysql/util/util.go

https://github.com/actiontech/sqle/issues/2928?open_in_browser=true
1. 修复在分析INSERT INTO ...... SELECT语句的时候，SELECT语句没有FROM导致的panic问题
2. 修复在分析INSERT INTO ...... SELECT语句的时候，SELECT语句使用UNION导致的panic问题
3. 增加了TODO项目，用于解决无法解析出SELECT子句中SELECT Field中的SUBQUERY refer的表
> [!TIP]

fix: panic when analysis insert into select stmt

---

sqle/api/controller/v1/audit_plan.go
sqle/api/controller/v1/instance_audit_plan.go
sqle/api/controller/v1/rule.go
sqle/api/controller/v1/task.go
sqle/utils/csv_builder.go

https://github.com/actiontech/sqle-ee/issues/2250
test: https://github.com/actiontech/sqle-ee/issues/2250#issuecomment-2709866299
1. 新增CSVBuilder，用于统一管理和构建SCV文件的逻辑
2. 将CSV生成的相关调用处使用CSVBuilder代替
> [!TIP]

fix: excel format error, when the text is too long

---

sqle/model/audit_plan.go
sqle/pkg/oracle/db.go
sqle/pkg/oracle/perf.go
sqle/server/auditplan/task_type_oracle_topsql.go
sqle/server/auditplan/task_wrap.go

https://github.com/actiontech/sqle-ee/issues/2270
1. Oracle Top SQL增加采集用户名称
2. 黑名单，增加用户名称黑名单
> [!TIP]

feat: support filter oracle top sqls by db user name

---

sqle/driver/mysql/executor/executor.go

This change prevents potential errors when schema or table names contain special characters or keywords. By enclosing them in backticks, we ensure proper SQL syntax and improve code robustness.
https://github.com/actiontech/sqle-ee/issues/2287
test https://github.com/actiontech/sqle-ee/issues/2287#issuecomment-2723818485
1. 给采集index的sql的库表加上反引号
> [!TIP]

fix(driver/mysql): add backticks around schema and table names in GetTableIndexesInfo

---

sqle/driver/mysql/mysql.go
sqle/driver/mysql/splitter/block.go
sqle/driver/mysql/splitter/splitter.go
sqle/driver/mysql/splitter/splitter_test.go
sqle/driver/mysql/util/parser_helper.go

issue：https://github.com/actiontech/sqle/issues/3092
1. 修复MySQL存储过程上线审核报错，使用Splitter Parse来获取SQL指纹
2. 增强MySQL 拆分器中的 CASE 块匹配逻辑以处理嵌套控制流语句
> [!TIP]
___
- 修改Fingerprint调用，确保正确指纹解析
- 优化CASE块匹配逻辑处理嵌套
- 改进BEGIN...END块及IF判断逻辑
- 添加单元测试验证CASE语句处理
___
```mermaid
flowchart LR
A["修改Fingerprint方法"]
B["优化CASE匹配逻辑"]
C["改进嵌套块处理"]
D["添加单元测试"]
A --> B
B --> C
C --> D
```
<tr>
<td>
<details> …

Fix mysql procedure audit

---

sqle/server/fillsql/fill_sql.go

FillingSQLWithParamMarker 添加对非MySQL数据库类型的错误处理，确保遇到其他数据库类型快速返回
https://github.com/actiontech/sqle-ee/issues/2464
> [!TIP]
___
- 为非 MySQL 数据库快速返回错误
- 添加错误提示机制
- 提升 SQL 解析逻辑健壮性
___
```mermaid
flowchart LR
A["原始 SQL 解析流程"] --> B["判断数据库类型"]
B -- "非 MySQL" --> C["返回错误提示"]
```
<tr>
<td>
<details>
<summary><strong>fill_sql.go</strong><dd><code>添加非 MySQL 错误返回处理</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

FillingSQLWithParamMarker 添加对非MySQL数据库类型的错误处理，确保遇到其他数据库类型快速返回

---

sqle/dms/instance.go
sqle/model/configuration.go
sqle/model/instance_audit_plan.go
sqle/model/sql_manage_insight_ce.go
sqle/model/task.go
sqle/model/utils.go
sqle/server/audit.go
sqle/server/auditplan/sql_info.go
sqle/server/auditplan/task_type_mysql_processlist.go
sqle/server/clean.go

https://github.com/actiontech/sqle-ee/issues/2450
1. 修改工单SQL相关的execute_sql_detail表，增加SQL指纹字段，供`性能洞察-关联SQL`功能查询使用
2. 新增sql_manage_raw_sqls表，使其保留扫描任务SQL详情，供`性能洞察-关联SQL`功能查询使用
3. sql_manage_raw_sqls数据增加周期任务清理过期数据
4. 调整MySQL processlist 扫描任务，保存原始SQL信息至sql_manage_raw_sqls，以便`性能洞察-关联SQL`功能查询具体单个SQL信息
> [!TIP]
___
- 添加GetInstances接口便于实例查询
- 新增系统变量及默认有效时长设置
- 新增SQLManageRawSQL结构体与创建、清理函数
- 更新ExecuteSQL结构体增加SqlFingerprint字段
___
```mermaid
flowchart LR
A["新增 GetInstances 接口"] --> B["新增系统变量与默认时长"]
B --> C["新增 SQLManageRawSQL 结构体与方法"]
C --> D["更新 ExecuteSQL 增加 SqlFingerprint"]
D --> E["新增清理过期SQL原始记录功能"]
``` …

Sql insight ce

---

Makefile

https://github.com/actiontech/sqle-ee/issues/2354#issuecomment-3149818211
修复makefile构建流程 RPM_NAME 变量包含空格
> [!TIP]
link https://github.com/actiontech/dms/pull/504
___
- 使用 strip 移除多余空格
- 修复项目版本拼接逻辑
- 优化 Makefile 构建流程
___
```mermaid
flowchart LR
A["Makefile 修改"] --> B["添加 strip 删除空格"]
B --> C["确保 PROJECT_VERSION 正确"]
```
<tr>
<td>
<details>
<summary><strong>Makefile</strong><dd><code>移除 PROJECT_VERSION 前后空格</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

build: remove leading and trailing spaces from PROJECT_VERSION

---

sqle/model/workflow.go
sqle/notification/notification.go

link https://github.com/actiontech/dms-ee/pull/651
https://github.com/actiontech/dms-ee/issues/597#issuecomment-3191071930
- SQL工单上线成功/失败需要通知所有在该数据源上有权限的人
> [!TIP]
___
- 添加获取实例ID方法
- 优化成功/失败通知逻辑
- 新增审核权限用户过滤功能
___
```mermaid
flowchart LR
A["Workflow对象"] --> B["GetInstanceIds方法"]
B --> C["getAuditUsersForWorkflowInstances"]
C --> D["getCanOpInstanceUsers"]
D --> E["CanOperationInstance"]
```
<tr>
<td>
<details> …

fix: notify all users with permission when workflow success or failed

---

sqle/driver/mysql/rule/rule.go
sqle/utils/util.go
sqle/utils/util_test.go

https://github.com/actiontech/sqle/issues/2049#issuecomment-3209488978
调整“禁止使用event”规则的正则表达式，使之可以匹配包含调整分隔符语句的情况
> [!TIP]

refactor(rule): remove redundant regex patterns in event SQL detection

---

sqle/api/controller/v1/configuration.go
sqle/server/clean.go

skip review
> [!TIP]
___
- 修正 SSH 密钥判断逻辑错误
- 修改 API 返回中 SSH 公钥条件判断
- 移除系统变量错误码检查
___
```mermaid
flowchart LR
A["配置文件 SSH 校验修改"]
B["API SSH 公钥返回修改"]
C["清理系统变量错误检查修改"]
A -- "调整条件判断" --> B
A -- "移除错误码检查" --> C
```
<tr>
<td>
<details>
<summary><strong>configuration.go</strong><dd><code>优化 SSH 密钥校验及返回处理</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Cherry pick main
