sqle/api/app.go, sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/configuration.go, sqle/model/utils.go
create ldap config model and generate update/get ldap config api
=> Issue 44 api and ldap config model

sqle/model/configuration.go
=> issue-44 Fix the problem that the password cannot be changed in smtp and ldap configuration

sqle/api/controller/v1/auth.go
issue-44 Fix the problem that the automatic registration cannot register the mailbox
=> issue-44 Fix the problem that the automatic registration cannot register the mailbox

.gitignore, go.mod, go.sum, vendor/github.com/actiontech/mybatis-mapper-2-sql/parser.go, vendor/modules.txt
=> Fix empty xml panic

.gitignore, go.mod, go.sum, vendor/github.com/actiontech/mybatis-mapper-2-sql/parser.go, vendor/modules.txt
=> Cherry pick pr 84

sqle/cmd/sqled/sqled.go, sqle/docs/swagger.yaml, sqle/driver/plugin.go
=> fix panic when start SQLE witout --config

sqle/model/instance.go, sqle/model/user.go
=> fix: list user instances not exclude deleted role

sqle/model/audit_plan.go, sqle/model/utils.go, sqle/pkg/scanner/client.go
=> fix can not handle big text SQL

sqle/api/controller/v1/instance.go
If instance driver plugin is build by pkg/driver package, it will open database connection on driver init, so we need wrap the error to custom result to tell the UI it is not connectable.
#103
=> fix: connect database error not custom to API result

sqle/pkg/driver/adaptor.go
=> fix: plugin adaptor do not use rules from SQLE when Audit

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/driver/driver.go, sqle/model/rule.go, sqle/model/utils.go, sqle/server/sqled.go
=> Support rule params

sqle/driver/mysql/util/parser_helper.go, sqle/driver/mysql/util/visitor.go, sqle/pkg/optimizer/index/ast.go, sqle/pkg/optimizer/index/optimizer.go
=> support general index optimization

sqle/driver/mysql/optimizer/index/ast.go, sqle/driver/mysql/optimizer/index/ast_test.go, sqle/pkg/optimizer/index/optimizer.go
=> implement MySQL select AST

sqle/driver/mysql/optimizer/index/optimizer.go, sqle/driver/mysql/optimizer/index/optimizer_test.go, sqle/driver/mysql/util/visitor.go, sqle/driver/mysql/util/visitor_test.go
=> implement general MySQL index optimization

.github/workflows/ci.yml, .golangci.yml
=> add no problem linters

sqle/driver/mysql/optimizer/index/optimizer.go, sqle/driver/mysql/optimizer/index/optimizer_test.go, sqle/driver/mysql/util/parser_helper.go
=> feat: check if prepare indexed columns is needed

sqle/driver/mysql/executor/executor.go, sqle/driver/mysql/mysql.go, sqle/driver/mysql/optimizer/index/optimizer.go, sqle/driver/mysql/optimizer/index/optimizer_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/session/context.go
=> support sort column by cardinality and session context query

.golangci.yml, sqle/api/app.go, sqle/driver/mysql/audit.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/executor/executor.go, sqle/driver/mysql/rollback.go, sqle/driver/mysql/rollback_test.go, sqle/model/audit_plan_test.go, sqle/model/workflow.go, sqle/server/clean.go, sqle/sqled.go
=> Ci add staticcheck

.golangci.yml, sqle/model/configuration.go, sqle/server/clean.go
=> Ci add durationcheck

.golangci.yml, sqle/api/controller/base.go, sqle/api/controller/validator.go, sqle/cmd/scannerd/scanners/mybatis/parser.go, sqle/driver/mysql/mysql.go, sqle/driver/mysql/optimizer/index/optimizer.go, sqle/driver/mysql/util/parser_helper_test.go, sqle/driver/plugin.go, sqle/utils/jwt.go
=> Ci add forcetypeassert

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/workflow.go
=> api define: Refactor workflow status

sqle/api/app.go, sqle/api/controller/v1/task.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/task.go, sqle/model/workflow.go, sqle/model/workflow_test.go, sqle/server/sqled.go, sqle/server/sqled_test.go
=> Support scheduled execution

sqle/api/controller/v1/workflow.go, sqle/model/workflow_list.go
1. use a unified status to display workflow status and task status,
2. display workflow schedule time.
#157
=> show more workflow status

sqle/api/controller/v1/workflow.go, sqle/errors/errors.go, sqle/model/workflow.go, sqle/model/workflow_test.go, sqle/server/sqled.go, sqle/server/workflow_schedule.go
=> Support schedule workflow

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> the schedule user should be display on FE

sqle/api/controller/v1/workflow.go, sqle/model/workflow_list.go
fix workflow status filter does not correspond, you want on_process, but given on_process and exec_scheduled
#157
=> fix workflow status filter

sqle/driver/mysql/optimizer/index/optimizer.go
[#180]when exec explain failed, all audit for all SQL will fail, don't throw a error, just ignore index optimize
=> fix audit error

sqle/api/controller/v1/task.go
=> replenish missing tag

sqle/model/utils.go
=> update default workflow template

sqle/api/middleware/jwt.go, sqle/api/middleware/jwt_test.go
=> add audit plan token check

README.md
=> add desc for sql server plugin

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v2/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Api define 212

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/session/mock_context.go
=> check DDL Table Size

sqle/api/controller/v2/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Fix api define 212

sqle/driver/mysql/optimizer/index/optimizer.go, sqle/driver/mysql/optimizer/index/optimizer_test.go, sqle/driver/mysql/session/context.go, sqle/driver/mysql/session/mock_context.go, sqle/driver/mysql/util/visitor.go
=> *: fix use lowercase table name to query case sensitive database

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> Check dml result line

sqle/api/controller/v2/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add a type to mark the data type, so the FE can set SQL highlight

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/rule.go, sqle/api/controller/v2/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/driver/driver.go, sqle/driver/mysql/rule/rule.go, sqle/driver/plugin.go, sqle/model/audit_plan.go, sqle/model/audit_plan_list.go, sqle/model/audit_plan_list_test.go, sqle/model/rule.go, sqle/model/utils.go, sqle/pkg/params/params.go, sqle/pkg/params/params_test.go, sqle/server/auditplan/manager.go, sqle/server/auditplan/manager_test.go, sqle/server/auditplan/meta.go
=> api controller

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/rule.go, sqle/api/controller/v2/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/driver/driver.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/plugin.go, sqle/model/audit_plan.go, sqle/model/audit_plan_list.go, sqle/model/audit_plan_list_test.go, sqle/model/rule.go, sqle/model/utils.go, sqle/pkg/params/params.go, sqle/pkg/params/params_test.go, sqle/server/auditplan/manager.go, sqle/server/auditplan/manager_test.go, sqle/server/auditplan/meta.go
=> check index too many

sqle/api/controller/v1/user.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
Feat:
- Update APIs definition of user management
related #216
=> Feat: Update APIs to support field "is_disabled"

sqle/api/app.go, sqle/api/controller/v1/user_group.go, sqle/api/controller/v1/util.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/errors/errors.go
Feat:
- Add new API definitions of user group manaement
Related: #215
=> Feat: Add new APIs of user group management.

sqle/api/app.go, sqle/api/controller/base.go, sqle/api/controller/v1/user_group.go, sqle/api/controller/v1/util.go, sqle/api/controller/v2/role.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
Feat:
- Add new API defintions of roles management.
related: #244
=> Feat: Add new APIs of roles management.

sqle/api/app.go, sqle/api/controller/base.go, sqle/api/controller/v1/user.go, sqle/api/middleware/verify_user.go, sqle/errors/errors.go, sqle/model/user.go, sqle/model/user_list.go
Feat:
- Update API GET:"/v1/users" implementation to support user disabled stat；
- Update API GET:"/v1/users/:user_name/" implementation to support user disabeld stat;
- Update API PATCH:"/v1/users/:user_name/" implementation to support user disabled stat;
- Add a middleware to check if user is disabled for all APIs.
related #216
=> Feat: update API implementation of User management.

sqle/driver/driver.go, sqle/driver/mysql/audit.go, sqle/driver/mysql/mysql.go
=> Optimized code

spelling_dict.txt, sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/rule/rule_test.go, sqle/driver/mysql/session/mock_context.go
=> check redundant index

sqle/pkg/scanner/client.go
=> api v1 for audit plan report has deprecated

sqle/api/controller/v1/user_group.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
Fix:
- The param "is_disabled" is meaningless when creating user groups.
=> Fix: remove meaningless http parameter

sqle/api/controller/base.go, sqle/api/controller/v1/user_group.go, sqle/errors/errors.go, sqle/model/base.go, sqle/model/user.go, sqle/model/user_group.go, sqle/model/utils.go
Feat:
- Add const variables to support model stat.
- Add model UserGroup.
- Add implementation of API POST:"/v1/user_groups".
- Comment: add comment.
related: #215 #199
=> Feat: implementation of API POST:"/v1/user_groups"

sqle/api/controller/v1/user_group.go, sqle/errors/errors.go
Feat: 
- impl of API Delete:"v1/user_groups/:user_group_name"
Related:
#215 #199
=> Feat: implementation of API Delete:"/v1/user_groups/:user_group_name"

sqle/api/app.go, sqle/api/controller/v1/operation.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Feat: add definition of API GET:"/v1/operations".

sqle/api/controller/base.go, sqle/api/controller/v1/user_group.go, sqle/model/user_group.go
Feat:
- impl of API Patch:"/v1/user_groups/:user_group_name".
Related: #199 #215
=> Feat: implementation of API Patch:"/v1/user_groups/:user_group_name"

sqle/api/app.go, sqle/api/controller/v1/user_group.go, sqle/model/user_group.go
Feat:
- impl of API Get:"/v1/user_group_tips"
=> Feat: add implementation API Get:"/v1/user_group_tips"

sqle/api/controller/v1/user_group.go, sqle/model/user_group.go
Feat:
- impl of API GET:"/v1/user_groups"
Related: #215 #199
=> Feat: add implementation of API GET:"/v1/user_groups".

sqle/api/controller/v2/role.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
Fix:
change "OperationCode" type from string to uint.
related: #228
=> Fix: fix api definition.

sqle/api/controller/v1/operation.go, sqle/model/operation.go
=> Feat: add impl of API GET:"/v1/operations".

sqle/api/app.go, sqle/api/controller/v1/operation.go, sqle/api/controller/v1/user.go, sqle/api/controller/v2/role.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/operation.go, sqle/model/role.go, sqle/model/user_group.go, sqle/model/utils.go
Updated:
- Update model Role;
- Add implementation of API POST:"/v2/roles"
Dprecated:
- API POST:"/v1/roles"
Related: #228
=> Feat: Add implementation of API POST:"/v2/roles"

sqle/api/app.go, sqle/api/controller/v2/role.go, sqle/model/operation.go, sqle/model/role.go
=> Feat: Add implementation of API PATCH:"/v2/roles/:role_name"

sqle/api/controller/v2/role.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
Fix:
- Model Role can be disabled.
Related: #228
=> Fix: fix api definition of role management

sqle/api/app.go, sqle/api/controller/base.go, sqle/api/controller/v1/role.go, sqle/api/controller/v2/role.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/role.go, sqle/model/role_list.go, sqle/model/utils.go
=> Feat: add implementation of API GET:"/v2/roles/"

sqle/model/audit_plan.go, sqle/pkg/errors/multi_error.go, sqle/pkg/errors/multi_error_test.go, sqle/pkg/oracle/db.go, sqle/pkg/oracle/perf.go, sqle/server/auditplan/manager.go, sqle/server/auditplan/meta.go, sqle/server/auditplan/task.go
=> support Top SQL collector for Oracle

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/util.go, sqle/server/auditplan/meta.go
=> Support issue 307

sqle/api/controller/v1/task.go, sqle/api/controller/v1/workflow.go, sqle/errors/errors.go, sqle/model/instance.go, sqle/model/workflow.go, sqle/model/workflow_list.go
=> support workflow operation permission

sqle/driver/mysql/mysql.go, sqle/driver/mysql/optimizer/index/optimizer.go, sqle/driver/mysql/optimizer/index/optimizer_test.go
=> fix wrong assert interface

sqle/model/user.go
Fix error from #313 
Related: #228
=> Fix: fix wrong query field.

sqle/api/controller/v1/user.go, sqle/api/controller/v1/user_group.go, sqle/model/user_group.go, sqle/model/user_list.go
Fix:
- fix query bug of access to workflows;
- fix param "filter_user_group_name" bug of API GET:"/v1/user_groups";
- fix missing data of API GET:"/v1/users";
- fix error message of API POST:"/v1/user_groups".
=> Fix query bugs for user_groups.

sqle/api/controller/v1/workflow.go, sqle/model/operation.go
=> Fix: remove OP_WORKFLOW_DELETE

sqle/api/controller/v1/instance.go, sqle/errors/errors.go, sqle/model/instance.go, sqle/model/user.go
Refactor:
- Refactor function of getting user instance tips;
- Refactor function of checking user instance.
=> Refactor: query optimization

sqle/api/controller/v1/user.go, sqle/model/user.go
变更：
1. 修复了当更新用户信息时，用户组字段未能更新的问题；
related: #327 
2. 修复了创建用户时，用户组字段未能保存的问题； 
3. 修复了获取用户详情信息时，用户组字段未能获取的问题。
=> Fix: fix several bugs of saving data "user groups"

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/session/context.go, sqle/driver/mysql/session/mock_context.go, sqle/driver/mysql/util/parser_helper.go
=> Fix issue 208

sqle/model/instance.go, sqle/model/user.go
=> Fix: fix instances tips list when user is admin.

sqle/api/controller/v1/user.go, sqle/model/user_list.go
Fix:
- Fix a bug of data being deleted by mistake;
related: #342 
- Fix a bug of query statment.
related: #344
=> Fix: bugs of user management.

sqle/server/audit.go
=> server: relax the Parse function result when audit

README.md
=> readme add db2 url

spelling_dict.txt, sqle/api/app.go, sqle/api/controller/v1/configuration.go, sqle/api/controller/v1/license.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> License api

sqle/api/controller/v1/license.go, sqle/api/controller/v1/license_ce.go
=> Optimized interface definition

sqle/api/controller/v1/license.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> generate api

Makefile, spelling_dict.txt, sqle/api/app.go, sqle/api/middleware/license.go, sqle/api/middleware/license_ce.go, sqle/cmd/sqled/sqled.go, sqle/config/public_variable.go, sqle/model/configuration.go, sqle/model/utils.go
=> Add license

sqle/api/controller/v1/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 329 api

sqle/api/controller/v1/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 268 api

sqle/model/audit_plan_list.go, sqle/model/audit_plan_list_test.go, sqle/pkg/oracle/perf.go, sqle/server/auditplan/task.go
=> Support issue 375

sqle/cmd/scannerd/scanners/supervisor/supervisor.go
=> add more log to print scanner runnning info

sqle/api/controller/v1/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> upgrade /v1/instance_connection [post]

sqle/api/controller/v1/instance.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue 394 api

spelling_dict.txt
=> add spelling_dict.txt

sqle/api/controller/v1/user.go
=> achieve user wechat related

spelling_dict.txt, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/session/mock_context.go
=> Support issue 389

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 407 api

sqle/api/app.go, sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue 353 api

sqle/model/audit_plan.go, sqle/model/audit_plan_test.go, sqle/model/utils.go
=> support #410, using fingerprint md5 as index

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v2/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 429 api

sqle/model/period.go
=> optimize code

sqle/api/controller/v1/instance.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 453 api

sqle/model/audit_plan.go
=> Allow admin to create audit tasks

sqle/api/controller/v1/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 448 api

sqle/model/audit_plan.go, sqle/notification/notification.go, sqle/notification/notification_ce.go
=> issue 448 notifier

spelling_dict.txt
=> issue 448 add to spelling_dict.txt

go.mod, go.sum, vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/data.go, vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/dynamic.go, vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/include.go, vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/mapper.go, vendor/github.com/actiontech/mybatis-mapper-2-sql/parser.go, vendor/modules.txt
=> update vendor, support parser iBatis xml file

sqle/model/workflow_list.go
=> fix issue 450

sqle/api/controller/v1/configuration.go, sqle/api/controller/v1/oauth2.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 470 api

sqle/api/app.go, sqle/api/controller/v1/configuration.go, sqle/api/controller/v1/configuration_ce.go, sqle/api/controller/v1/license_qa.go, sqle/api/controller/v1/oauth2.go, sqle/api/controller/v1/oauth2_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/errors/errors.go, sqle/model/configuration.go, sqle/model/utils.go
=> Issue 470 ce

sqle/model/user.go
=> add ThirdPartyUserID

sqle/api/controller/v1/auth.go
=> add new login type

sqle/api/controller/v1/oauth2.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix Security risks

sqle/driver/mysql/audit.go, sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/audit_test.go
=> 解决社区版MySQL语法解析失败导致审批流程无法正常进行的问题

sqle/driver/mysql/mysql.go
=> notify as an error when dry run failed

sqle/api/controller/v1/instance.go, sqle/api/controller/v1/sql_query.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 509 api

sqle/api/controller/v1/sql_query.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 509 api fix bug

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> modify api: add switch for ssl

spelling_dict.txt, sqle/api/controller/v1/auth.go, sqle/api/controller/v1/configuration.go, sqle/model/configuration.go
=> support ldaps

go.mod, go.sum, vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/dynamic.go, vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/utils.go, vendor/modules.txt
=> fix issue #302, upgrade vendor

sqle/model/instance.go, sqle/model/sql_query.go, sqle/model/utils.go
=> define models

sqle/server/auditplan/task.go
=> fix issue #524

sqle/api/controller/v1/instance.go, sqle/api/controller/v1/instance_ce.go, sqle/model/operation.go, sqle/model/operation_ce.go
=> Issue 509 refactor to differ ce and ee

sqle/api/controller/v1/instance.go, sqle/api/controller/v1/task.go, sqle/model/instance.go, sqle/model/instance_list.go
=> issue 509 upgrade api

sqle/api/controller/v1/instance.go
=> issue 509 Adjust spelling

sqle/api/app.go, sqle/api/controller/v1/sql_query.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> remove redundant path

sqle/api/controller/v1/instance.go
=> rollback api

sqle/driver/mysql/executor/executor.go, sqle/driver/mysql/mysql.go
=> issue 509 Implement SQLQueryDriver ce part

sqle/api/controller/v1/sql_query.go, sqle/model/sql_query.go
https://github.com/actiontech/sqle/issues/509
=> Issue 509 fix

sqle/api/controller/v1/instance.go, sqle/model/sql_query.go
=> Update instance apis

spelling_dict.txt, sqle/driver/driver.go, sqle/driver/driver_audit.go, sqle/driver/driver_ce.go, sqle/driver/mysql/mysql.go, sqle/driver/plugin.go, sqle/driver/plugin_audit.go, sqle/pkg/driver/adaptor.go
=> Issue 526 ce

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/sql_query.go, sqle/api/controller/v1/task.go, sqle/api/controller/v2/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> define apis

sqle/driver/driver_analysis.go
=> define plugin apis

sqle/api/controller/v1/instance.go, sqle/api/controller/v1/sql_query.go, sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add desc for api response

sqle/driver/driver_analysis.go, sqle/driver/mysql/analysis.go, sqle/driver/mysql/executor/executor.go, sqle/driver/mysql/session/context.go
=> List table implement

sqle/driver/mysql/executor/executor.go, sqle/driver/mysql/session/context.go, sqle/server/auditplan/task.go
=> add function to show table metadata

sqle/driver/driver_analysis.go
https://github.com/actiontech/sqle/issues/568
=> Avoid reusing inappropriate code

sqle/api/controller/v2/audit_plan.go, sqle/model/audit_plan_list_test.go, sqle/model/audit_plan_report.go, sqle/model/audit_plan_report_list.go, sqle/server/auditplan/task.go
=> add number field to distinguish each sql in audit-plan-report

sqle/api/app.go, sqle/api/controller/v1/sql_query.go, sqle/api/controller/v1/sql_query_ce.go
=> explain sql api interface

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/audit_plan_ce.go, sqle/model/audit_plan.go, sqle/model/audit_plan_report.go
=> audit plan get analysis data

sqle/api/controller/v1/sql_query.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add necessary annotation

sqle/api/controller/v1/audit_plan.go
=> Fix the problem that the parameters in the array are not validated

spelling_dict.txt, sqle/driver/driver_audit.go, sqle/driver/driver_query.go, sqle/model/configuration.go, sqle/model/instance.go, sqle/model/utils.go, sqle/pkg/driver/adaptor_query.go, sqle/utils/aes.go
[#589 ](https://github.com/actiontech/sqle-ee/issues/256)
=> Issue 589 

build/sqled.spec
=> Redirect standard and error logs

sqle/api/controller/v1/sql_query.go, sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add message to show exception information

sqle/driver/driver.go
https://github.com/actiontech/sqle-ee/issues/256
=> ee 256 add conn plugin error log

sqle/model/instance.go
=> issue 589 open model

sqle/model/user.go
=> issue 621 remove useless function

go.mod, go.sum, vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/dynamic.go, vendor/modules.txt
=> update vendor for fix #639

spelling_dict.txt, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/task.go, sqle/api/controller/v1/util.go, sqle/driver/driver.go, sqle/driver/driver_analysis.go, sqle/driver/driver_audit.go, sqle/driver/driver_query.go, sqle/driver/mysql/audit.go, sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/mysql.go, sqle/driver/mysql/mysql_ce.go, sqle/driver/mysql/mysql_test.go, sqle/driver/mysql/pt_osc.go, sqle/driver/mysql/rollback.go, sqle/driver/mysql/rollback_test.go, sqle/driver/plugin.go, sqle/driver/plugin_audit.go, sqle/pkg/driver/adaptor_audit.go, sqle/pkg/driver/adaptor_query.go, sqle/pkg/driver/plugin_implementor.go, sqle/server/audit.go, sqle/server/sqled.go, sqle/server/sqled_test.go, sqle/server/workflow_schedule.go
#568 
https://github.com/actiontech/sqle-ee/pull/293
=> Refactor driver code

sqle/driver/driver_analysis.go, sqle/driver/plugin.go, sqle/driver/plugin_analysis.go
=> to distinguish error type in plugin usage

spelling_dict.txt
=> fix spell check

sqle/pkg/driver/adaptor_analysis.go, sqle/pkg/driver/adaptor_query.go, sqle/pkg/driver/plugin_implementor.go
put db configuration into function variables, because the functions can't get db connection when it is running
=> put db configuration into function variables

sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle-ee/issues/301
=> ee 301 swagger

sqle/api/controller/v1/instance.go, sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/instance_list.go
=> Issue625 display instance type

sqle/api/controller/v1/dashboard.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> api define， #680

sqle/api/controller/v1/dashboard.go, sqle/api/controller/v1/workflow.go, sqle/model/workflow_list.go
=> Issue680 implement api

sqle/server/auditplan/meta.go, sqle/server/auditplan/task.go
=> Issue687 filter sqls

sqle/driver/driver_audit.go, sqle/server/auditplan/meta.go
=> modify db type name

go.mod, go.sum, vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/dynamic.go, vendor/modules.txt
=> fix issue #704, update vendor for support parer mybatis trim suffix prop

sqle/cmd/scannerd/cmd/mybatis.go, sqle/cmd/scannerd/cmd/slowquery.go, sqle/pkg/scanner/client.go
=> issue 701 Increase timeout

sqle/api/controller/v1/statistic.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> modify field type

sqle/api/app.go, sqle/api/controller/v1/statistic.go, sqle/api/controller/v1/statistic_ce.go
=> add 4 apis' implements for ce

sqle/api/app.go, sqle/api/controller/v1/statistic.go, sqle/api/controller/v1/statistic_ce.go
=> Average wait time for review

sqle/api/controller/v1/statistic.go
=> Implement rejected rate

sqle/api/app.go, sqle/api/controller/v1/statistic.go, sqle/api/controller/v1/statistic_ce.go
=> get task count each day

sqle/model/workflow.go
=> Avarge audit time

sqle/api/controller/v1/statistic.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> return instance count of each instance type

sqle/api/app.go, sqle/api/controller/v1/statistic.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 723 update /v1/statistic/tasks/status_count

spelling_dict.txt, sqle/api/app.go, sqle/api/controller/v1/statistic.go, sqle/api/controller/v1/statistic_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/workflow_list.go
=> Task percent by instance type

sqle/model/workflow.go
=> issue 723 get workflow count funcs

sqle/model/workflow.go
=> Returns the index record grouped by workflow_id order by id desc

sqle/model/task.go, sqle/model/workflow.go
=> Fix work flow average

sqle/model/workflow.go
=> Reuse method GetWorkFlowReverseStepsByIndexAndState

sqle/api/app.go, sqle/api/controller/v1/statistic.go, sqle/api/controller/v1/statistic_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> the api is used for statistics of workflow not task

sqle/api/controller/v1/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 755 api

sqle/driver/mysql/audit.go, sqle/driver/mysql/invalid_offline_test.go
=> Issue 716 invalid offline check

sqle/driver/mysql/audit_after_event_test.go, sqle/driver/mysql/audit_executed_sql_test.go, sqle/driver/mysql/mysql.go, sqle/driver/mysql/rule/rule.go
=> Issue 716 Blocking rules

sqle/driver/mysql/audit.go, sqle/driver/mysql/audit_after_event_test.go, sqle/driver/mysql/audit_executed_sql_test.go, sqle/driver/mysql/invalid_offline_test.go, sqle/driver/mysql/mysql.go, sqle/driver/mysql/rule/rule.go
=> MySQL audit scenario transformation compatible with post audit mode

sqle/driver/mysql/rule/rule.go
=> fix desc error

sqle/driver/mysql/rule/rule.go
=> issue_777 upgrade rule name

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> Issue 777 step3

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> Issue 777 step4

spelling_dict.txt
=> issue_777 upgrade spelling_dict.txt

sqle/model/workflow.go
=> get daily workflow counts by one query

sqle/model/configuration.go
=> Fix plaintext password errors

sqle/driver/mysql/rule/rule.go, sqle/server/audit.go
=> Fix rule panic

sqle/server/audit.go
=> return panic tips for users

sqle/api/controller/v1/dashboard.go
=> Do not display timed online status work orders

sqle/api/controller/v1/rule.go, sqle/model/rule.go
#755 
如果智能扫描任务正在使用这个规则模板, 则规则模板不应该被删除, 删除时需要报错并阻止此操作
=> issue 755 fix bug

sqle/driver/mysql/rule/rule.go
=> fix possible null pointer bug

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/task.go, sqle/api/controller/v2/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/operation.go, sqle/notification/notification.go
=> Rename audit task to scan task

sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> update api interface

sqle/api/controller/v1/task.go, sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> modify apis

sqle/api/controller/v1/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> modify param's name

sqle/api/controller/v1/workflow.go, sqle/model/workflow.go
=> update approve workflow

sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> remove invalid spaces

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> response data should be array

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/task.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/common/driver.go, sqle/common/instance.go, sqle/model/workflow.go, sqle/server/workflow_schedule.go
=> Update execute workflow

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/model/workflow.go, sqle/server/workflow_schedule.go
#832
1. 修改定时上线时间的接口实现
2. 定时上线任务
=> Issue 832 schedule workflow

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go
=> Execute one task

build/sqled.spec
#810 
std log will be overwritten now, using append mode to print log to std.log
=> fix issue 810

sqle/api/app.go, sqle/api/controller/v2/workflow.go, sqle/model/instance.go
=> Get workflow detail

sqle/driver/mysql/executor/executor.go
=> fix issue #859, usting safety way to define sql connector

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Get tasks summary

spelling_dict.txt
=> fix spell for passwd

sqle/model/workflow.go, sqle/notification/notification.go
=> fix notification

sqle/common/driver.go
=> fix ee edition compile errors

sqle/api/controller/v2/workflow.go
=> fill Current Step Number

sqle/model/workflow_list.go
=> temp:fix statistic

sqle/api/controller/v1/dashboard.go, sqle/model/workflow_list.go
=> fix dashboard show error

sqle/api/controller/v2/workflow.go
=> fix current step number

sqle/api/controller/v1/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add enums value:create_audit_workflow

sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue832 optimize code

sqle/api/controller/v1/workflow.go
=> task status should be exec_scheduled only before it is executed

sqle/model/instance.go
=> fix spell error

sqle/model/task.go, sqle/model/workflow.go
=> Regularly clean up tasks and workflow

sqle/notification/notification.go
=> modify email body

sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/task.go, sqle/model/user.go, sqle/model/workflow.go, sqle/notification/notification.go, sqle/server/workflow_schedule.go
=> Issue832 instance summary

sqle/api/controller/v1/instance.go, sqle/model/workflow.go
=> fix api of deleting instance api

sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add executing status filter

sqle/model/workflow.go
=> correct sql

sqle/api/controller/v1/user.go, sqle/api/controller/v1/workflow.go, sqle/model/user.go, sqle/model/workflow.go
=> remove deprecated workflow status

sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Fix date filter api

sqle/api/controller/v1/workflow.go, sqle/model/user.go
=> can not reject workflow if there is any task is executed

sqle/api/controller/v2/workflow.go
=> Workflow success filter

sqle/api/controller/v1/task.go
=> optimize audit flow

spelling_dict.txt
=> ee 842 spelling

sqle/api/controller/v1/workflow.go, sqle/model/workflow.go
=> Check if the work order can go online

sqle/model/workflow.go
https://github.com/actiontech/sqle/issues/915
=> In the same sql mode, the data source type must be the same

sqle/api/controller/v1/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> define api

sqle/api/controller/v1/user.go, sqle/api/controller/validator.go
=> set user email as empty when req.email is empty string

sqle/api/app.go, sqle/api/controller/v1/statistic.go, sqle/api/controller/v1/statistic_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> execute fail percent api define

sqle/api/controller/v1/statistic.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> modify api

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> get audit plan types api

sqle/api/controller/v1/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> modify api define

sqle/api/controller/v1/audit_plan.go
=> get all audit plan types

sqle/api/controller/v1/audit_plan.go, sqle/model/audit_plan_list.go
=> Add query conditions to the scan plan list

sqle/model/instance.go, sqle/model/task.go
=> Issue 901 avg exec time

sqle/model/workflow.go
=> Audit pass rate interface updates

sqle/model/task.go
=> fail percent statistci

sqle/model/workflow.go
=> remove func

sqle/model/workflow.go
=> recycle exec failed workflow

build/sqled.spec, sqle/api/app.go, sqle/cmd/sqled/sqled.go, sqle/config/config.go, sqle/log/logger.go, sqle/sqled.go
#888 
通过配置文件，配置 api.log sqled.log 的回收周期（默认会保存两个日志文件）
=> Log rotation configuration

sqle/model/rule_list.go
=> fix mysql8.0 slow query question

spelling_dict.txt
=> issue 900 spelling

sqle/api/controller/v1/configuration.go
=> Mail check

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v2/audit_plan.go, sqle/pkg/scanner/client.go
Reverts actiontech/sqle#981
合错分支了回滚重提
=> Revert "Issue980 define apis"

sqle/api/app.go, sqle/api/controller/v1/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue984 define apis

sqle/api/cloudbeaver_wrapper/service/instance.go
=> issue 971 support tidb

sqle/api/controller/v1/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> remove useless fields

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue988 define apis

sqle/model/audit_plan.go, sqle/model/instance.go, sqle/model/management_permission.go, sqle/model/project.go, sqle/model/role.go, sqle/model/rule.go, sqle/model/sql_whitelist.go, sqle/model/user.go, sqle/model/user_group.go, sqle/model/utils.go, sqle/model/workflow.go
=> Define model

sqle/api/controller/v1/user.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add management permission for user

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/rule.go, sqle/api/controller/v1/sql_whitelist.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add project id to specify project

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 990 update api

sqle/api/controller/v1/management_permission.go, sqle/api/controller/v1/user.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add api for management permissions

sqle/api/controller/v1/role.go, sqle/api/controller/v1/user.go, sqle/api/controller/v1/user_group.go, sqle/model/role.go, sqle/model/role_list.go, sqle/model/user.go, sqle/model/user_group.go
=> Issue 1004

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> Fix incorrect naming, this rule should belong to DML

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/utils/util.go, sqle/utils/util_test.go
=> Extract the public method of getting the object name

sqle/utils/util_test.go
=> fix ci spell check

sqle/server/audit.go
=> add error tips when whitelist sql is incorrect

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> use rule_template_name in url to comply with the same format

sqle/api/app.go, sqle/api/controller/v1/project.go, sqle/api/controller/v1/user.go, sqle/model/project.go, sqle/model/user.go
#978
获取项目tips：/v1/project_tips [get]
获取项目详情：/v1/projects/{project_name} [get]
=> Issue 978 1

sqle/api/app.go, sqle/api/controller/v1/project.go, sqle/model/instance.go, sqle/model/project.go
#978 
1. 通用成员判断逻辑
2. 修复一部分发现的问题
3. 调整现有实现以复用判断逻辑
=> Issue 978 public func

sqle/api/app.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/project.go, sqle/model/instance.go, sqle/model/project.go, sqle/model/project_list.go, sqle/model/user.go
=> Issue 984 create instance and get instance

sqle/api/cloudbeaver_wrapper/service/audit.go, sqle/api/controller/v1/rule.go, sqle/api/controller/v1/sql_audit.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/project.go, sqle/model/rule.go, sqle/model/rule_list.go, sqle/model/utils.go, sqle/server/audit.go, sqle/server/auditplan/task.go, sqle/server/sqled.go, sqle/server/sqled_test.go
=> Implement rules

sqle/cmd/scannerd/cmd/mybatis.go, sqle/cmd/scannerd/scanners/mybatis/mybatis.go
=> scanner can skip audit

sqle/cmd/scannerd/cmd/mybatis.go, sqle/cmd/scannerd/cmd/root.go, sqle/cmd/scannerd/cmd/slowquery.go, sqle/pkg/scanner/client.go
=> Timeout limit

sqle/api/app.go, sqle/api/controller/v1/management_permission.go, sqle/api/controller/v1/user.go, sqle/model/management_permission.go, sqle/model/user.go
=> Issue 1004 2

sqle/api/controller/v1/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/rule.go
=> change api to support using global rule template when add instance

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/model/project.go
=> Issue960 create task project

sqle/api/controller/v1/workflow.go
=> Issue960 fix create workflow

sqle/api/app.go, sqle/api/controller/v1/project.go, sqle/api/controller/v1/user.go, sqle/api/controller/v1/user_group.go, sqle/model/instance.go, sqle/model/project.go, sqle/model/role.go
=> Issue 998 user group

sqle/api/controller/v1/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> one instance can bind only one rule template name

sqle/api/cloudbeaver_wrapper/service/audit.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/rule.go, sqle/model/audit_plan.go, sqle/model/rule.go, sqle/model/utils.go
=> Adjust rule template name

sqle/api/controller/v1/workflow.go, sqle/model/workflow.go
=> add storage project id to db

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/workflow_list.go
=> Workflow list

sqle/api/app.go
=> Add new router

sqle/api/app.go, sqle/api/controller/v1/user.go, sqle/api/controller/v1/user_group.go, sqle/model/project.go, sqle/model/user_group.go, sqle/model/utils.go, sqle/sqled.go
#960 
1. 增加删除用户前的项目检查
2. 删除用户时删除自动移除项目成员
=> Issue 998 remove

sqle/api/app.go, sqle/api/controller/v1/workflow.go
=> List all workflows

sqle/api/app.go, sqle/api/controller/v1/workflow.go
=> get workflow template

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add api to get workflow detail

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue990 change field

sqle/api/app.go, sqle/api/controller/v1/workflow.go
=> update workflow template api implement

sqle/api/controller/v1/user.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/project.go
=> Issue 1004 get user api add param user is manager

sqle/model/project.go, sqle/model/project_list.go, sqle/model/user.go
=> issue 960 fix bug

sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/project.go, sqle/api/controller/v1/project_permission.go, sqle/api/controller/v1/task.go, sqle/api/controller/v1/workflow.go, sqle/model/audit_plan.go, sqle/model/instance.go, sqle/model/project.go, sqle/model/project_permission.go, sqle/model/project_permission_test.go, sqle/model/user.go, sqle/model/utils.go, sqle/model/workflow.go
=> Issue980 model refactor

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/workflow.go
=> Workflow detail

sqle/model/project_list.go
=> issue 960 debug

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/model/project_permission.go
=> 960 workflow approve

sqle/api/controller/v1/instance.go, sqle/api/controller/v1/instance_ce.go
=> Issue 976 2

sqle/api/app.go, sqle/api/controller/v1/workflow.go
=> Reject workflow

sqle/api/app.go, sqle/api/controller/v1/workflow.go
=> Cancel workflow

sqle/api/controller/v1/rule.go, sqle/model/audit_plan.go, sqle/model/audit_plan_list.go, sqle/model/audit_plan_test.go, sqle/model/rule.go, sqle/server/sqled.go
=> Issue960 debug

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/model/workflow.go
=> Batch cancel

sqle/model/project.go
=> issue_960 debug

sqle/api/controller/v1/workflow.go, sqle/model/workflow.go
=> Fix create workflow

sqle/api/cloudbeaver_wrapper/service/instance.go
=> Issue 1099

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix field type and remove useless parameter

sqle/model/project_permission.go
=> issue_960 debug fix IsProjectMember

sqle/cmd/scannerd/cmd/mybatis.go, sqle/cmd/scannerd/cmd/root.go, sqle/cmd/scannerd/cmd/slowquery.go, sqle/pkg/scanner/client.go
=> issue_980 scanner add project param

sqle/api/controller/v1/user.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix json format

sqle/model/instance.go, sqle/model/project.go, sqle/model/project_list.go, sqle/model/project_permission.go, sqle/model/role.go, sqle/pkg/scanner/client.go
=> issue_960 debug: update member(group) list instance filter

sqle/api/controller/v1/user.go, sqle/api/controller/v1/user_group.go, sqle/model/instance.go, sqle/model/project_permission.go, sqle/model/role.go
=> issue_960 debug: sql query : manager can see all instance

sqle/model/project_permission_test.go
=> issue_960 debug fix unit test

sqle/model/instance_list.go
=> fix sql: delete useless table

sqle/model/role_list.go, sqle/model/user_group.go, sqle/model/user_list.go
=> remove code of old model

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add new return field

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> rename new return field

sqle/api/controller/v1/statistic.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 1127 api

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 1130 api

sqle/api/controller/v1/rule.go, sqle/model/rule.go
=> issue 1130

sqle/api/middleware/jwt_test.go, sqle/model/audit_plan_list_test.go, sqle/model/project_permission_test.go, sqle/server/sqled_test.go
=> Fix unit test

sqle/api/app.go, sqle/api/controller/v1/statistic.go, sqle/model/audit_plan.go, sqle/model/instance_list.go, sqle/model/rule_list.go, sqle/model/sql_whitelist.go, sqle/model/user.go, sqle/model/workflow_list.go
=> Issue 1127

spelling_dict.txt
=> fix:spell check

sqle/model/audit_plan.go
https://github.com/actiontech/sqle-ee/issues/531
=> ee 531 sync audit plan

sqle/api/controller/v1/workflow.go
=> issue_1164

sqle/model/project.go, sqle/model/user.go
=> issue_1161

sqle/api/app.go, sqle/api/controller/v1/user.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/user.go
=> issue 1162

sqle/api/controller/v1/user_group.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/project.go
=> return users of groups when get member groups

sqle/api/controller/v1/role.go, sqle/api/controller/v1/user_group.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/role.go, sqle/model/user_group.go
=> Issue1182 change api

sqle/server/sqled.go
=> issue 1180

sqle/api/app.go, sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 1191 api

go.mod, go.sum, vendor/github.com/actiontech/mybatis-mapper-2-sql/ast/dynamic.go, vendor/modules.txt
=> support #1193, update mybatis parser lib

sqle/api/controller/v1/workflow.go
=> can not reject workflow if there is any task is scheduled to be executed

sqle/api/app.go, sqle/api/controller/v1/rule.go
=> Issue 1191

sqle/model/project.go, sqle/model/project_list.go, sqle/model/user.go, sqle/model/user_group.go
=> issue 1204

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/audit_plan.go, sqle/api/controller/v2/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/rule.go, sqle/utils/util.go
=> 点击规则模板名称，跳转规则详情页面

sqle/api/controller/v1/workflow.go, sqle/model/operation.go, sqle/model/project.go, sqle/model/project_permission.go, sqle/model/workflow.go
=> Issue 1190

sqle/api/controller/v1/rule.go
=> issue 1191 update contentType

sqle/api/controller/v1/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 1211 api

sqle/model/operation.go
=> issue 1190 fix bug

sqle/api/controller/v1/project_permission.go
=> issue 1205

sqle/api/controller/v1/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/instance.go, sqle/model/project_permission.go, sqle/model/project_permission_test.go
#1211 
1. 之前提交的接口参数 IP 不是很合理, 改为 Host
2. 实现此issue
=> Issue 1211

sqle/api/controller/v1/audit_plan.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> return instance type for display

sqle/model/user.go
=> issue_1222

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/configuration.go
=> Issue 1224

spelling_dict.txt, sqle/model/workflow.go, sqle/pkg/im/dingding/dingding.go, sqle/pkg/im/im.go
=> Issue 1177 optimize

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue 1227

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> test ding talk test button api

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue 1234 api

sqle/api/app.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/project.go, sqle/api/controller/v1/rule.go, sqle/api/controller/v1/sql_whitelist.go, sqle/api/controller/v1/user.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Request parameter rule name is required

sqle/api/controller/v1/workflow.go, sqle/model/workflow.go
=> issue 1234

sqle/api/controller/v1/workflow.go, sqle/model/configuration.go, sqle/pkg/im/dingding/dingding.go, sqle/pkg/im/im.go
=> Issue 1241

sqle/api/controller/v1/task.go, sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/task.go, sqle/model/workflow.go
=> issue_1234 Add manual online status

sqle/api/app.go, sqle/api/cloudbeaver_wrapper/app.go, sqle/api/cloudbeaver_wrapper/service/gql.go, sqle/api/cloudbeaver_wrapper/service/gql_test.go, sqle/api/cloudbeaver_wrapper/service/instance.go, sqle/api/cloudbeaver_wrapper/service/user.go
=> Issue 1237

sqle/api/controller/v1/sync_instance.go, sqle/api/controller/v1/sync_instance_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue 1253 api

sqle/api/controller/v1/sync_instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Sync api fix

sqle/model/configuration.go, sqle/model/instance.go, sqle/model/utils.go
=> add sync instance model

sqle/model/configuration.go, sqle/notification/notification.go
=> issue_1248

sqle/api/cloudbeaver_wrapper/service/gql.go
=> issue_1237 fix bug

sqle/api/controller/v1/instance.go, sqle/api/controller/v2/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/instance.go, sqle/model/instance_list.go
=> return source of instance when get instance list and detail

sqle/api/app.go, sqle/api/controller/v1/sync_instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> change api definition

sqle/pkg/sync_Task/sync_task_ce.go, sqle/server/sqled.go
https://github.com/actiontech/sqle/issues/1253
=> remove package

go.mod, go.sum, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/api/controller/validator.go, sqle/api/controller/validator_test.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/workflow.go, sqle/model/workflow_list.go, sqle/utils/util.go, vendor/github.com/bwmarrin/snowflake/.travis.yml, vendor/github.com/bwmarrin/snowflake/LICENSE, vendor/github.com/bwmarrin/snowflake/README.md, vendor/github.com/bwmarrin/snowflake/snowflake.go, vendor/modules.txt
=> Issue 1280

sqle/api/app.go, sqle/api/controller/validator_test.go
=> Issue 1280 fix

spelling_dict.txt
=> chore:fix spell check

sqle/api/controller/v2/workflow.go
=> fix:fix a error call

sqle/api/controller/v1/operation_record.go, sqle/api/controller/v1/project.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue 1281 api

sqle/api/controller/v1/operation_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:add TotalNum resp field

sqle/api/controller/v1/operation_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> add desc field for tips

sqle/api/app.go, sqle/api/controller/v1/operation_record.go, sqle/api/middleware/operation_record_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/operation_record.go, sqle/model/utils.go
=> feat:add operation log record middleware

sqle/api/app.go, sqle/api/controller/v1/operation_record.go, sqle/api/controller/v1/operation_recored_ce.go
=> Issue 1281 imple

sqle/api/controller/v1/operation_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> chore:change field OperationContent

sqle/model/operation_record.go
=> move const to ee file

sqle/api/controller/v1/operation_record.go
=> chore:list operation record req struct

sqle/api/controller/v1/project.go
=> fix:fix query error

sqle/model/workflow.go
=> add model function for ee

sqle/model/operation_record.go, sqle/server/clean.go, sqle/server/sqled.go
=> feat:clean expired operation record log

sqle/api/app.go, sqle/api/controller/v1/auth.go, sqle/api/controller/v2/auth.go, sqle/api/middleware/jwt.go, sqle/docs/docs.go
=> Cloudbeaver authorization

sqle/common/instance.go, sqle/model/instance.go, sqle/model/sync_instance_task.go, sqle/model/workflow.go
=> chore:optimize check delete instance sql

sqle/api/controller/v1/auth.go, sqle/api/controller/v2/auth.go
=> bug: the response will be rewrote when login with wrong password

sqle/api/controller/v1/operation_record.go, sqle/api/controller/v1/sync_instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix:syntax error and swagger

sqle/model/sync_instance_task.go
https://github.com/actiontech/sqle/issues/1281
=> chore:remove to ee

sqle/api/middleware/jwt.go
=> return error 401 to lead front-end to fill login target param to redirect to specified page after logging in

sqle/notification/notification.go
=> amend the field

sqle/api/controller/v1/operation_record.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
https://github.com/actiontech/sqle/issues/1281
=> return field for front-end to filter options to display

sqle/pkg/im/im.go
=> fix:api modify

sqle/api/controller/v1/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> deprecate api which has a bug

sqle/api/app.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v1/workflow_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> Issue 1326 api

sqle/api/app.go, sqle/api/controller/v1/operation_record.go, sqle/api/controller/v1/operation_recored_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> issue_1324_api

sqle/model/task.go, sqle/model/workflow.go, sqle/model/workflow_list.go
=> Issue 1326

sqle/model/task.go
=> chore:add task end time

sqle/utils/aes.go
=> fix:Blocking problems caused by nested locks

sqle/api/cloudbeaver_wrapper/service/audit.go
=> to make it behaves the same as workflow

sqle/api/controller/v1/task.go
https://github.com/actiontech/sqle/issues/1364
=> fix:audit plugin choose error

sqle/api/controller/v1/user.go
=> fix wrong request type used and support change phone in user center

sqle/api/app.go, sqle/api/controller/v1/dashboard.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/workflow_list.go
=> Issue 1361

sqle/driver/plugin_adapter_v1.go, sqle/driver/plugin_adapter_v2.go, sqle/driver/plugin_manager.go, sqle/driver/v1/driver.go
=> fix:start cmd repeatedly

sqle/api/app.go, sqle/api/controller/v1/configuration.go, sqle/api/controller/v1/configuration_ce.go, sqle/api/controller/v1/configuration_comm.go, sqle/model/project.go
=> Issue 1374 imple

sqle/api/controller/v1/configuration_ce.go, sqle/api/controller/v1/configuration_comm.go, sqle/model/configuration.go, sqle/model/utils.go
=> Issue 1374 2

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/configuration.go
=> Issue 1374 3

sqle/api/cloudbeaver_wrapper/service/instance.go, sqle/api/controller/v1/audit_plan.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/project.go, sqle/api/controller/v1/sql_whitelist.go, sqle/api/controller/v1/user.go, sqle/api/controller/v1/user_group.go, sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/instance.go, sqle/api/controller/v2/workflow.go, sqle/model/audit_plan.go, sqle/model/instance.go, sqle/model/project.go, sqle/model/project_list.go, sqle/model/utils.go, sqle/server/auditplan/manager.go, sqle/server/auditplan/manager_test.go
=> Issue 1375

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix:swagger

sqle/model/project.go, sqle/model/workflow.go
=> Issue 1326/optimize

sqle/model/project.go
=> fix spelling error

sqle/model/audit_plan.go
=> remove debug log

sqle/model/workflow.go
=> limit length of description of workflow as 3000 bytes

sqle/model/workflow.go
=> fix:use workflow id to workflow record id

sqle/api/controller/v1/instance.go, sqle/common/instance.go
=> make message readable

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/rule.go
feat:
- 新增实现：支持以rule_name列表获取rules列表
#1411 
fix:
- docs：修复 swagger 文档
#1419
=> feat(rules): 新增实现：支持以rule_name列表获取rules列表

sqle/api/app.go
fix:
- 修复错误的 api router 对象使用
#1416
=> fix: fix api router

sqle/api/controller/v2/audit_plan.go, sqle/api/controller/v2/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
fix:
- 修复 api 示例文本
related: #1411 #1416
=> fix(api): fix api example

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
fix：
- 调整了请求参数格式，以便前端代码能够正常工作
- 更新了 swagger API 相关文件
ref：https://github.com/swaggo/swag#declarative-comments-format
related: #1411 #1420
=> fix: 调整 API query

sqle/api/controller/v1/rule.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix(rules): 调整 /v1/rules 请求参数格式

sqle/model/task.go, sqle/server/audit.go
=> fix(audit): model.AuditResult 去重

sqle/api/controller/v2/audit_plan.go, sqle/api/controller/v2/task.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix: fix api operation id

sqle/driver/mysql/rule/rule.go
=> feat: 新增审核规则：禁止全索引扫描

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/session/context.go
=> feat: 新增规则: update/delete 最大影响行数

sqle/driver/mysql/rule/rule.go
=> feat: 新增审核规则，检查绑定变量数量

sqle/driver/mysql/audit_executed_sql_test.go, sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> Issue 1432

sqle/driver/mysql/mysql.go
=> fix:add optional module

sqle/driver/mysql/rule/rule.go
=> Issue1432 fix bug

sqle/server/auditplan/meta.go
feat:
- API: GET:/v1/audit_plan_types 返回值增加 mysql processlist 任务类型
#1450
=> feat(auditplan): 新增审核任务类型 mysql processlist

spelling_dict.txt
=> fix(spell): 更新拼写检查字典

sqle/driver/mysql/rule/rule.go
=> avoid panic

sqle/api/app.go, sqle/api/controller/v1/instance.go, sqle/api/controller/v1/task.go, sqle/api/controller/v2/instance.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/rule.go
=> Issue 1452

sqle/server/auditplan/meta.go, sqle/server/auditplan/task.go
feat:
- 新增了审核任务类型 mysql processlist 的定义和实现
#1450 
fix：
- log 模块新增了 Debug() 和 Debugf() 函数来精简代码
=> feat(auditplan): 新增审核任务类型实现，mysql processlist

sqle/server/auditplan/meta.go, sqle/server/auditplan/task_ce.go
=> feat(auditplan): 新增慢日志审核任务

sqle/server/auditplan/meta.go
=> fix(auditplan): mysql.slow_log 采集新增采集频率支持

sqle/driver/mysql/audit_executed_sql_test.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> fix bug and add unit test

sqle/server/auditplan/task.go
=> fix(auditplan): 结构体新增query_time执行时间字段

sqle/driver/mysql/audit_executed_sql_test.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> Cherry pick

sqle/model/management_permission.go
=> bug: it will delete permission of all users

sqle/server/auditplan/task.go
=> refactor(auditplan): 将 processlist 审核任务审核抽取为公共函数

sqle/driver/mysql/util/parser_helper.go
=> fix(rule): 增加空指针判断，防止程序 panic

sqle/api/controller/v2/workflow.go, sqle/model/workflow.go
=> fix(workflow): 调整工单的步骤判断

sqle/api/app.go, sqle/api/controller/v2/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/driver/plugin_manager.go
=> feat(config): 新增API以获取支持的数据库类型及其默认端口

spelling_dict.txt
=> chore(spell): update dict

sqle/server/auditplan/task.go
=> reuse code

sqle/api/app.go, sqle/api/controller/base.go, sqle/api/controller/v1/configuration.go, sqle/api/controller/v1/configuration_ce.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/errors/errors.go
=> feat(webhook): 新增webhook相关API定义

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go
=> this rule should compare value type

sqle/api/controller/v1/configuration.go, sqle/api/controller/v1/configuration_ce.go, sqle/model/configuration.go
=> feat: 获取/更新webhook的API实现

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix(webhook): fix api tag

sqle/model/configuration.go
=> fix(webhook): fix update webhook config error

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/model/configuration.go, sqle/model/utils.go
=> fix: 调整webhook使用token

sqle/notification/notification.go, sqle/notification/webhook.go, sqle/utils/retry/config.go, sqle/utils/retry/retry.go, sqle/utils/retry/retry_test.go, sqle/utils/util.go
=> feat(webhook): 新增工单变化时，webhook 发送请求

spelling_dict.txt, sqle/model/configuration.go
=> fix(webhook)：修复token无法被置为空值的问题

sqle/notification/webhook.go
=> fix(webhook): fix interval second

sqle/notification/notification.go, sqle/notification/webhook.go
=> refactor(webhook): 函数签名优化

sqle/api/controller/v1/workflow.go, sqle/server/workflow_schedule.go
feat:
- 新增中止单个上线任务的api实现
- 新增中止工单多个上线任务的API实现
#1519
=> feat(workflow): 新增中止上线的API实现

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix(api): fix api version

sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> fix(api): 概览接口支持中止的状态

sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/workflow.go, sqle/driver/mysql/executor/executor.go, sqle/driver/mysql/mysql.go, sqle/driver/plugin_adapter_v1.go, sqle/driver/plugin_adapter_v2.go, sqle/server/sqled.go, sqle/server/workflow_schedule.go, sqle/utils/func.go, sqle/utils/func_test.go, sqle/utils/util.go, sqle/utils/util_test.go
fix:
- API 实现，移除了不必要的检查
- utils：修复了TryClose() 在多次 close channel 的情况下，可能出现 panic 的问题，且新增了单元测试
feat:
- mysql 插件新增 KillProcess() 实现
- 新增了 sqle 对 mysql 插件 KillProcess() 的调用
#1519
=> feat: MySQL 审核插件实现 KillProcess()

sqle/api/controller/v1/workflow.go, sqle/api/controller/v2/task.go, sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml, sqle/driver/mysql/mysql.go, sqle/model/task.go, sqle/model/workflow.go, sqle/server/sqled.go, sqle/server/workflow_schedule.go
重构了中止失败的流程，由直接中止变更为轮询数据库状态来判断；
重构了中止流程下的状态判断，支持了中止流程；
#1519
=> feat(workflow): 新增工单任务的状态变化

sqle/server/sqled.go, sqle/server/workflow_schedule.go
fix:修复在所有任务执行成功的情况下，工单状态没有更新的问题
refactor: 重构了在「SQL中止上线」的场景下，工单状态更新的问题。
#1519
=> fix: 修复在所有任务执行成功的情况下，工单状态没有更新的问题

sqle/driver/mysql/mysql.go
=> fix(mysql): fix db close() after execution

sqle/api/controller/v1/workflow.go
fix: 
- 修复 task 枚举值，避免字符串造成前端页面故障
#1519
=> fix: 修复 Task 状态枚举值

sqle/server/sqled.go
=> fix wrong index

sqle/model/configuration.go
#1396 
feat:
1. 为IM添加了加密AppSecret和解密AppSecret功能
=> fix issue 1396

sqle/model/configuration.go
=> fix-issue1396

sqle/model/audit_plan.go, sqle/model/audit_plan_report.go, sqle/model/audit_plan_test.go, sqle/server/auditplan/task.go
=> Fix issue1518

sqle/api/controller/v2/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> feat(workflow): 创建工单接口新增返回工单ID

sqle/api/controller/v2/workflow.go
=> feat(workflow): 创建工单成功后返回工单ID

sqle/model/audit_plan.go
=> fix: 修复函数逻辑错误

sqle/driver/mysql/audit_test.go, sqle/driver/mysql/util/parser_helper.go
=> fix: 支持含有子查询的负向查询的语句检查

sqle/api/controller/v1/rule.go, sqle/model/instance.go, sqle/model/rule.go
fix:
- 优化了检查关联扫描任务的错误提示
- 新增了检查关联数据源的检查
#1535
=> fix(rule_template): 删除项目规则模板前，检查是否有关联的数据源

sqle/api/controller/v1/workflow.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> api(workflow): 工单列表接口新增工单ID过滤

sqle/api/controller/v1/workflow.go, sqle/model/workflow_list.go
=> feat(workflow): 新增支持通过工单ID过滤工单列表

sqle/notification/notification.go
=> fix(notification): 工单消息推送中新增工单ID

sqle/api/controller/v1/configuration.go, sqle/docs/docs.go, sqle/docs/swagger.json, sqle/docs/swagger.yaml
=> feat(configurations): 新增 API 支持操作记录过期时间的设置和获取

sqle/api/controller/v1/configuration.go
=> fix: 禁用配置时不再更新其他具体配置项

sqle/pkg/im/dingding/dingding.go
=> fix: 重复安装sqle，钉钉无法收到审批

sqle/api/controller/v1/configuration.go, sqle/model/configuration.go, sqle/server/clean.go
feat:
- 新增支持获取操作记录过期时间
- 新增支持更新操作记录过期时间
- 新增操作过期时间设置能够正确影响清理任务
- 移除了一段无用代码
#1562
=> feat: 新增操作记录过期时间的支持

sqle/api/controller/v2/workflow.go
=> fix: 新增工单前检查工单名称是否已经存在

sqle/driver/mysql/rule/rule.go
=> Fix:规则“表中包含有太多的列”，在扫描任务中无效

sqle/driver/mysql/audit_offline_test.go, sqle/driver/mysql/audit_test.go, sqle/driver/mysql/rule/rule.go, sqle/driver/mysql/util/parser_helper.go
=> MySQL新增三条规则

sqle/server/auditplan/meta.go, sqle/server/auditplan/task.go
=> chore:Baidu rds slow log has no time limit

sqle/model/utils.go
=> fix:Real-time updating of plugin-side rules

sqle/api/controller/v1/audit_plan.go, sqle/cmd/scannerd/scanners/mybatis/mybatis.go, sqle/pkg/scanner/client.go
=> refactor:Using pointers instead of slices makes the code simpler

sqle/driver/mysql/rollback.go
=> fix issue 1599

sqle/model/audit_plan.go, sqle/server/auditplan/task.go
#791(https://github.com/actiontech/sqle-ee/issues/791)
=> Fix issue791
